// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const countConsideredEntities = `-- name: CountConsideredEntities :one
SELECT count(*) AS considered
FROM entities e
WHERE e.project_id = $1 AND e.entity_type_id = ANY($2::uuid[])
`

type CountConsideredEntitiesParams struct {
	ProjectID   uuid.UUID
	EntityTypes []uuid.UUID
}

// CountConsideredEntities is the denominator of an orphan report: how
// many entities this run looked at.
//
// It exists because an empty findings list means one of two entirely
// different things -- nothing is orphaned, or nothing was considered --
// and those are the same JSON without a count beside them. Ignored
// entity types are subtracted from the id list before it gets here, so a
// total cannot count what the report excludes.
func (q *Queries) CountConsideredEntities(ctx context.Context, arg CountConsideredEntitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsideredEntities, arg.ProjectID, arg.EntityTypes)
	var considered int64
	err := row.Scan(&considered)
	return considered, err
}

const listNormalisedInEdges = `-- name: ListNormalisedInEdges :many
SELECT dependent, needed, kind
FROM (
        SELECT r.target_id AS dependent, r.source_id AS needed,
               'gate'::text AS kind, r.invalid AS invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($2::uuid[])
    UNION ALL
        SELECT r.source_id, r.target_id, 'gate'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($3::uuid[])
    UNION ALL
        SELECT r.target_id, r.source_id, 'containment'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($4::uuid[])
    UNION ALL
        SELECT r.target_id, r.source_id, 'adjacency'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($5::uuid[])
    UNION ALL
        SELECT r.source_id, r.target_id, 'adjacency'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($5::uuid[])
) AS edges
WHERE dependent = ANY($6::uuid[])
  AND (NOT $7::boolean OR NOT invalid)
`

type ListNormalisedInEdgesParams struct {
	ProjectID      uuid.UUID
	ForwardGates   []uuid.UUID
	ReverseGates   []uuid.UUID
	Containment    []uuid.UUID
	Adjacency      []uuid.UUID
	Dependents     []uuid.UUID
	ExcludeInvalid bool
}

type ListNormalisedInEdgesRow struct {
	Dependent uuid.UUID
	Needed    uuid.UUID
	Kind      string
}

// ListNormalisedInEdges is the in-neighbourhood of a set of entities in
// the engine's one normalised direction, needed → dependent.
//
// The two gating arms are the reversal itself: a forward type's edge
// gates its target, a reverse (`prerequisite_of`) type's edge gates its
// source. After this statement nothing downstream knows which trait an
// edge carried, which is the whole point of normalising.
//
// Containment has an arm of its own rather than riding in with the
// forward gates, because the unreachable analysis owes a reason and
// "the only way in is through a container nobody can reach" is a
// different sentence, with a different fix, from "every route to it is
// blocked". Everything else treats a container as a gate.
//
// The adjacency arms are symmetric types, listed in both directions and
// marked `adjacency`: a symmetric edge joins two entities without
// ordering them, so it may admit under `any` and may never be required
// under `all`.
//
// exclude_invalid is a parameter and not a constant because this
// package's default is to **follow** invalid edges -- see
// analysis.Params for the argument, which is that `invalid` describes a
// row's fields and this question reads only its endpoints.
func (q *Queries) ListNormalisedInEdges(ctx context.Context, arg ListNormalisedInEdgesParams) ([]ListNormalisedInEdgesRow, error) {
	rows, err := q.db.Query(ctx, listNormalisedInEdges,
		arg.ProjectID,
		arg.ForwardGates,
		arg.ReverseGates,
		arg.Containment,
		arg.Adjacency,
		arg.Dependents,
		arg.ExcludeInvalid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNormalisedInEdgesRow
	for rows.Next() {
		var i ListNormalisedInEdgesRow
		if err := rows.Scan(&i.Dependent, &i.Needed, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphansPage = `-- name: ListOrphansPage :many
SELECT e.id, e.key, e.name, et.key AS entity_type_key,
       ind.n::bigint AS in_degree, outd.n::bigint AS out_degree
FROM entities e
JOIN entity_types et ON et.id = e.entity_type_id AND et.project_id = $1
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM relations r
    WHERE r.project_id = $1 AND r.target_id = e.id
      AND NOT (r.relation_type_id = ANY($2::uuid[]))
) ind ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM relations r
    WHERE r.project_id = $1 AND r.source_id = e.id
      AND NOT (r.relation_type_id = ANY($2::uuid[]))
) outd ON true
WHERE e.project_id = $1
  AND e.entity_type_id = ANY($3::uuid[])
  AND CASE $4::text
        WHEN 'sink'   THEN ind.n > 0 AND outd.n = 0
        WHEN 'source' THEN ind.n = 0 AND outd.n > 0
        ELSE ind.n = 0 AND outd.n = 0
      END
  AND ($5::uuid IS NULL
       OR (et.key, lower(e.key), e.id) > ($6::text,
                                          $7::text,
                                          $5::uuid))
ORDER BY et.key, lower(e.key), e.id
LIMIT $8::int
`

type ListOrphansPageParams struct {
	ProjectID            uuid.UUID
	IgnoredRelationTypes []uuid.UUID
	EntityTypes          []uuid.UUID
	Mode                 string
	AfterID              *uuid.UUID
	AfterEntityType      *string
	AfterKey             *string
	Limit                int32
}

type ListOrphansPageRow struct {
	ID            uuid.UUID
	Key           string
	Name          string
	EntityTypeKey string
	InDegree      int64
	OutDegree     int64
}

// ListOrphansPage is the orphan analysis, and it is **an aggregate with
// no recursion anywhere in it**.
//
// That is stated because three analyses of runtime-built recursive SQL
// in a row make this one look like it should be a fourth. It is not: an
// orphan is an entity with no edges, which is a degree, and a degree is
// a count. So this is static SQL and goes through sqlc like every other
// statement in this repository.
//
// **It reads `relations` regardless of `invalid`**, which is the
// decision analysis.Params argues in full and the place it is most
// likely to be forgotten: an entity whose only edge is flagged invalid
// **is not an orphan**, and calling it one would send a designer to
// delete content that has edges. `invalid` describes whether a row's
// own fields still fit its type's field_schema; it says nothing about
// the row's endpoints, and endpoints are the only thing this statement
// reads. Adding `AND r.invalid = false` below is the one-line "tidy"
// TestAnEntityWhoseOnlyEdgeIsInvalidIsNotAnOrphan exists to make loud.
//
// ignored_relation_types is the annotation types, and it is a
// **subtraction** rather than a list of types to count, deliberately: an
// orphan is an entity nothing points at, so every type counts unless a
// designer has said in the metamodel that this one is decoration. An
// empty array excludes nothing, which is what a game that declared no
// traits gets -- and which is a perfectly meaningful input rather than a
// refusal, unlike the other three analyses.
//
// The keyset is (entity type key, folded entity key, id), which is a
// total order, so a cursor can neither skip nor repeat a row. Keys are
// folded because every key in Maestro is matched without regard to case,
// and a sort that disagreed with the fold would order two spellings of
// one key inconsistently between pages.
func (q *Queries) ListOrphansPage(ctx context.Context, arg ListOrphansPageParams) ([]ListOrphansPageRow, error) {
	rows, err := q.db.Query(ctx, listOrphansPage,
		arg.ProjectID,
		arg.IgnoredRelationTypes,
		arg.EntityTypes,
		arg.Mode,
		arg.AfterID,
		arg.AfterEntityType,
		arg.AfterKey,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphansPageRow
	for rows.Next() {
		var i ListOrphansPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.EntityTypeKey,
			&i.InDegree,
			&i.OutDegree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByIDs = `-- name: ListRelationsByIDs :many
SELECT r.id, r.relation_type_id, r.source_id, r.target_id, r.invalid
FROM relations r
WHERE r.project_id = $1 AND r.id = ANY($2::uuid[])
`

type ListRelationsByIDsParams struct {
	ProjectID uuid.UUID
	Ids       []uuid.UUID
}

type ListRelationsByIDsRow struct {
	ID             uuid.UUID
	RelationTypeID uuid.UUID
	SourceID       uuid.UUID
	TargetID       uuid.UUID
	Invalid        bool
}

// ListRelationsByIDs reads the edges of a cycle back, so a finding can
// name the relation *type* of every one of them -- which is the field
// Task 4's widening of internal/graph exists for, because the first
// thing a designer does with a reported loop is ask whether the type
// should have been declared gating at all.
//
// The ids come out of a walk this game's own project id already bounded,
// so the project filter here is redundant today. It is written anyway,
// for the reason every statement in this file carries one: isolation is
// a property of the statement and not of the caller that happens to feed
// it, and the next caller of this statement will not be that walk.
func (q *Queries) ListRelationsByIDs(ctx context.Context, arg ListRelationsByIDsParams) ([]ListRelationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listRelationsByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationsByIDsRow
	for rows.Next() {
		var i ListRelationsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelationTypeID,
			&i.SourceID,
			&i.TargetID,
			&i.Invalid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteStepsByRouteKey = `-- name: ListRouteStepsByRouteKey :many

SELECT s.position, s.entity_id, s.entity_type_key, s.entity_key
FROM route_steps s
JOIN routes rt ON rt.id = s.route_id AND rt.project_id = s.project_id
WHERE s.project_id = $1 AND lower(rt.key) = lower($2)
ORDER BY s.position
`

type ListRouteStepsByRouteKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

type ListRouteStepsByRouteKeyRow struct {
	Position      int32
	EntityID      *uuid.UUID
	EntityTypeKey string
	EntityKey     string
}

// Statements for internal/analysis. Every one of them filters on the
// resolved project id, in SQL and never in Go, which is this
// repository's isolation rule and not this file's own decision.
//
// The recursive walks the three analyses run are **not** here: they are
// emitted by internal/graph at run time and therefore cannot go through
// sqlc, exactly as internal/views/compile.go's statements cannot. What
// is here is everything static.
// ListRouteStepsByRouteKey reads a route's steps in order, addressed by
// the route's key and this game's id.
//
// entity_id is nullable: 0013_analysis.sql tombstones a step whose
// entity was deleted with ON DELETE SET NULL rather than removing it, so
// a route visibly keeps a step it can no longer resolve. A caller must
// have an opinion about the null; analysis.routeSeeds contributes no
// seed for one and still names it in the seed report.
func (q *Queries) ListRouteStepsByRouteKey(ctx context.Context, arg ListRouteStepsByRouteKeyParams) ([]ListRouteStepsByRouteKeyRow, error) {
	rows, err := q.db.Query(ctx, listRouteStepsByRouteKey, arg.ProjectID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteStepsByRouteKeyRow
	for rows.Next() {
		var i ListRouteStepsByRouteKeyRow
		if err := rows.Scan(
			&i.Position,
			&i.EntityID,
			&i.EntityTypeKey,
			&i.EntityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeExists = `-- name: RouteExists :one
SELECT EXISTS (
    SELECT 1 FROM routes WHERE project_id = $1 AND lower(key) = lower($2)
) AS route_exists
`

type RouteExistsParams struct {
	ProjectID uuid.UUID
	Key       string
}

// RouteExists separates "no such route" from "a route with no steps",
// which ListRouteStepsByRouteKey answers identically and which are two
// different refusals.
func (q *Queries) RouteExists(ctx context.Context, arg RouteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, routeExists, arg.ProjectID, arg.Key)
	var route_exists bool
	err := row.Scan(&route_exists)
	return route_exists, err
}
