// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConsideredEntities = `-- name: CountConsideredEntities :one
SELECT count(*) AS considered
FROM entities e
WHERE e.project_id = $1 AND e.entity_type_id = ANY($2::uuid[])
`

type CountConsideredEntitiesParams struct {
	ProjectID   uuid.UUID
	EntityTypes []uuid.UUID
}

// CountConsideredEntities is the denominator of an orphan report: how
// many entities this run looked at.
//
// It exists because an empty findings list means one of two entirely
// different things -- nothing is orphaned, or nothing was considered --
// and those are the same JSON without a count beside them. Ignored
// entity types are subtracted from the id list before it gets here, so a
// total cannot count what the report excludes.
func (q *Queries) CountConsideredEntities(ctx context.Context, arg CountConsideredEntitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsideredEntities, arg.ProjectID, arg.EntityTypes)
	var considered int64
	err := row.Scan(&considered)
	return considered, err
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM routes
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteRouteParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// The steps go with it: route_steps keys into routes with ON DELETE
// CASCADE (0013_analysis.sql), so this is one statement rather than two.
// execrows, not exec, because zero rows is the answer to "was it there"
// -- a caller that resolved the route a moment earlier and deletes
// nothing raced another remover, and hears not_found rather than a
// success it can publish an event about.
func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRouteSteps = `-- name: DeleteRouteSteps :exec
DELETE FROM route_steps
WHERE project_id = $1::uuid AND route_id = $2::uuid
`

type DeleteRouteStepsParams struct {
	ProjectID uuid.UUID
	RouteID   uuid.UUID
}

// The first half of the step rewrite. Delete-then-insert rather than a
// diff: steps are positional, the list is small, and a diff would be a
// second place that decides what a step is. It runs inside the same
// transaction as the route row's compare-and-set, so a step list never
// lands beside a route row that rolled back.
func (q *Queries) DeleteRouteSteps(ctx context.Context, arg DeleteRouteStepsParams) error {
	_, err := q.db.Exec(ctx, deleteRouteSteps, arg.ProjectID, arg.RouteID)
	return err
}

const getDesignVersion = `-- name: GetDesignVersion :one
SELECT design_version FROM projects WHERE id = $1::uuid
`

// The game's current design version, which is the staleness signal a
// stored route verdict is compared against. It is maintained by
// 0013_analysis.sql's twelve triggers and never by Go, for the reason
// that migration argues: a bump a query has to remember is a bump the
// twenty-first query forgets.
func (q *Queries) GetDesignVersion(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getDesignVersion, projectID)
	var design_version int64
	err := row.Scan(&design_version)
	return design_version, err
}

const getRouteByKey = `-- name: GetRouteByKey :one
SELECT id, project_id, key, name, description, params, version, last_checked_at, last_checked_design_version, last_check, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM routes
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
`

type GetRouteByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetRouteByKey(ctx context.Context, arg GetRouteByKeyParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByKey, arg.ProjectID, arg.Key)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Params,
		&i.Version,
		&i.LastCheckedAt,
		&i.LastCheckedDesignVersion,
		&i.LastCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getRouteByKeyForUpdate = `-- name: GetRouteByKeyForUpdate :one
SELECT id, project_id, key, name, description, params, version, last_checked_at, last_checked_design_version, last_check, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM routes
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
FOR UPDATE
`

type GetRouteByKeyForUpdateParams struct {
	ProjectID uuid.UUID
	Key       string
}

// The upsert's own read, taken inside its transaction with the row lock
// held, so the spelling and the version a caller is told about are the
// ones its own write will meet. GetViewByKeyForUpdate's comment carries
// the argument for the lock: what it buys is not the refusal but the
// *number* the caller is told to merge onto.
func (q *Queries) GetRouteByKeyForUpdate(ctx context.Context, arg GetRouteByKeyForUpdateParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByKeyForUpdate, arg.ProjectID, arg.Key)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Params,
		&i.Version,
		&i.LastCheckedAt,
		&i.LastCheckedDesignVersion,
		&i.LastCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const insertRouteStep = `-- name: InsertRouteStep :exec
INSERT INTO route_steps (route_id, project_id, position, entity_id,
                         entity_type_key, entity_key, note)
VALUES ($1::uuid, $2::uuid,
        $3::integer, $4::uuid,
        $5::text, $6::text,
        $7::text)
`

type InsertRouteStepParams struct {
	RouteID       uuid.UUID
	ProjectID     uuid.UUID
	Position      int32
	EntityID      uuid.UUID
	EntityTypeKey string
	EntityKey     string
	Note          string
}

// entity_id is resolved by Go before this statement and is NOT NULL on
// write: a key that does not resolve is refused at the call, never
// stored as a tombstone. A tombstone is what a *deletion* leaves behind
// (ON DELETE SET NULL), and accepting one on write would let an agent
// author a route out of typos and be told it holds.
func (q *Queries) InsertRouteStep(ctx context.Context, arg InsertRouteStepParams) error {
	_, err := q.db.Exec(ctx, insertRouteStep,
		arg.RouteID,
		arg.ProjectID,
		arg.Position,
		arg.EntityID,
		arg.EntityTypeKey,
		arg.EntityKey,
		arg.Note,
	)
	return err
}

const listNormalisedInEdges = `-- name: ListNormalisedInEdges :many
SELECT dependent, needed, kind
FROM (
        SELECT r.target_id AS dependent, r.source_id AS needed,
               'gate'::text AS kind, r.invalid AS invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($2::uuid[])
    UNION ALL
        SELECT r.source_id, r.target_id, 'gate'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($3::uuid[])
    UNION ALL
        SELECT r.target_id, r.source_id, 'containment'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($4::uuid[])
    UNION ALL
        SELECT r.target_id, r.source_id, 'adjacency'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($5::uuid[])
    UNION ALL
        SELECT r.source_id, r.target_id, 'adjacency'::text, r.invalid
        FROM relations r
        WHERE r.project_id = $1
          AND r.relation_type_id = ANY($5::uuid[])
) AS edges
WHERE dependent = ANY($6::uuid[])
  AND (NOT $7::boolean OR NOT invalid)
`

type ListNormalisedInEdgesParams struct {
	ProjectID      uuid.UUID
	ForwardGates   []uuid.UUID
	ReverseGates   []uuid.UUID
	Containment    []uuid.UUID
	Adjacency      []uuid.UUID
	Dependents     []uuid.UUID
	ExcludeInvalid bool
}

type ListNormalisedInEdgesRow struct {
	Dependent uuid.UUID
	Needed    uuid.UUID
	Kind      string
}

// ListNormalisedInEdges is the in-neighbourhood of a set of entities in
// the engine's one normalised direction, needed → dependent.
//
// The two gating arms are the reversal itself: a forward type's edge
// gates its target, a reverse (`prerequisite_of`) type's edge gates its
// source. After this statement nothing downstream knows which trait an
// edge carried, which is the whole point of normalising.
//
// Containment has an arm of its own rather than riding in with the
// forward gates, because the unreachable analysis owes a reason and
// "the only way in is through a container nobody can reach" is a
// different sentence, with a different fix, from "every route to it is
// blocked". Everything else treats a container as a gate.
//
// The adjacency arms are symmetric types, listed in both directions and
// marked `adjacency`: a symmetric edge joins two entities without
// ordering them, so it may admit under `any` and may never be required
// under `all`.
//
// exclude_invalid is a parameter and not a constant because this
// package's default is to **follow** invalid edges -- see
// analysis.Params for the argument, which is that `invalid` describes a
// row's fields and this question reads only its endpoints.
func (q *Queries) ListNormalisedInEdges(ctx context.Context, arg ListNormalisedInEdgesParams) ([]ListNormalisedInEdgesRow, error) {
	rows, err := q.db.Query(ctx, listNormalisedInEdges,
		arg.ProjectID,
		arg.ForwardGates,
		arg.ReverseGates,
		arg.Containment,
		arg.Adjacency,
		arg.Dependents,
		arg.ExcludeInvalid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNormalisedInEdgesRow
	for rows.Next() {
		var i ListNormalisedInEdgesRow
		if err := rows.Scan(&i.Dependent, &i.Needed, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderingEdgesAmong = `-- name: ListOrderingEdgesAmong :many
SELECT r.id, r.relation_type_id, r.source_id, r.target_id
FROM relations r
WHERE r.project_id = $1
  AND r.relation_type_id = ANY($2::uuid[])
  AND r.source_id = ANY($3::uuid[])
  AND r.target_id = ANY($3::uuid[])
  AND (NOT $4::boolean OR NOT r.invalid)
`

type ListOrderingEdgesAmongParams struct {
	ProjectID      uuid.UUID
	RelationTypes  []uuid.UUID
	Entities       []uuid.UUID
	ExcludeInvalid bool
}

type ListOrderingEdgesAmongRow struct {
	ID             uuid.UUID
	RelationTypeID uuid.UUID
	SourceID       uuid.UUID
	TargetID       uuid.UUID
}

// ListOrderingEdgesAmong is the whole SQL side of the `out_of_order`
// verdict, and it is deliberately **not** a walk.
//
// routes.check's other three verdicts come out of the reachability
// closure; this one does not, and check.go says so beside the code that
// reads these rows. An ordering relation places two entities in a
// sequence, and whether a route respects it is a question about the two
// positions the route gives them -- a depth-1 lookup over the route's
// own entity ids, with no recursion, no seed and no closure. A reader
// who assumed the closure produced this verdict would go looking for a
// bug in the walk that is not there.
//
// Both endpoints are constrained to the route's own step entities: an
// ordering edge to something the route never mentions orders nothing
// the route claims.
func (q *Queries) ListOrderingEdgesAmong(ctx context.Context, arg ListOrderingEdgesAmongParams) ([]ListOrderingEdgesAmongRow, error) {
	rows, err := q.db.Query(ctx, listOrderingEdgesAmong,
		arg.ProjectID,
		arg.RelationTypes,
		arg.Entities,
		arg.ExcludeInvalid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderingEdgesAmongRow
	for rows.Next() {
		var i ListOrderingEdgesAmongRow
		if err := rows.Scan(
			&i.ID,
			&i.RelationTypeID,
			&i.SourceID,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphansPage = `-- name: ListOrphansPage :many
SELECT e.id, e.key, e.name, et.key AS entity_type_key,
       ind.n::bigint AS in_degree, outd.n::bigint AS out_degree
FROM entities e
JOIN entity_types et ON et.id = e.entity_type_id AND et.project_id = $1
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM relations r
    WHERE r.project_id = $1 AND r.target_id = e.id
      AND NOT (r.relation_type_id = ANY($2::uuid[]))
) ind ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM relations r
    WHERE r.project_id = $1 AND r.source_id = e.id
      AND NOT (r.relation_type_id = ANY($2::uuid[]))
) outd ON true
WHERE e.project_id = $1
  AND e.entity_type_id = ANY($3::uuid[])
  AND CASE $4::text
        WHEN 'sink'   THEN ind.n > 0 AND outd.n = 0
        WHEN 'source' THEN ind.n = 0 AND outd.n > 0
        ELSE ind.n = 0 AND outd.n = 0
      END
  AND ($5::uuid IS NULL
       OR (et.key, lower(e.key), e.id) > ($6::text,
                                          $7::text,
                                          $5::uuid))
ORDER BY et.key, lower(e.key), e.id
LIMIT $8::int
`

type ListOrphansPageParams struct {
	ProjectID            uuid.UUID
	IgnoredRelationTypes []uuid.UUID
	EntityTypes          []uuid.UUID
	Mode                 string
	AfterID              *uuid.UUID
	AfterEntityType      *string
	AfterKey             *string
	Limit                int32
}

type ListOrphansPageRow struct {
	ID            uuid.UUID
	Key           string
	Name          string
	EntityTypeKey string
	InDegree      int64
	OutDegree     int64
}

// ListOrphansPage is the orphan analysis, and it is **an aggregate with
// no recursion anywhere in it**.
//
// That is stated because three analyses of runtime-built recursive SQL
// in a row make this one look like it should be a fourth. It is not: an
// orphan is an entity with no edges, which is a degree, and a degree is
// a count. So this is static SQL and goes through sqlc like every other
// statement in this repository.
//
// **It reads `relations` regardless of `invalid`**, which is the
// decision analysis.Params argues in full and the place it is most
// likely to be forgotten: an entity whose only edge is flagged invalid
// **is not an orphan**, and calling it one would send a designer to
// delete content that has edges. `invalid` describes whether a row's
// own fields still fit its type's field_schema; it says nothing about
// the row's endpoints, and endpoints are the only thing this statement
// reads. Adding `AND r.invalid = false` below is the one-line "tidy"
// TestAnEntityWhoseOnlyEdgeIsInvalidIsNotAnOrphan exists to make loud.
//
// ignored_relation_types is the annotation types, and it is a
// **subtraction** rather than a list of types to count, deliberately: an
// orphan is an entity nothing points at, so every type counts unless a
// designer has said in the metamodel that this one is decoration. An
// empty array excludes nothing, which is what a game that declared no
// traits gets -- and which is a perfectly meaningful input rather than a
// refusal, unlike the other three analyses.
//
// The keyset is (entity type key, folded entity key, id), which is a
// total order, so a cursor can neither skip nor repeat a row. Keys are
// folded because every key in Maestro is matched without regard to case,
// and a sort that disagreed with the fold would order two spellings of
// one key inconsistently between pages.
func (q *Queries) ListOrphansPage(ctx context.Context, arg ListOrphansPageParams) ([]ListOrphansPageRow, error) {
	rows, err := q.db.Query(ctx, listOrphansPage,
		arg.ProjectID,
		arg.IgnoredRelationTypes,
		arg.EntityTypes,
		arg.Mode,
		arg.AfterID,
		arg.AfterEntityType,
		arg.AfterKey,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphansPageRow
	for rows.Next() {
		var i ListOrphansPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.EntityTypeKey,
			&i.InDegree,
			&i.OutDegree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByIDs = `-- name: ListRelationsByIDs :many
SELECT r.id, r.relation_type_id, r.source_id, r.target_id, r.invalid
FROM relations r
WHERE r.project_id = $1 AND r.id = ANY($2::uuid[])
`

type ListRelationsByIDsParams struct {
	ProjectID uuid.UUID
	Ids       []uuid.UUID
}

type ListRelationsByIDsRow struct {
	ID             uuid.UUID
	RelationTypeID uuid.UUID
	SourceID       uuid.UUID
	TargetID       uuid.UUID
	Invalid        bool
}

// ListRelationsByIDs reads the edges of a cycle back, so a finding can
// name the relation *type* of every one of them -- which is the field
// Task 4's widening of internal/graph exists for, because the first
// thing a designer does with a reported loop is ask whether the type
// should have been declared gating at all.
//
// The ids come out of a walk this game's own project id already bounded,
// so the project filter here is redundant today. It is written anyway,
// for the reason every statement in this file carries one: isolation is
// a property of the statement and not of the caller that happens to feed
// it, and the next caller of this statement will not be that walk.
func (q *Queries) ListRelationsByIDs(ctx context.Context, arg ListRelationsByIDsParams) ([]ListRelationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listRelationsByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationsByIDsRow
	for rows.Next() {
		var i ListRelationsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelationTypeID,
			&i.SourceID,
			&i.TargetID,
			&i.Invalid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteStepsByRouteID = `-- name: ListRouteStepsByRouteID :many
SELECT s.position, s.entity_id, s.entity_type_key, s.entity_key, s.note
FROM route_steps s
WHERE s.project_id = $1::uuid AND s.route_id = $2::uuid
ORDER BY s.position
`

type ListRouteStepsByRouteIDParams struct {
	ProjectID uuid.UUID
	RouteID   uuid.UUID
}

type ListRouteStepsByRouteIDRow struct {
	Position      int32
	EntityID      *uuid.UUID
	EntityTypeKey string
	EntityKey     string
	Note          string
}

// One route's steps in order, addressed by the route's id and this
// game's id. entity_id is nullable and a null is a tombstone; the
// stored key pair beside it is what a check reports as missing or moved.
func (q *Queries) ListRouteStepsByRouteID(ctx context.Context, arg ListRouteStepsByRouteIDParams) ([]ListRouteStepsByRouteIDRow, error) {
	rows, err := q.db.Query(ctx, listRouteStepsByRouteID, arg.ProjectID, arg.RouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteStepsByRouteIDRow
	for rows.Next() {
		var i ListRouteStepsByRouteIDRow
		if err := rows.Scan(
			&i.Position,
			&i.EntityID,
			&i.EntityTypeKey,
			&i.EntityKey,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteStepsByRouteKey = `-- name: ListRouteStepsByRouteKey :many

SELECT s.position, s.entity_id, s.entity_type_key, s.entity_key
FROM route_steps s
JOIN routes rt ON rt.id = s.route_id AND rt.project_id = s.project_id
WHERE s.project_id = $1 AND lower(rt.key) = lower($2)
ORDER BY s.position
`

type ListRouteStepsByRouteKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

type ListRouteStepsByRouteKeyRow struct {
	Position      int32
	EntityID      *uuid.UUID
	EntityTypeKey string
	EntityKey     string
}

// Statements for internal/analysis. Every one of them filters on the
// resolved project id, in SQL and never in Go, which is this
// repository's isolation rule and not this file's own decision.
//
// The recursive walks the three analyses run are **not** here: they are
// emitted by internal/graph at run time and therefore cannot go through
// sqlc, exactly as internal/views/compile.go's statements cannot. What
// is here is everything static.
// ListRouteStepsByRouteKey reads a route's steps in order, addressed by
// the route's key and this game's id.
//
// entity_id is nullable: 0013_analysis.sql tombstones a step whose
// entity was deleted with ON DELETE SET NULL rather than removing it, so
// a route visibly keeps a step it can no longer resolve. A caller must
// have an opinion about the null; analysis.routeSeeds contributes no
// seed for one and still names it in the seed report.
func (q *Queries) ListRouteStepsByRouteKey(ctx context.Context, arg ListRouteStepsByRouteKeyParams) ([]ListRouteStepsByRouteKeyRow, error) {
	rows, err := q.db.Query(ctx, listRouteStepsByRouteKey, arg.ProjectID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteStepsByRouteKeyRow
	for rows.Next() {
		var i ListRouteStepsByRouteKeyRow
		if err := rows.Scan(
			&i.Position,
			&i.EntityID,
			&i.EntityTypeKey,
			&i.EntityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesPage = `-- name: ListRoutesPage :many
SELECT r.id, r.key, r.name, r.description, r.version, r.updated_at,
       r.last_checked_at, r.last_checked_design_version,
       (SELECT count(*) FROM route_steps s
         WHERE s.project_id = r.project_id AND s.route_id = r.id)::bigint AS step_count
FROM routes r
WHERE r.project_id = $1::uuid
  AND ($2::uuid IS NULL
       OR (r.name, r.id) > ($3::text, $2::uuid))
ORDER BY r.name, r.id
LIMIT $4::int
`

type ListRoutesPageParams struct {
	ProjectID uuid.UUID
	AfterID   *uuid.UUID
	AfterName *string
	Limit     int32
}

type ListRoutesPageRow struct {
	ID                       uuid.UUID
	Key                      string
	Name                     string
	Description              string
	Version                  int32
	UpdatedAt                pgtype.Timestamptz
	LastCheckedAt            pgtype.Timestamptz
	LastCheckedDesignVersion *int64
	StepCount                int64
}

// One page of a game's routes, keyed on (name, id), which is exactly
// routes_project_idx.
//
// **No step lists and no stored verdicts**, mirroring ListViewsPage's
// discipline about not shipping query documents in a listing: a listing
// says what exists and how healthy it is, and routes.get is where a walk
// and its proof come from. What is here instead is the step *count* and
// the two columns a caller needs to decide the three-state status --
// never checked, stale, checked -- which is a fixed amount of data per
// row however long the route is.
//
// The keyset compares uuid to uuid and carries `id` in the ORDER BY as
// well as in the comparison, for the reasons ListEntitiesPage sets out:
// route names are as duplicable as entity names, and a keyset whose
// comparison disagrees with its sort order skips or repeats rows at a
// page boundary and says nothing.
func (q *Queries) ListRoutesPage(ctx context.Context, arg ListRoutesPageParams) ([]ListRoutesPageRow, error) {
	rows, err := q.db.Query(ctx, listRoutesPage,
		arg.ProjectID,
		arg.AfterID,
		arg.AfterName,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesPageRow
	for rows.Next() {
		var i ListRoutesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.UpdatedAt,
			&i.LastCheckedAt,
			&i.LastCheckedDesignVersion,
			&i.StepCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeExists = `-- name: RouteExists :one
SELECT EXISTS (
    SELECT 1 FROM routes WHERE project_id = $1 AND lower(key) = lower($2)
) AS route_exists
`

type RouteExistsParams struct {
	ProjectID uuid.UUID
	Key       string
}

// RouteExists separates "no such route" from "a route with no steps",
// which ListRouteStepsByRouteKey answers identically and which are two
// different refusals.
func (q *Queries) RouteExists(ctx context.Context, arg RouteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, routeExists, arg.ProjectID, arg.Key)
	var route_exists bool
	err := row.Scan(&route_exists)
	return route_exists, err
}

const upsertRoute = `-- name: UpsertRoute :one

INSERT INTO routes (project_id, key, name, description, params,
                    updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::jsonb,
        $6::uuid, $7::uuid)
ON CONFLICT (project_id, lower(key)) DO UPDATE
SET name                = excluded.name,
    description         = excluded.description,
    params              = excluded.params,
    version             = routes.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE routes.version = $8::integer
RETURNING id, project_id, key, name, description, params, version, last_checked_at, last_checked_design_version, last_check, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertRouteParams struct {
	ProjectID        uuid.UUID
	Key              string
	Name             string
	Description      string
	Params           []byte
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// The route CRUD. Every statement filters on the resolved project id,
// and the two that address one row by key fold the key, because every
// key in Maestro is matched without regard to case.
// The compare-and-set, in one statement, exactly as UpsertView and
// UpsertEntityType do it; those statements carry the full argument and
// it is not restated. In short: the DO UPDATE is guarded by the caller's
// expected version, so two writers cannot both read version 1 and both
// succeed, and a guard that matches nothing returns no row rather than
// an error, which Go turns into the typed conflict.
//
// **key is not in the SET list**, for UpsertEntityType's reason: the
// first spelling stored stands, so a re-seed cannot rewrite the handle a
// designer bookmarks, and the returned row still carries the stored
// spelling.
//
// **The three verdict columns are not in the SET list either, and that
// is the decision this table exists for.** last_check, last_checked_at
// and last_checked_design_version are written by routes.check alone. An
// edit to a route's name must not silently discard a verdict somebody
// proved, and a caller that said nothing about a check would be saying
// "never checked" if they were listed here.
func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, upsertRoute,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Params,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Params,
		&i.Version,
		&i.LastCheckedAt,
		&i.LastCheckedDesignVersion,
		&i.LastCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const writeRouteCheck = `-- name: WriteRouteCheck :one
UPDATE routes
SET last_check                  = $1::jsonb,
    last_checked_at             = now(),
    last_checked_design_version = $2::bigint
WHERE project_id = $3::uuid AND id = $4::uuid
RETURNING last_checked_at, last_checked_design_version
`

type WriteRouteCheckParams struct {
	LastCheck     []byte
	DesignVersion int64
	ProjectID     uuid.UUID
	ID            uuid.UUID
}

type WriteRouteCheckRow struct {
	LastCheckedAt            pgtype.Timestamptz
	LastCheckedDesignVersion *int64
}

// WriteRouteCheck stores the one thing this sub-project caches.
//
// **The design version is a parameter and not a subselect.** Reading
// `projects.design_version` here would read it at the end of the check,
// so a metamodel write that committed while the walk was running would
// be counted as a design this verdict had seen -- and the route would
// read `checked` against content it never looked at. The value bound
// here is the one check.go read **before** the walk began, which makes a
// mid-check write leave the route `stale` rather than freshly green.
// TestAWriteDuringACheckLeavesTheRouteStaleRatherThanFreshlyGreen is
// that assertion.
//
// **version is not in the SET list.** A check is not an edit of the
// route: the steps and the parameters a caller holds are still current
// afterwards, and bumping the version would turn every check into a
// version_conflict for the next writer. routes_set_updated_at does fire,
// which is why last_checked_at is written from the same now() -- see
// routeStatus, which compares the two.
func (q *Queries) WriteRouteCheck(ctx context.Context, arg WriteRouteCheckParams) (WriteRouteCheckRow, error) {
	row := q.db.QueryRow(ctx, writeRouteCheck,
		arg.LastCheck,
		arg.DesignVersion,
		arg.ProjectID,
		arg.ID,
	)
	var i WriteRouteCheckRow
	err := row.Scan(&i.LastCheckedAt, &i.LastCheckedDesignVersion)
	return i, err
}
