// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments
WHERE id = $1::uuid AND project_id = $2::uuid
RETURNING id
`

type DeleteCommentParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

// Append-only means there is no update; a note written against the wrong
// thing is still worse than a gap, so it can go.
func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteComment, arg.ID, arg.ProjectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertComment = `-- name: InsertComment :one

WITH written AS (
    INSERT INTO comments (project_id, entity_id, relation_id, entity_type_id, relation_type_id,
                          body, created_by_user_id, created_by_token_id)
    VALUES ($1::uuid,
            $2::uuid,
            $3::uuid,
            $4::uuid,
            $5::uuid,
            $6::text,
            $7::uuid,
            $8::uuid)
    RETURNING id, project_id, entity_id, relation_id, entity_type_id, relation_type_id, body, created_at, created_by_user_id, created_by_token_id
)
SELECT w.id, w.project_id, w.entity_id, w.relation_id, w.entity_type_id, w.relation_type_id, w.body, w.created_at, w.created_by_user_id, w.created_by_token_id, COALESCE(t.label, u.display_name, '')::text AS author,
       COALESCE(owner.display_name, u.display_name, '')::text AS author_of
FROM written w
LEFT JOIN users u ON u.id = w.created_by_user_id
LEFT JOIN api_tokens t ON t.id = w.created_by_token_id
LEFT JOIN users owner ON owner.id = t.user_id
`

type InsertCommentParams struct {
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
}

type InsertCommentRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	Author           string
	AuthorOf         string
}

// The log beside a game's content. Every statement carries the resolved
// project id, and which of them are load-bearing is stated rather than
// implied:
//
//   - **DeleteComment's is.** A comment id is a value a previous answer
//     handed back and names no parent, so nothing but this filter keeps
//     a removal inside one game. Mutating it reddens TestCommentsArea's
//     "one game's log is not another's" case.
//
// **The author comes back as three facts, not one.** `author` is what to
// print, `author_of` is the person a token traces back to, and which of
// the two audit columns is set says whether a person or an agent wrote
// it: a reader who cannot tell a machine from a colleague is reading a
// log that is lying to them by omission, and the token label alone
// ("rl-aeternum") reads as a name.
//
//   - **The listings' are defence in depth.** A listing is reached by a
//     target the caller addressed by key, and resolving that address is
//     already scoped to the game; the composite foreign keys mean a
//     comment cannot name a row of another game in the first place. The
//     filters stay because a read of this table should not depend on
//     somebody remembering that two other mechanisms already did the
//     work, and no test can tell them apart -- which is this comment's
//     reason for existing.
//
// The four target columns are a CHECK-constrained choice of one
// (0017_comments.sql), so a listing filters on the one that is set and
// the three nulls never match anything.
// **The author comes back with the row**, from the same join every read
// here makes: a log whose entries do not say who wrote them is half a
// log, and the two kinds of author this product has are a person with a
// display name and an agent with a token's label.
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (InsertCommentRow, error) {
	row := q.db.QueryRow(ctx, insertComment,
		arg.ProjectID,
		arg.EntityID,
		arg.RelationID,
		arg.EntityTypeID,
		arg.RelationTypeID,
		arg.Body,
		arg.CreatedByUserID,
		arg.CreatedByTokenID,
	)
	var i InsertCommentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityID,
		&i.RelationID,
		&i.EntityTypeID,
		&i.RelationTypeID,
		&i.Body,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.Author,
		&i.AuthorOf,
	)
	return i, err
}

const listCommentCountsForEntities = `-- name: ListCommentCountsForEntities :many
SELECT entity_id, count(*)::bigint AS comments
FROM comments
WHERE project_id = $1::uuid AND entity_id = ANY ($2::uuid[])
GROUP BY entity_id
`

type ListCommentCountsForEntitiesParams struct {
	ProjectID uuid.UUID
	EntityIds []uuid.UUID
}

type ListCommentCountsForEntitiesRow struct {
	EntityID *uuid.UUID
	Comments int64
}

// How many comments each of these entities carries, for a listing that
// wants to say which rows have been thought about without reading the
// log of every one of them.
func (q *Queries) ListCommentCountsForEntities(ctx context.Context, arg ListCommentCountsForEntitiesParams) ([]ListCommentCountsForEntitiesRow, error) {
	rows, err := q.db.Query(ctx, listCommentCountsForEntities, arg.ProjectID, arg.EntityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentCountsForEntitiesRow
	for rows.Next() {
		var i ListCommentCountsForEntitiesRow
		if err := rows.Scan(&i.EntityID, &i.Comments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsInProject = `-- name: ListCommentsInProject :many
SELECT c.id, c.project_id, c.entity_id, c.relation_id, c.entity_type_id, c.relation_type_id, c.body, c.created_at, c.created_by_user_id, c.created_by_token_id, COALESCE(t.label, u.display_name, '')::text AS author,
       COALESCE(owner.display_name, u.display_name, '')::text AS author_of
FROM comments c
LEFT JOIN users u ON u.id = c.created_by_user_id
LEFT JOIN api_tokens t ON t.id = c.created_by_token_id
LEFT JOIN users owner ON owner.id = t.user_id
WHERE c.project_id = $1::uuid
ORDER BY c.created_at DESC, c.id DESC
LIMIT $2::integer
`

type ListCommentsInProjectParams struct {
	ProjectID uuid.UUID
	Lim       int32
}

type ListCommentsInProjectRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	Author           string
	AuthorOf         string
}

// The game's whole log: what has been thought about this game lately,
// whatever it was about.
func (q *Queries) ListCommentsInProject(ctx context.Context, arg ListCommentsInProjectParams) ([]ListCommentsInProjectRow, error) {
	rows, err := q.db.Query(ctx, listCommentsInProject, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsInProjectRow
	for rows.Next() {
		var i ListCommentsInProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.RelationID,
			&i.EntityTypeID,
			&i.RelationTypeID,
			&i.Body,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.CreatedByTokenID,
			&i.Author,
			&i.AuthorOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsOnEntity = `-- name: ListCommentsOnEntity :many
SELECT c.id, c.project_id, c.entity_id, c.relation_id, c.entity_type_id, c.relation_type_id, c.body, c.created_at, c.created_by_user_id, c.created_by_token_id, COALESCE(t.label, u.display_name, '')::text AS author,
       COALESCE(owner.display_name, u.display_name, '')::text AS author_of
FROM comments c
LEFT JOIN users u ON u.id = c.created_by_user_id
LEFT JOIN api_tokens t ON t.id = c.created_by_token_id
LEFT JOIN users owner ON owner.id = t.user_id
WHERE c.project_id = $1::uuid AND c.entity_id = $2::uuid
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3::integer
`

type ListCommentsOnEntityParams struct {
	ProjectID uuid.UUID
	EntityID  uuid.UUID
	Lim       int32
}

type ListCommentsOnEntityRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	Author           string
	AuthorOf         string
}

// Newest first, which is how a log is read, and one page at a time.
func (q *Queries) ListCommentsOnEntity(ctx context.Context, arg ListCommentsOnEntityParams) ([]ListCommentsOnEntityRow, error) {
	rows, err := q.db.Query(ctx, listCommentsOnEntity, arg.ProjectID, arg.EntityID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsOnEntityRow
	for rows.Next() {
		var i ListCommentsOnEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.RelationID,
			&i.EntityTypeID,
			&i.RelationTypeID,
			&i.Body,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.CreatedByTokenID,
			&i.Author,
			&i.AuthorOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsOnEntityType = `-- name: ListCommentsOnEntityType :many
SELECT c.id, c.project_id, c.entity_id, c.relation_id, c.entity_type_id, c.relation_type_id, c.body, c.created_at, c.created_by_user_id, c.created_by_token_id, COALESCE(t.label, u.display_name, '')::text AS author,
       COALESCE(owner.display_name, u.display_name, '')::text AS author_of
FROM comments c
LEFT JOIN users u ON u.id = c.created_by_user_id
LEFT JOIN api_tokens t ON t.id = c.created_by_token_id
LEFT JOIN users owner ON owner.id = t.user_id
WHERE c.project_id = $1::uuid AND c.entity_type_id = $2::uuid
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3::integer
`

type ListCommentsOnEntityTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Lim          int32
}

type ListCommentsOnEntityTypeRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	Author           string
	AuthorOf         string
}

func (q *Queries) ListCommentsOnEntityType(ctx context.Context, arg ListCommentsOnEntityTypeParams) ([]ListCommentsOnEntityTypeRow, error) {
	rows, err := q.db.Query(ctx, listCommentsOnEntityType, arg.ProjectID, arg.EntityTypeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsOnEntityTypeRow
	for rows.Next() {
		var i ListCommentsOnEntityTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.RelationID,
			&i.EntityTypeID,
			&i.RelationTypeID,
			&i.Body,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.CreatedByTokenID,
			&i.Author,
			&i.AuthorOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsOnRelation = `-- name: ListCommentsOnRelation :many
SELECT c.id, c.project_id, c.entity_id, c.relation_id, c.entity_type_id, c.relation_type_id, c.body, c.created_at, c.created_by_user_id, c.created_by_token_id, COALESCE(t.label, u.display_name, '')::text AS author,
       COALESCE(owner.display_name, u.display_name, '')::text AS author_of
FROM comments c
LEFT JOIN users u ON u.id = c.created_by_user_id
LEFT JOIN api_tokens t ON t.id = c.created_by_token_id
LEFT JOIN users owner ON owner.id = t.user_id
WHERE c.project_id = $1::uuid AND c.relation_id = $2::uuid
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3::integer
`

type ListCommentsOnRelationParams struct {
	ProjectID  uuid.UUID
	RelationID uuid.UUID
	Lim        int32
}

type ListCommentsOnRelationRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	Author           string
	AuthorOf         string
}

func (q *Queries) ListCommentsOnRelation(ctx context.Context, arg ListCommentsOnRelationParams) ([]ListCommentsOnRelationRow, error) {
	rows, err := q.db.Query(ctx, listCommentsOnRelation, arg.ProjectID, arg.RelationID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsOnRelationRow
	for rows.Next() {
		var i ListCommentsOnRelationRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.RelationID,
			&i.EntityTypeID,
			&i.RelationTypeID,
			&i.Body,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.CreatedByTokenID,
			&i.Author,
			&i.AuthorOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsOnRelationType = `-- name: ListCommentsOnRelationType :many
SELECT c.id, c.project_id, c.entity_id, c.relation_id, c.entity_type_id, c.relation_type_id, c.body, c.created_at, c.created_by_user_id, c.created_by_token_id, COALESCE(t.label, u.display_name, '')::text AS author,
       COALESCE(owner.display_name, u.display_name, '')::text AS author_of
FROM comments c
LEFT JOIN users u ON u.id = c.created_by_user_id
LEFT JOIN api_tokens t ON t.id = c.created_by_token_id
LEFT JOIN users owner ON owner.id = t.user_id
WHERE c.project_id = $1::uuid AND c.relation_type_id = $2::uuid
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3::integer
`

type ListCommentsOnRelationTypeParams struct {
	ProjectID      uuid.UUID
	RelationTypeID uuid.UUID
	Lim            int32
}

type ListCommentsOnRelationTypeRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityID         *uuid.UUID
	RelationID       *uuid.UUID
	EntityTypeID     *uuid.UUID
	RelationTypeID   *uuid.UUID
	Body             string
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	Author           string
	AuthorOf         string
}

func (q *Queries) ListCommentsOnRelationType(ctx context.Context, arg ListCommentsOnRelationTypeParams) ([]ListCommentsOnRelationTypeRow, error) {
	rows, err := q.db.Query(ctx, listCommentsOnRelationType, arg.ProjectID, arg.RelationTypeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsOnRelationTypeRow
	for rows.Next() {
		var i ListCommentsOnRelationTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.RelationID,
			&i.EntityTypeID,
			&i.RelationTypeID,
			&i.Body,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.CreatedByTokenID,
			&i.Author,
			&i.AuthorOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
