// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocumentLink = `-- name: DeleteDocumentLink :execrows
DELETE FROM document_links
WHERE project_id = $1::uuid
  AND document_id = $2::uuid
  AND entity_id = $3::uuid
`

type DeleteDocumentLinkParams struct {
	ProjectID  uuid.UUID
	DocumentID uuid.UUID
	EntityID   uuid.UUID
}

// The row count is what tells LinkRemove that there was nothing to
// detach, which it reports as not_found rather than as silence
// (TestRemovingALinkLeavesTheDocumentAndTheEntity).
func (q *Queries) DeleteDocumentLink(ctx context.Context, arg DeleteDocumentLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocumentLink, arg.ProjectID, arg.DocumentID, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDocumentLinksExcept = `-- name: DeleteDocumentLinksExcept :exec
DELETE FROM document_links
WHERE project_id = $1::uuid
  AND document_id = $2::uuid
  AND NOT (entity_id = ANY($3::uuid[]))
`

type DeleteDocumentLinksExceptParams struct {
	ProjectID  uuid.UUID
	DocumentID uuid.UUID
	Keep       []uuid.UUID
}

// The other half of a replacing write. An empty keep list detaches
// everything, which is exactly what `links: []` means -- and the caller
// must pass an empty array rather than a nil one, because pgx encodes
// nil as SQL NULL and `NOT (x = ANY(NULL))` is NULL, which deletes
// nothing. markdown.replaceLinks says so where the slice is built.
func (q *Queries) DeleteDocumentLinksExcept(ctx context.Context, arg DeleteDocumentLinksExceptParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentLinksExcept, arg.ProjectID, arg.DocumentID, arg.Keep)
	return err
}

const getDocumentByPath = `-- name: GetDocumentByPath :one
SELECT id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id FROM documents
WHERE project_id = $1::uuid
  AND lower(path) = lower($2::text)
  AND ($3::bool OR deleted_at IS NULL)
`

type GetDocumentByPathParams struct {
	ProjectID      uuid.UUID
	Path           string
	IncludeDeleted bool
}

// The read path. A soft-deleted document is not found unless the caller
// asked for it: deletion is soft so nothing is lost, not so that every
// reader has to filter. Both arms are exercised: the filtering one by
// TestDeletingADocumentHidesItFromReadsAndKeepsItsHistory, through
// Read, and the include_deleted one by deleteRefusal and
// conflictAfterFailedUpsert, which have to re-read a row that may be
// deleted in order to say why a write or a delete was refused --
// deleteRefusal's arm by TestDeletingTwiceIsNotFoundRatherThanASecond
// Tombstone, and conflictAfterFailedUpsert's by
// TestACreationRacingACreateAndDeleteIsToldTheTombstone.
func (q *Queries) GetDocumentByPath(ctx context.Context, arg GetDocumentByPathParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByPath, arg.ProjectID, arg.Path, arg.IncludeDeleted)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getDocumentByPathForUpdate = `-- name: GetDocumentByPathForUpdate :one
SELECT id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id FROM documents
WHERE project_id = $1::uuid
  AND lower(path) = lower($2::text)
FOR UPDATE
`

type GetDocumentByPathForUpdateParams struct {
	ProjectID uuid.UUID
	Path      string
}

// FOR UPDATE, and deliberately with no deleted_at filter: a write to a
// deleted path resurrects it, so the writer must see the row it is about
// to bring back, and must hold it.
//
// **What the lock buys, measured rather than asserted.** It does not buy
// the refusal: the guarded DO UPDATE refuses on its own, and dropping
// FOR UPDATE from this statement leaves the whole markdown suite green
// at -count=5. Nor does it buy the freshness of the number the loser is
// told to merge onto -- without the lock the read sees a stale version,
// passes the Go check, and the guarded upsert then refuses and
// conflictAfterFailedUpsert re-reads, arriving at the same fresh answer
// by a longer route. TestTheReportedCurrentVersionIsTheOneTheWriteWould
// HaveMet pins that answer, and it passes either way; it pins the
// guarantee, not this clause.
//
// What the lock does buy is the shape of the refusal rather than its
// existence: a conflicting writer is turned away before its body, its
// frontmatter and its version row are written and rolled back, and the
// pre-write spelling check in writeWith runs against a row no other
// transaction can move under it. It also serialises this write against a
// concurrent *delete* of the same row: without the lock, a hard delete
// landing between this read and the upsert would let the upsert's own
// INSERT arm fire on the freed path and silently re-create the document
// at version 1, rather than the writer being told the row is gone. All
// three are worth a row lock on a write that is already taking one.
// None is observable through this package's public surface, so no test
// here distinguishes them, and this comment says so rather than naming a
// test that would not go red. (The third case cannot fire until Task 4
// lands deletion, and deletion there is soft, so it is not reachable
// even then; a *hard* delete racing this read is not something Task 3
// or 4 need close, only something worth naming so a future hard-delete
// feature does not skip it. Task 4 landed and deletion there is soft, as
// predicted: SoftDeleteDocument is an UPDATE, so it takes this same row
// lock and the two serialise on it, and the resurrection the upsert then
// performs is the documented behaviour rather than a silent
// re-creation.)
func (q *Queries) GetDocumentByPathForUpdate(ctx context.Context, arg GetDocumentByPathForUpdateParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByPathForUpdate, arg.ProjectID, arg.Path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, project_id, document_id, version, title, summary, body_md, frontmatter, message, deleted, author_user_id, author_token_id, created_at FROM document_versions
WHERE project_id = $1::uuid
  AND document_id = $2::uuid
  AND version = $3::integer
`

type GetDocumentVersionParams struct {
	ProjectID  uuid.UUID
	DocumentID uuid.UUID
	Version    int32
}

// The other call the file header names. Same rule: filtered by
// project_id and document_id, never by version alone and never by a
// join -- and the same caveat: no call markdown.ReadVersion offers can
// make this query's own project filter matter, for the reason above
// ListDocumentVersions. TestReadingAnotherGamesVersionIsNotFound is
// refused one join earlier, in markdown.documentForVersions.
func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.ProjectID, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.Message,
		&i.Deleted,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const getEntityIDByKey = `-- name: GetEntityIDByKey :one
SELECT id FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
  AND lower(key) = lower($3::text)
`

type GetEntityIDByKeyParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Key          string
}

// The second half of that resolution.
//
// **This query's own project filter separates nothing markdown.resolveEntity
// can reach, and that is stated rather than credited to a test that would
// not go red.** entity_type_id arrives already resolved inside the
// caller's own game (GetEntityTypeIDByKey filters on project_id), and
// 0004_metamodel.sql gives entities a composite key to entity_types
// carrying project_id, so an entity whose project_id disagrees with its
// type's is unrepresentable. Verified by mutation: neutralising this
// filter behind a no-op `OR TRUE` leaves the package green, including
// TestALinkToAnEntityFromAnotherGamesTypeOfTheSameNameIsRefusedAtTheKey,
// which is refused by the entity_type_id filter instead. The filter
// stays for the same reason ListDocumentVersions' does -- a future
// caller that obtains a type id some other way, which Task 11's REST
// mirror may be -- and because the file header's rule is that isolation
// is in SQL and not in whoever remembers to resolve first.
// What the test above does pin is the *answer*: a caller naming another
// game's entity under a type key both games declare is refused at
// entity_key, not at entity_type and not with somebody else's row.
func (q *Queries) GetEntityIDByKey(ctx context.Context, arg GetEntityIDByKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEntityIDByKey, arg.ProjectID, arg.EntityTypeID, arg.Key)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEntityTypeIDByKey = `-- name: GetEntityTypeIDByKey :one
SELECT id FROM entity_types
WHERE project_id = $1::uuid
  AND lower(key) = lower($2::text)
`

type GetEntityTypeIDByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

// Link endpoints are resolved here rather than through
// internal/metamodel's own EntityByKey, in two steps rather than one
// join, for a reason that is about the *answer* and not about coupling:
// a caller that typed "quesst" and a caller that typed "wanted-hoggerr"
// have made two different mistakes at two different arguments, and one
// flat "not found" makes an agent guess which. Two lookups let the
// refusal name entity_type or entity_key, which is the discrimination
// the spec wanted a whole extra wire code for.
// TestAMistypedEntityTypeAndAMistypedEntityKeyAreToldApart pins that the
// two misses are told apart, and the project filter here is what refuses
// an entity type another game declared
// (TestALinkToAnEntityInAnotherGameIsRefused).
func (q *Queries) GetEntityTypeIDByKey(ctx context.Context, arg GetEntityTypeIDByKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEntityTypeIDByKey, arg.ProjectID, arg.Key)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :one
INSERT INTO document_versions (project_id, document_id, version, title, summary, body_md,
                               frontmatter, message, deleted, author_user_id, author_token_id)
VALUES ($1::uuid, $2::uuid,
        $3::integer, $4::text, $5::text,
        $6::text, $7::jsonb, $8::text,
        $9::boolean,
        $10::uuid, $11::uuid)
RETURNING id, project_id, document_id, version, title, summary, body_md, frontmatter, message, deleted, author_user_id, author_token_id, created_at
`

type InsertDocumentVersionParams struct {
	ProjectID     uuid.UUID
	DocumentID    uuid.UUID
	Version       int32
	Title         string
	Summary       string
	BodyMd        string
	Frontmatter   []byte
	Message       string
	Deleted       bool
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
}

// The snapshot. Full bodies, never diffs (spec §3): a thousand versions
// of a long script is a few megabytes, which is nothing beside a diff
// chain that must be replayed to answer "show me version 12" and that
// corrupts every later version if one link is wrong.
//
// project_id is written from the caller's own resolved id, in the same
// transaction as the document write, and 0007_documents.sql's composite
// key is what keeps it honest: a version row whose project_id disagrees
// with its document's cannot be inserted at all
// (documents_schema_test.go pins that refusal).
//
// deleted is a required argument rather than a column left to its
// DEFAULT false, and that is deliberate: Delete's tombstone is the one
// caller that passes true, and every other caller has to say false out
// loud. A defaulted column would let a future snapshot-writing path
// forget the question and store a live version where a tombstone
// belonged, silently; a required argument turns the same omission into
// a compile error. TestDeletingADocumentHidesItFromReadsAndKeepsIts
// History reads the true case back and Task 3's
// TestTheFirstWriteAlsoWritesVersionOneWithItsAuthorAndMessage the
// false one.
func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, insertDocumentVersion,
		arg.ProjectID,
		arg.DocumentID,
		arg.Version,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.Frontmatter,
		arg.Message,
		arg.Deleted,
		arg.AuthorUserID,
		arg.AuthorTokenID,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.Message,
		&i.Deleted,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentLinksByDocument = `-- name: ListDocumentLinksByDocument :many
SELECT l.role, t.key AS entity_type_key, e.key AS entity_key,
       e.name AS entity_name, e.id AS entity_id
FROM document_links l
JOIN entities e ON e.id = l.entity_id AND e.project_id = l.project_id
JOIN entity_types t ON t.id = e.entity_type_id AND t.project_id = e.project_id
WHERE l.project_id = $1::uuid
  AND l.document_id = $2::uuid
ORDER BY t.key, e.key, e.id
`

type ListDocumentLinksByDocumentParams struct {
	ProjectID  uuid.UUID
	DocumentID uuid.UUID
}

type ListDocumentLinksByDocumentRow struct {
	Role          string
	EntityTypeKey string
	EntityKey     string
	EntityName    string
	EntityID      uuid.UUID
}

// Ordered by the entity's type key then its key then its id: none of the
// first two is unique on its own, and an order that can tie reshuffles
// its ties between two identical calls.
//
// The project filter here separates nothing that markdown.LinksByDocument
// can reach, and this is stated rather than credited to a test that
// would not go red: the document id only ever arrives already resolved
// inside the caller's own game (markdown.documentForLinks), and
// 0007_documents.sql's composite keys make a link row whose project_id
// disagrees with its document's unrepresentable. It stays for the same
// reason ListDocumentVersions' does -- a caller that does not resolve
// first, which Task 11's REST mirror may be. What is pinned is the
// document_id filter: TestALinkIsAddressedByItsOwnDocument uses two
// documents in one game, where the project filter separates nothing.
func (q *Queries) ListDocumentLinksByDocument(ctx context.Context, arg ListDocumentLinksByDocumentParams) ([]ListDocumentLinksByDocumentRow, error) {
	rows, err := q.db.Query(ctx, listDocumentLinksByDocument, arg.ProjectID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentLinksByDocumentRow
	for rows.Next() {
		var i ListDocumentLinksByDocumentRow
		if err := rows.Scan(
			&i.Role,
			&i.EntityTypeKey,
			&i.EntityKey,
			&i.EntityName,
			&i.EntityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentLinksByEntity = `-- name: ListDocumentLinksByEntity :many
SELECT l.role, d.id AS document_id, d.path, d.title, d.kind
FROM document_links l
JOIN documents d ON d.id = l.document_id AND d.project_id = l.project_id
WHERE l.project_id = $1::uuid
  AND l.entity_id = $2::uuid
  AND d.deleted_at IS NULL
ORDER BY d.path, d.id
`

type ListDocumentLinksByEntityParams struct {
	ProjectID uuid.UUID
	EntityID  uuid.UUID
}

type ListDocumentLinksByEntityRow struct {
	Role       string
	DocumentID uuid.UUID
	Path       string
	Title      string
	Kind       string
}

// The reverse direction, which is how the UI builds an entity page and
// how an agent asked to rewrite the Hogger dialogue finds the document
// from the quest instead of guessing a path.
//
// Soft-deleted documents are excluded: an entity page listing a document
// nobody can read would be a dead link on every quest it was attached
// to. TestAnEntityStopsListingADocumentThatWasDeleted pins it, and pins
// the other half of the same rule in its second act: nothing cascades on
// a soft delete, so the link row survives and comes back with its role
// when the document is written to again.
func (q *Queries) ListDocumentLinksByEntity(ctx context.Context, arg ListDocumentLinksByEntityParams) ([]ListDocumentLinksByEntityRow, error) {
	rows, err := q.db.Query(ctx, listDocumentLinksByEntity, arg.ProjectID, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentLinksByEntityRow
	for rows.Next() {
		var i ListDocumentLinksByEntityRow
		if err := rows.Scan(
			&i.Role,
			&i.DocumentID,
			&i.Path,
			&i.Title,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, project_id, document_id, version, title, summary, message, deleted,
       author_user_id, author_token_id, created_at
FROM document_versions
WHERE project_id = $1::uuid
  AND document_id = $2::uuid
  AND ($3::integer IS NULL
       OR version < $3::integer)
ORDER BY version DESC
LIMIT $4::int
`

type ListDocumentVersionsParams struct {
	ProjectID    uuid.UUID
	DocumentID   uuid.UUID
	AfterVersion *int32
	Limit        int32
}

type ListDocumentVersionsRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	DocumentID    uuid.UUID
	Version       int32
	Title         string
	Summary       string
	Message       string
	Deleted       bool
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

// Version metadata only, newest first. **No bodies**: prose is the
// largest payload in the system and agents are its main consumer, so a
// history that carried them would blow a context window on the first
// call against a document anyone has actually worked on (spec §7).
// TestHistoryIsNewestFirstAndCarriesNoBodies pins the order and the
// absence, the latter by reading the returned row type's own fields.
//
// Keyset by version alone, which is unique within a document
// (document_versions_key), so there is no tiebreak to add and the page
// is an index scan. This is one of the two calls the file header names
// as being one forgotten join away from serving another game's prose,
// and it deliberately does not reach the parent document at all -- but
// no call markdown.History offers can make this query's own project
// filter matter (see markdown.documentForVersions): the document id
// only ever reaches here already resolved inside the caller's own game,
// and 0007_documents.sql's composite key makes a version row whose
// project_id disagrees with its document's unrepresentable
// (TestAVersionRowCannotClaimAGameItsDocumentDoesNotBelongTo forces
// that refusal). What the project filter separates nothing for is
// covered instead by TestAVersionIsAddressedByItsOwnDocument, the
// document_id filter, and TestTwoGamesSharingOnePathKeepSeparateHistories
// pins that a version row carries its own document's project id in the
// first place.
func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions,
		arg.ProjectID,
		arg.DocumentID,
		arg.AfterVersion,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentVersionsRow
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DocumentID,
			&i.Version,
			&i.Title,
			&i.Summary,
			&i.Message,
			&i.Deleted,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsPage = `-- name: ListDocumentsPage :many
SELECT d.id, d.project_id, d.path, d.kind, d.title, d.summary, d.current_version,
       d.deleted_at, d.created_at, d.updated_at,
       d.created_by_user_id, d.created_by_token_id,
       d.updated_by_user_id, d.updated_by_token_id
FROM documents d
WHERE d.project_id = $1::uuid
  AND ($2::bool OR d.deleted_at IS NULL)
  AND ($3::text IS NULL
       OR starts_with(lower(d.path), lower($3::text)))
  AND ($4::text IS NULL OR lower(d.kind) = lower($4::text))
  AND ($5::uuid IS NULL
       OR EXISTS (SELECT 1 FROM document_links l
                   WHERE l.project_id = d.project_id
                     AND l.document_id = d.id
                     AND l.entity_id = $5::uuid))
  AND ($6::uuid IS NULL
       OR (d.path, d.id) > ($7::text, $6::uuid))
ORDER BY d.path, d.id
LIMIT $8::int
`

type ListDocumentsPageParams struct {
	ProjectID      uuid.UUID
	IncludeDeleted bool
	PathPrefix     *string
	Kind           *string
	EntityID       *uuid.UUID
	AfterID        *uuid.UUID
	AfterPath      *string
	Limit          int32
}

type ListDocumentsPageRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Path             string
	Kind             string
	Title            string
	Summary          string
	CurrentVersion   int32
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

// One page of a game's documents, keyset-ordered by (path, id).
//
// **No body_md and no frontmatter in the select list.** They are the two
// largest columns in the schema and a listing never needs either; a
// SELECT * here would quietly put a megabyte of prose per row on a page
// of fifty. markdown.DocumentSummary carries no field for either, which
// is what makes the rule a fact about the type rather than a promise
// about this select list (TestAListingRowCarriesNoBodyAtAll).
//
// **starts_with, not LIKE, and this is a correctness choice rather than
// a style one.** A path may legally contain `_`, which is LIKE's
// single-character wildcard, so `path_prefix: "lore_x"` under LIKE would
// also match `loreax` -- a filter silently answering a question the
// caller did not ask, which is the class of defect this whole read
// surface is most exposed to. Escaping it correctly is possible and is
// one forgotten backslash away from the same bug.
// TestAPathPrefixFilterDoesNotTreatUnderscoreAsAWildcard pins it. The
// cost is that starts_with cannot use documents_listing_idx for the
// prefix, so a prefixed listing scans the game's documents; a game has
// hundreds of documents, not millions, and the ordering half of the
// index still applies.
//
// The prefix and the kind are folded, like every other path comparison
// in this file, so `Lore/` and `lore/` name the same subtree and
// `SCRIPT` and `script` name the same shelf
// (TestAListingFiltersByKindAndByEntity).
//
// The entity filter is an EXISTS rather than a join, so a document
// attached to one entity appears once and the page's row count is the
// number of documents rather than the number of links.
// TestADocumentAttachedToTwoEntitiesAppearsOnceInAFilteredListing pins
// that, with a document attached to two entities of which one is
// filtered on; a JOIN would answer with the same row twice.
//
// **`l.project_id = d.project_id` inside that EXISTS is defence in
// depth, not load-bearing, and no test here says otherwise.** The
// entity id the caller filters on is already resolved inside this
// game (List's own resolveEntity call), and document_links rows are
// themselves scoped to a project, so nothing in this game's page can
// reach another game's document through this clause even with it
// dropped; the suite stays green without it. It stays anyway, for the
// same reason 0007_documents.sql's comment gives for the version
// tables: a clause whose absence the suite cannot catch is exactly the
// one a later edit removes first, and this one costs nothing to keep.
//
// The project filter is load-bearing here, unlike the ones the header
// describes as defence in depth: a listing resolves nothing beforehand,
// so this filter is the only thing keeping one game's prose out of
// another's page. TestAListingNeverCrossesGames pins it.
func (q *Queries) ListDocumentsPage(ctx context.Context, arg ListDocumentsPageParams) ([]ListDocumentsPageRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsPage,
		arg.ProjectID,
		arg.IncludeDeleted,
		arg.PathPrefix,
		arg.Kind,
		arg.EntityID,
		arg.AfterID,
		arg.AfterPath,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsPageRow
	for rows.Next() {
		var i ListDocumentsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.Kind,
			&i.Title,
			&i.Summary,
			&i.CurrentVersion,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserID,
			&i.CreatedByTokenID,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksForDocuments = `-- name: ListLinksForDocuments :many
SELECT l.document_id, l.role, t.key AS entity_type_key,
       e.id AS entity_id, e.key AS entity_key, e.name AS entity_name
FROM document_links l
JOIN entities e ON e.id = l.entity_id AND e.project_id = l.project_id
JOIN entity_types t ON t.id = e.entity_type_id AND t.project_id = e.project_id
WHERE l.project_id = $1::uuid
  AND l.document_id = ANY($2::uuid[])
ORDER BY l.document_id, t.key, e.key, e.id
`

type ListLinksForDocumentsParams struct {
	ProjectID   uuid.UUID
	DocumentIds []uuid.UUID
}

type ListLinksForDocumentsRow struct {
	DocumentID    uuid.UUID
	Role          string
	EntityTypeKey string
	EntityID      uuid.UUID
	EntityKey     string
	EntityName    string
}

// The attachments of a whole page of documents, in one call rather than
// one per row. A search hit names its linked entities (spec §8) so a
// designer who found the script gets to the quest in one more click, and
// a query per hit would make a fifty-hit answer cost fifty-one round
// trips.
//
// The project filter is defence in depth here, exactly as
// ListDocumentLinksByDocument's is and stated for the same reason: the
// document ids only ever arrive as the ids SearchDocuments just returned
// for this game, and 0007_documents.sql's composite keys make a link row
// whose project_id disagrees with its document's unrepresentable, so the
// suite stays green without this clause. It stays because a clause whose
// absence no test can catch is the one a later edit removes first.
//
// Ordered by document, then the entity's type key, then its key: none of
// the first two is unique on its own, and an order that can tie
// reshuffles its ties between two identical calls.
func (q *Queries) ListLinksForDocuments(ctx context.Context, arg ListLinksForDocumentsParams) ([]ListLinksForDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listLinksForDocuments, arg.ProjectID, arg.DocumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksForDocumentsRow
	for rows.Next() {
		var i ListLinksForDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.Role,
			&i.EntityTypeKey,
			&i.EntityID,
			&i.EntityKey,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocuments = `-- name: SearchDocuments :many
SELECT d.id, d.path, d.title, d.summary, d.kind, d.current_version,
       ts_rank(d.search, plainto_tsquery('simple', $1::text)) AS rank,
       (ts_filter(d.search, '{a}')
         @@ plainto_tsquery('simple', $1::text))::bool AS name_match
FROM documents d
WHERE d.project_id = $2::uuid
  AND d.deleted_at IS NULL
  AND ($3::text = '' OR lower(d.kind) = lower($3::text))
  AND d.search @@ plainto_tsquery('simple', $1::text)
ORDER BY name_match DESC, rank DESC, d.title, d.id
LIMIT $4::int
`

type SearchDocumentsParams struct {
	Query     string
	ProjectID uuid.UUID
	Kind      string
	Limit     int32
}

type SearchDocumentsRow struct {
	ID             uuid.UUID
	Path           string
	Title          string
	Summary        string
	Kind           string
	CurrentVersion int32
	Rank           float32
	NameMatch      bool
}

// Full-text search over a game's documents, ranked, current versions
// only.
//
// **Only the current version is indexed** (spec §8). documents.search is
// a generated column on `documents`, and `document_versions` has no
// vector at all, so history is unreachable from here by construction.
// Searching it would multiply the index by the number of versions to
// answer a question that in practice is asked about one known document,
// where history plus diff answers it better.
// TestOnlyTheCurrentVersionIsSearchable pins it.
//
// The project filter is load-bearing, the way ListDocumentsPage's is and
// unlike the ones this file's other comments call defence in depth: the
// query text is the caller's and names no parent, and a search resolves
// nothing beforehand, so nothing but this clause keeps one game's prose
// out of another's answer. TestASearchNeverCrossesGames pins it.
//
// **name_match leads the ordering, and it is a guarantee rather than a
// tendency**, for the reason metamodel.Search's own comment works
// through at length: ts_rank saturates towards 1.0 as a lexeme repeats,
// so weights alone lose to sheer frequency on a multi-word query. Here
// the A-weighted half of the vector is the *title* and nothing else
// (0007_documents.sql builds it that way), so ts_filter(search, '{a}')
// @@ query asks exactly "does the title satisfy the query", and a
// document the query names outranks one that merely mentions the words
// in its body however often. ts_rank orders within each of the two
// groups, which is the work the A/B/C weights were introduced for.
// TestADocumentTheQueryNamesOutranksOneThatOnlyMentionsIt pins both
// halves: it is red without `name_match DESC` and red with the
// ts_filter replaced by the whole vector.
//
// The configuration is 'simple' on both sides of that expression and on
// the column itself, matching entities.search: the two indexes are
// merged into one ranked list in internal/web/mcp_search.go, and
// ts_rank values produced under different configurations are not
// comparable at all.
//
// Ties break by title then id, so two identical calls answer
// identically. Neither key is unique on its own.
//
// `kind` is a plain argument rather than a nullable one because the
// empty string is the only spelling of "no filter" this surface has —
// the same limitation ListDocumentsPage's `kind` records, since a
// document's kind is optional and ” is also a real stored value.
//
// Deleted documents are absent. A search result nobody can open is a
// worse answer than no answer.
// TestADeletedDocumentIsNotSearchable pins it.
func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments,
		arg.Query,
		arg.ProjectID,
		arg.Kind,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsRow
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.Summary,
			&i.Kind,
			&i.CurrentVersion,
			&i.Rank,
			&i.NameMatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :one
UPDATE documents
SET deleted_at          = now(),
    current_version     = current_version + 1,
    updated_by_user_id  = $1::uuid,
    updated_by_token_id = $2::uuid
WHERE project_id = $3::uuid
  AND lower(path) = lower($4::text)
  AND deleted_at IS NULL
  AND current_version = $5::integer
RETURNING id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id
`

type SoftDeleteDocumentParams struct {
	ActorUserID     *uuid.UUID
	ActorTokenID    *uuid.UUID
	ProjectID       uuid.UUID
	Path            string
	ExpectedVersion int32
}

// Guarded by the caller's expected version, exactly as UpsertDocument
// is, so a delete cannot race an edit: the loser matches no row and gets
// back no row, which Go turns into the typed conflict.
// TestDeletingWithAStaleVersionIsAConflict pins the guard and
// TestDeletingAnotherGamesDocumentIsNotFound the project filter.
//
// deleted_at IS NULL is part of the guard, so deleting a document twice
// is not_found on the second call rather than a second tombstone. That
// is the honest answer: the document is already gone, and the caller has
// nothing to do. TestDeletingTwiceIsNotFoundRatherThanASecondTombstone
// pins it.
//
// current_version advances here and the caller appends the matching
// tombstone version in the same transaction. The two are one change and
// withTx is what keeps them so; the count assertion in
// TestDeletingADocumentHidesItFromReadsAndKeepsItsHistory is what
// refuses to let them drift.
//
// There is no FOR UPDATE read before this statement, unlike the write
// path. It would buy nothing here: this UPDATE takes the row lock
// itself, and everything the write path reads under its lock -- the
// stored spelling, a body to echo on a conflict -- this call either does
// not need or reads afterwards, in deleteRefusal, once it already knows
// it was refused.
func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, softDeleteDocument,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.ProjectID,
		arg.Path,
		arg.ExpectedVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertDocument = `-- name: UpsertDocument :one

INSERT INTO documents (project_id, path, kind, title, summary, body_md, frontmatter,
                       current_version,
                       created_by_user_id, created_by_token_id,
                       updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text,
        COALESCE($3::text, ''),
        $4::text, $5::text, $6::text,
        $7::jsonb, 1,
        $8::uuid, $9::uuid,
        $8::uuid, $9::uuid)
ON CONFLICT (project_id, lower(path)) DO UPDATE
SET kind                = COALESCE($3::text, documents.kind),
    title               = excluded.title,
    summary             = excluded.summary,
    body_md             = excluded.body_md,
    frontmatter         = excluded.frontmatter,
    current_version     = documents.current_version + 1,
    deleted_at          = NULL,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE documents.current_version = $10::integer
RETURNING id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id
`

type UpsertDocumentParams struct {
	ProjectID       uuid.UUID
	Path            string
	Kind            *string
	Title           string
	Summary         string
	BodyMd          string
	Frontmatter     []byte
	ActorUserID     *uuid.UUID
	ActorTokenID    *uuid.UUID
	ExpectedVersion int32
}

// Every statement in this file carries the resolved project id: the
// reads as a filter, the writes as the column they set. Isolation
// between games is enforced in SQL, not in Go, so a query trusting a
// path or an id alone would hand a caller another game's prose the
// moment one leaked.
//
// Which filters are load-bearing, stated rather than implied:
//
//   - On documents, every one of them is. A path is caller-supplied and
//     names no parent, and a document id is a value a previous answer
//     handed back, so nothing but the project filter keeps either inside
//     one game. TestReadingAnotherGamesDocumentIsNotFound pins it for
//     GetDocumentByPath; the FOR UPDATE read's filter is pinned by the
//     same test too, if indirectly: dropping it reddens
//     TestWritingAPathAnotherGameUsesCreatesASecondDocument immediately,
//     because a write to another game's path would otherwise lock and
//     resurrect the first game's row instead of creating its own.
//   - On document_versions, the project filter is load-bearing *as
//     well*, and this is the one place Maestro deliberately does not
//     follow the metamodel's reasoning. There, a query reaching entities
//     through an entity_type_id is covered by the composite foreign key
//     and the filter is defence in depth. Here 0007_documents.sql gives
//     the child tables the same composite key, so the same argument
//     would apply -- and the spec (§5) rejects it for these tables
//     specifically: GetDocumentVersion and ListDocumentVersions are the
//     calls
//     where "join to the parent, then check" is one forgotten join away
//     from serving another game's prose, and the invariant must not
//     depend on anyone remembering. So the version queries carry their
//     own denormalised project_id and never join documents to establish
//     scope. InsertDocumentVersion writes it as a column rather than
//     filtering on it, and the composite key is what keeps it honest.
//     **Stated plainly, because it is checkable and was checked:** no
//     call this package offers can make that filter matter -- History
//     and ReadVersion resolve the document inside the game first, and
//     the composite key makes a version row disagreeing with its
//     document unrepresentable, so dropping the filter from either
//     query leaves the suite green. It stays for the callers that do
//     not resolve first, which Task 11's REST mirror may be. See
//     markdown.documentForVersions, which says the same thing where a
//     reader of the Go will find it.
//
// No write here sets updated_at. 0007_documents.sql puts a
// set_updated_at trigger on documents, so the column has one mechanism
// behind it rather than a trigger plus a clause every future query must
// remember.
// The compare-and-set, in one statement. Two writers cannot both read
// current_version 3 and both succeed: the DO UPDATE is guarded by the
// caller's expected version, so the loser matches no row and gets back
// no row rather than an error, which Go turns into the typed conflict.
// TestTwoConcurrentWritesLeaveOneWinnerAndNoGapInTheVersions pins it.
//
// A creating caller passes expected_version 0, which no stored version
// can equal -- current_version starts at 1 and only climbs -- so the
// guard is a no-op on the insert path and a guaranteed mismatch when a
// path the caller believed free turns out to be taken. That is the whole
// mechanism behind `expected_version: 0` (spec §7), and it is why the
// argument is required rather than inferred from absence.
//
// The path column is deliberately not in the SET list: the first
// spelling stored stands, so a re-seed under different casing addresses
// the existing document rather than rewriting the handle other documents
// and links refer to. That omission is also what lets Go refuse a
// respelling *after* this statement runs -- the returned row still
// carries the stored spelling -- which closes the creation race, where
// there was nothing yet to lock.
//
// kind is in the SET list, but not unconditionally: it is COALESCEd
// against the stored value rather than overwritten by excluded.kind,
// because kind is a property of the document -- what shelf it sits on --
// and not a property of any one edit. A caller passes NULL to mean "say
// nothing about kind", and every value including the empty string means
// "set it to this"; SQL's COALESCE already treats a NULL argument as
// "keep the left side" and a non-NULL one, empty string included, as
// "replace it," which is exactly that rule. On the insert arm the same
// COALESCE falls back to ” -- a new document's kind is never left NULL,
// matching the NOT NULL DEFAULT ” the column already carries.
// TestAnEditThatOmitsKindLeavesItUnchanged pins both directions.
//
// created_by_* are not in the SET list either: the creator of a document
// is a fact about its first version and does not change when someone
// else edits it. updated_by_* do change, on every write.
//
// deleted_at = NULL on the update arm is the resurrection rule (spec
// §3): writing to a soft-deleted path brings the document back and
// continues its version numbering, because the path is still taken and
// the history is still there. TestWritingToADeletedPathResurrectsItAnd
// ContinuesTheNumbering is what pins it: delete the clause and the
// resurrected document reads back as still deleted.
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.ProjectID,
		arg.Path,
		arg.Kind,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.Frontmatter,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.ExpectedVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertDocumentLink = `-- name: UpsertDocumentLink :one
INSERT INTO document_links (project_id, document_id, entity_id, role)
VALUES ($1::uuid, $2::uuid,
        $3::uuid, $4::text)
ON CONFLICT (document_id, entity_id) DO UPDATE
SET role = excluded.role
RETURNING id, project_id, document_id, entity_id, role, created_at
`

type UpsertDocumentLinkParams struct {
	ProjectID  uuid.UUID
	DocumentID uuid.UUID
	EntityID   uuid.UUID
	Role       string
}

// Idempotent by (document, entity): re-adding a link updates its role
// rather than making a second edge, which is what keeps a re-run seeding
// script from doubling every attachment.
// TestReAddingALinkUpdatesItsRoleRatherThanDuplicatingIt pins it.
//
// project_id is written, not filtered, and 0007_documents.sql's two
// composite keys are what make a cross-game link impossible by
// construction: this row's project_id must agree with the document's
// *and* with the entity's, so a document in one game cannot be attached
// to an entity in another whatever Go believes.
// TestALinkRowCannotClaimAGameItsDocumentDoesNotBelongTo forces that
// refusal from this package.
func (q *Queries) UpsertDocumentLink(ctx context.Context, arg UpsertDocumentLinkParams) (DocumentLink, error) {
	row := q.db.QueryRow(ctx, upsertDocumentLink,
		arg.ProjectID,
		arg.DocumentID,
		arg.EntityID,
		arg.Role,
	)
	var i DocumentLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DocumentID,
		&i.EntityID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
