// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const getDocumentByPath = `-- name: GetDocumentByPath :one
SELECT id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id FROM documents
WHERE project_id = $1::uuid
  AND lower(path) = lower($2::text)
  AND ($3::bool OR deleted_at IS NULL)
`

type GetDocumentByPathParams struct {
	ProjectID      uuid.UUID
	Path           string
	IncludeDeleted bool
}

// The read path. A soft-deleted document is not found unless the caller
// asked for it: deletion is soft so nothing is lost, not so that every
// reader has to filter. Both arms are exercised: the filtering one by
// TestDeletingADocumentHidesItFromReadsAndKeepsItsHistory, through
// Read, and the include_deleted one by deleteRefusal and
// conflictAfterFailedUpsert, which have to re-read a row that may be
// deleted in order to say why a write or a delete was refused --
// deleteRefusal's arm by TestDeletingTwiceIsNotFoundRatherThanASecond
// Tombstone, and conflictAfterFailedUpsert's by
// TestACreationRacingACreateAndDeleteIsToldTheTombstone.
func (q *Queries) GetDocumentByPath(ctx context.Context, arg GetDocumentByPathParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByPath, arg.ProjectID, arg.Path, arg.IncludeDeleted)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getDocumentByPathForUpdate = `-- name: GetDocumentByPathForUpdate :one
SELECT id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id FROM documents
WHERE project_id = $1::uuid
  AND lower(path) = lower($2::text)
FOR UPDATE
`

type GetDocumentByPathForUpdateParams struct {
	ProjectID uuid.UUID
	Path      string
}

// FOR UPDATE, and deliberately with no deleted_at filter: a write to a
// deleted path resurrects it, so the writer must see the row it is about
// to bring back, and must hold it.
//
// **What the lock buys, measured rather than asserted.** It does not buy
// the refusal: the guarded DO UPDATE refuses on its own, and dropping
// FOR UPDATE from this statement leaves the whole markdown suite green
// at -count=5. Nor does it buy the freshness of the number the loser is
// told to merge onto -- without the lock the read sees a stale version,
// passes the Go check, and the guarded upsert then refuses and
// conflictAfterFailedUpsert re-reads, arriving at the same fresh answer
// by a longer route. TestTheReportedCurrentVersionIsTheOneTheWriteWould
// HaveMet pins that answer, and it passes either way; it pins the
// guarantee, not this clause.
//
// What the lock does buy is the shape of the refusal rather than its
// existence: a conflicting writer is turned away before its body, its
// frontmatter and its version row are written and rolled back, and the
// pre-write spelling check in writeWith runs against a row no other
// transaction can move under it. It also serialises this write against a
// concurrent *delete* of the same row: without the lock, a hard delete
// landing between this read and the upsert would let the upsert's own
// INSERT arm fire on the freed path and silently re-create the document
// at version 1, rather than the writer being told the row is gone. All
// three are worth a row lock on a write that is already taking one.
// None is observable through this package's public surface, so no test
// here distinguishes them, and this comment says so rather than naming a
// test that would not go red. (The third case cannot fire until Task 4
// lands deletion, and deletion there is soft, so it is not reachable
// even then; a *hard* delete racing this read is not something Task 3
// or 4 need close, only something worth naming so a future hard-delete
// feature does not skip it. Task 4 landed and deletion there is soft, as
// predicted: SoftDeleteDocument is an UPDATE, so it takes this same row
// lock and the two serialise on it, and the resurrection the upsert then
// performs is the documented behaviour rather than a silent
// re-creation.)
func (q *Queries) GetDocumentByPathForUpdate(ctx context.Context, arg GetDocumentByPathForUpdateParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByPathForUpdate, arg.ProjectID, arg.Path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :one
INSERT INTO document_versions (project_id, document_id, version, title, summary, body_md,
                               frontmatter, message, deleted, author_user_id, author_token_id)
VALUES ($1::uuid, $2::uuid,
        $3::integer, $4::text, $5::text,
        $6::text, $7::jsonb, $8::text,
        $9::boolean,
        $10::uuid, $11::uuid)
RETURNING id, project_id, document_id, version, title, summary, body_md, frontmatter, message, deleted, author_user_id, author_token_id, created_at
`

type InsertDocumentVersionParams struct {
	ProjectID     uuid.UUID
	DocumentID    uuid.UUID
	Version       int32
	Title         string
	Summary       string
	BodyMd        string
	Frontmatter   []byte
	Message       string
	Deleted       bool
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
}

// The snapshot. Full bodies, never diffs (spec §3): a thousand versions
// of a long script is a few megabytes, which is nothing beside a diff
// chain that must be replayed to answer "show me version 12" and that
// corrupts every later version if one link is wrong.
//
// project_id is written from the caller's own resolved id, in the same
// transaction as the document write, and 0007_documents.sql's composite
// key is what keeps it honest: a version row whose project_id disagrees
// with its document's cannot be inserted at all
// (documents_schema_test.go pins that refusal).
//
// deleted is a required argument rather than a column left to its
// DEFAULT false, and that is deliberate: Delete's tombstone is the one
// caller that passes true, and every other caller has to say false out
// loud. A defaulted column would let a future snapshot-writing path
// forget the question and store a live version where a tombstone
// belonged, silently; a required argument turns the same omission into
// a compile error. TestDeletingADocumentHidesItFromReadsAndKeepsIts
// History reads the true case back and Task 3's
// TestTheFirstWriteAlsoWritesVersionOneWithItsAuthorAndMessage the
// false one.
func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, insertDocumentVersion,
		arg.ProjectID,
		arg.DocumentID,
		arg.Version,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.Frontmatter,
		arg.Message,
		arg.Deleted,
		arg.AuthorUserID,
		arg.AuthorTokenID,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.Message,
		&i.Deleted,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :one
UPDATE documents
SET deleted_at          = now(),
    current_version     = current_version + 1,
    updated_by_user_id  = $1::uuid,
    updated_by_token_id = $2::uuid
WHERE project_id = $3::uuid
  AND lower(path) = lower($4::text)
  AND deleted_at IS NULL
  AND current_version = $5::integer
RETURNING id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id
`

type SoftDeleteDocumentParams struct {
	ActorUserID     *uuid.UUID
	ActorTokenID    *uuid.UUID
	ProjectID       uuid.UUID
	Path            string
	ExpectedVersion int32
}

// Guarded by the caller's expected version, exactly as UpsertDocument
// is, so a delete cannot race an edit: the loser matches no row and gets
// back no row, which Go turns into the typed conflict.
// TestDeletingWithAStaleVersionIsAConflict pins the guard and
// TestDeletingAnotherGamesDocumentIsNotFound the project filter.
//
// deleted_at IS NULL is part of the guard, so deleting a document twice
// is not_found on the second call rather than a second tombstone. That
// is the honest answer: the document is already gone, and the caller has
// nothing to do. TestDeletingTwiceIsNotFoundRatherThanASecondTombstone
// pins it.
//
// current_version advances here and the caller appends the matching
// tombstone version in the same transaction. The two are one change and
// withTx is what keeps them so; the count assertion in
// TestDeletingADocumentHidesItFromReadsAndKeepsItsHistory is what
// refuses to let them drift.
//
// There is no FOR UPDATE read before this statement, unlike the write
// path. It would buy nothing here: this UPDATE takes the row lock
// itself, and everything the write path reads under its lock -- the
// stored spelling, a body to echo on a conflict -- this call either does
// not need or reads afterwards, in deleteRefusal, once it already knows
// it was refused.
func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, softDeleteDocument,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.ProjectID,
		arg.Path,
		arg.ExpectedVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertDocument = `-- name: UpsertDocument :one

INSERT INTO documents (project_id, path, kind, title, summary, body_md, frontmatter,
                       current_version,
                       created_by_user_id, created_by_token_id,
                       updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text,
        COALESCE($3::text, ''),
        $4::text, $5::text, $6::text,
        $7::jsonb, 1,
        $8::uuid, $9::uuid,
        $8::uuid, $9::uuid)
ON CONFLICT (project_id, lower(path)) DO UPDATE
SET kind                = COALESCE($3::text, documents.kind),
    title               = excluded.title,
    summary             = excluded.summary,
    body_md             = excluded.body_md,
    frontmatter         = excluded.frontmatter,
    current_version     = documents.current_version + 1,
    deleted_at          = NULL,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE documents.current_version = $10::integer
RETURNING id, project_id, path, kind, title, summary, body_md, frontmatter, current_version, deleted_at, search, created_at, updated_at, created_by_user_id, created_by_token_id, updated_by_user_id, updated_by_token_id
`

type UpsertDocumentParams struct {
	ProjectID       uuid.UUID
	Path            string
	Kind            *string
	Title           string
	Summary         string
	BodyMd          string
	Frontmatter     []byte
	ActorUserID     *uuid.UUID
	ActorTokenID    *uuid.UUID
	ExpectedVersion int32
}

// Every statement in this file carries the resolved project id: the
// reads as a filter, the writes as the column they set. Isolation
// between games is enforced in SQL, not in Go, so a query trusting a
// path or an id alone would hand a caller another game's prose the
// moment one leaked.
//
// Which filters are load-bearing, stated rather than implied:
//
//   - On documents, every one of them is. A path is caller-supplied and
//     names no parent, and a document id is a value a previous answer
//     handed back, so nothing but the project filter keeps either inside
//     one game. TestReadingAnotherGamesDocumentIsNotFound pins it for
//     GetDocumentByPath; the FOR UPDATE read's filter is pinned by the
//     same test too, if indirectly: dropping it reddens
//     TestWritingAPathAnotherGameUsesCreatesASecondDocument immediately,
//     because a write to another game's path would otherwise lock and
//     resurrect the first game's row instead of creating its own.
//   - On document_versions, the project filter is load-bearing *as
//     well*, and this is the one place Maestro deliberately does not
//     follow the metamodel's reasoning. There, a query reaching entities
//     through an entity_type_id is covered by the composite foreign key
//     and the filter is defence in depth. Here 0007_documents.sql gives
//     the child tables the same composite key, so the same argument
//     would apply -- and the spec (§5) rejects it for these tables
//     specifically: read_version and history (Task 6) are the calls
//     where "join to the parent, then check" is one forgotten join away
//     from serving another game's prose, and the invariant must not
//     depend on anyone remembering. So the version queries carry their
//     own denormalised project_id and never join documents to establish
//     scope. InsertDocumentVersion writes it as a column rather than
//     filtering on it, and the composite key is what keeps it honest.
//
// No write here sets updated_at. 0007_documents.sql puts a
// set_updated_at trigger on documents, so the column has one mechanism
// behind it rather than a trigger plus a clause every future query must
// remember.
// The compare-and-set, in one statement. Two writers cannot both read
// current_version 3 and both succeed: the DO UPDATE is guarded by the
// caller's expected version, so the loser matches no row and gets back
// no row rather than an error, which Go turns into the typed conflict.
// TestTwoConcurrentWritesLeaveOneWinnerAndNoGapInTheVersions pins it.
//
// A creating caller passes expected_version 0, which no stored version
// can equal -- current_version starts at 1 and only climbs -- so the
// guard is a no-op on the insert path and a guaranteed mismatch when a
// path the caller believed free turns out to be taken. That is the whole
// mechanism behind `expected_version: 0` (spec §7), and it is why the
// argument is required rather than inferred from absence.
//
// The path column is deliberately not in the SET list: the first
// spelling stored stands, so a re-seed under different casing addresses
// the existing document rather than rewriting the handle other documents
// and links refer to. That omission is also what lets Go refuse a
// respelling *after* this statement runs -- the returned row still
// carries the stored spelling -- which closes the creation race, where
// there was nothing yet to lock.
//
// kind is in the SET list, but not unconditionally: it is COALESCEd
// against the stored value rather than overwritten by excluded.kind,
// because kind is a property of the document -- what shelf it sits on --
// and not a property of any one edit. A caller passes NULL to mean "say
// nothing about kind", and every value including the empty string means
// "set it to this"; SQL's COALESCE already treats a NULL argument as
// "keep the left side" and a non-NULL one, empty string included, as
// "replace it," which is exactly that rule. On the insert arm the same
// COALESCE falls back to ” -- a new document's kind is never left NULL,
// matching the NOT NULL DEFAULT ” the column already carries.
// TestAnEditThatOmitsKindLeavesItUnchanged pins both directions.
//
// created_by_* are not in the SET list either: the creator of a document
// is a fact about its first version and does not change when someone
// else edits it. updated_by_* do change, on every write.
//
// deleted_at = NULL on the update arm is the resurrection rule (spec
// §3): writing to a soft-deleted path brings the document back and
// continues its version numbering, because the path is still taken and
// the history is still there. TestWritingToADeletedPathResurrectsItAnd
// ContinuesTheNumbering is what pins it: delete the clause and the
// resurrected document reads back as still deleted.
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.ProjectID,
		arg.Path,
		arg.Kind,
		arg.Title,
		arg.Summary,
		arg.BodyMd,
		arg.Frontmatter,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.ExpectedVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.BodyMd,
		&i.Frontmatter,
		&i.CurrentVersion,
		&i.DeletedAt,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.CreatedByTokenID,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}
