// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (token_hash, project_id, user_id, label, token_hint)
VALUES ($1::bytea, $2::uuid,
        $3::uuid, $4::text, $5::text)
RETURNING id, token_hash, project_id, user_id, label, created_at, last_used_at, revoked_at, token_hint
`

type CreateAPITokenParams struct {
	TokenHash []byte
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Label     string
	TokenHint string
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.TokenHash,
		arg.ProjectID,
		arg.UserID,
		arg.Label,
		arg.TokenHint,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProjectID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.TokenHint,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (token_hash, email, project_id, role, created_by, expires_at)
VALUES ($1::bytea, $2::text,
        $3::uuid, $4::text,
        $5::uuid, $6::timestamptz)
RETURNING id, token_hash, email, project_id, role, created_by, created_at, expires_at, redeemed_at, redeemed_by
`

type CreateInviteParams struct {
	TokenHash []byte
	Email     *string
	ProjectID *uuid.UUID
	Role      *string
	CreatedBy *uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TokenHash,
		arg.Email,
		arg.ProjectID,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.ProjectID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1::bytea, $2::uuid, $3::timestamptz)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, is_admin)
VALUES ($1::text, $2::text,
        $3::text, $4::boolean)
RETURNING id, email, display_name, password_hash, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :execrows
DELETE FROM invites WHERE redeemed_at IS NULL AND expires_at <= now()
`

// Only ever removes unredeemed rows (redeemed_at IS NULL): a redeemed
// invite past its original expires_at is not "expired" in any sense that
// matters (it already did its job and MarkInviteRedeemed's own WHERE
// clause makes it unreachable a second time regardless), and deleting it
// would erase who created an account or a membership grant and when —
// exactly the audit trail RevokeInvite above is careful to preserve too.
func (q *Queries) DeleteExpiredInvites(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvites)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1::bytea
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1::uuid
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const extendSession = `-- name: ExtendSession :execrows
UPDATE sessions
SET expires_at = LEAST(created_at + interval '90 days', now() + $1::interval)
WHERE token_hash = $2::bytea
  AND expires_at < now() + $1::interval - interval '1 minute'
`

type ExtendSessionParams struct {
	Ttl       pgtype.Interval
	TokenHash []byte
}

// Sliding renewal, called from web.resolveSessionCaller on a session past
// the halfway point of its SESSION_TTL. The target expiry is computed
// here, in SQL, from the session's own row and Postgres' own now() — not
// passed in from Go as an already-resolved timestamp. An earlier version
// did the latter (now().Add(ttl) computed once per request in auth.go)
// and its WHERE clause compared "is the new value later than the
// current one" — which sounds like it should make concurrent renewals
// collapse into one write, but does not: each request computes its own,
// slightly later, wall-clock target, so a second writer blocking on the
// row lock wakes up, re-evaluates against the now-committed row, finds
// its own target still greater, and writes again. A quality review
// proved this by holding the row lock open with pg_sleep and by firing
// fifteen concurrent requests at the real binary — three to six writes
// each time, not one.
//
// Two things fix that, both here instead of trusted to the Go caller:
//
// Concurrency: the target is now() + ttl computed by this statement, and
// the WHERE clause requires the *current* expires_at to be more than a
// minute short of that target before writing at all. A session already
// renewed by another concurrent request seconds ago has an expires_at
// within that one-minute slack of any request's now() + ttl, so it
// matches nothing and writes nothing. This does not collapse N
// concurrent requests into exactly one write in the general case — two
// requests arriving more than a minute apart both legitimately renew,
// which is the throttle working as intended, the same way
// TouchAPIToken's five-minute window lets last_used_at move again after
// it elapses — but it does mean requests that are actually concurrent
// (the case this comment used to overclaim "a no-op" for) collapse to
// one write, because they all fall inside the one-minute slack of each
// other's target.
//
// Absolute lifetime: capping the new value at created_at + 90 days (see
// identity.maxSessionLifetime in sessions.go, which this literal must
// match) means a session in continuous use is renewed right up to that
// cap and never again past it.
//
// This stays an UPDATE, never an upsert: a logout (DeleteSession) landing
// between the SELECT in UserForSession and this statement leaves no row
// to match, and an UPDATE that matches nothing creates nothing — a
// revoked session cannot be resurrected by a renewal that started before
// the revocation. Do not change this to INSERT ... ON CONFLICT to "handle"
// a missing row; a missing row here means "let it stay gone". This is
// :execrows, not :exec, purely so a test can count actual writes instead
// of inferring them from the final value, which looks identical whether
// one write happened or six.
func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSession, arg.Ttl, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, token_hash, email, project_id, role, created_by, created_at, expires_at, redeemed_at, redeemed_by FROM invites WHERE token_hash = $1::bytea
`

// Unlike GetLiveInvite, this ignores redeemed_at and expires_at: it exists
// only for RedeemInvite's fallback path, reached after GetLiveInvite has
// already found no row, to tell an expired invite apart from a truly
// unknown or already-redeemed one. Reaching that fallback at all requires
// the caller to already hold a token whose SHA-256 equals a stored
// token_hash, which nobody can produce without either holding the real
// token or having brute-forced 256 bits of entropy — so this query never
// gives an attacker anything they could not already get by holding the
// token itself.
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.ProjectID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
	)
	return i, err
}

const getLiveAPIToken = `-- name: GetLiveAPIToken :one
SELECT t.id, t.token_hash, t.project_id, t.user_id, t.label, t.created_at, t.last_used_at, t.revoked_at, t.token_hint, u.is_admin AS user_is_admin FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1::bytea AND t.revoked_at IS NULL
`

type GetLiveAPITokenRow struct {
	ID          uuid.UUID
	TokenHash   []byte
	ProjectID   uuid.UUID
	UserID      uuid.UUID
	Label       string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	TokenHint   string
	UserIsAdmin bool
}

// Joins users for is_admin so web.resolveBearerCaller can build a Caller
// from one query instead of two. This is a deliberate exception to the
// rest of this file keeping api_tokens and users apart (ListAPITokens
// below joins only for a display label, never a fact the middleware would
// trust) — see identity.APITokenSummary.UserIsAdmin's own doc comment for
// why this one earns the join: it replaces a second round trip on the
// hottest authenticated path in the product, the same class of cost
// TouchAPIToken's throttle and ExtendSession's guard above exist to
// control, and Task 9's original design (a lean, no-join lookup here) is
// the one being traded away to get it.
func (q *Queries) GetLiveAPIToken(ctx context.Context, tokenHash []byte) (GetLiveAPITokenRow, error) {
	row := q.db.QueryRow(ctx, getLiveAPIToken, tokenHash)
	var i GetLiveAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProjectID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.TokenHint,
		&i.UserIsAdmin,
	)
	return i, err
}

const getLiveInvite = `-- name: GetLiveInvite :one
SELECT id, token_hash, email, project_id, role, created_by, created_at, expires_at, redeemed_at, redeemed_by FROM invites
WHERE token_hash = $1::bytea
  AND redeemed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetLiveInvite(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getLiveInvite, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.ProjectID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.display_name, u.password_hash, u.is_admin, u.created_at, u.updated_at,
       s.expires_at AS session_expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1::bytea
  AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID               uuid.UUID
	Email            string
	DisplayName      string
	PasswordHash     string
	IsAdmin          bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SessionExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, is_admin, created_at, updated_at FROM users WHERE lower(email) = lower($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, is_admin, created_at, updated_at FROM users WHERE id = $1::uuid
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT t.id, t.project_id, t.user_id, u.display_name AS user_display_name,
       t.label, t.token_hint, t.created_at, t.last_used_at, t.revoked_at
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.project_id = $1::uuid
ORDER BY t.created_at DESC, t.id DESC
`

type ListAPITokensRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	UserID          uuid.UUID
	UserDisplayName string
	Label           string
	TokenHint       string
	CreatedAt       pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

// token_hash is deliberately not selected: this query backs an operator
// listing (ListAPITokens in tokens.go), and the hash of a bearer
// credential has no reason to leave the database even in a column nothing
// currently renders. token_hint is selected instead — see its column
// comment (migration 0003) for what it is safe to show. Revoked rows are
// included on purpose: this is the audit trail for what happened to a
// token, not only a list of what is still live. Joined to users so an
// operator triaging a leaked token sees who minted it instead of a raw
// id, and ordered by created_at then id so ties (two tokens minted in
// the same transaction) list in a stable order across repeated calls,
// the same tiebreak reasoning ListProjectsForUser and ListMembers
// already apply to their own orderings.
func (q *Queries) ListAPITokens(ctx context.Context, projectID uuid.UUID) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensRow
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.UserDisplayName,
			&i.Label,
			&i.TokenHint,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingInvites = `-- name: ListOutstandingInvites :many
SELECT id, token_hash, email, project_id, role, created_by, created_at, expires_at, redeemed_at, redeemed_by FROM invites WHERE redeemed_at IS NULL ORDER BY created_at DESC, id DESC
`

// "Outstanding" means not yet redeemed, regardless of whether it has since
// expired: an admin looking for a mis-sent invite to revoke needs to find
// it before it necessarily expires on its own, and a lapsed-but-unredeemed
// row is also useful context ("this one needs reissuing"). Ordered
// newest-first, with id as an explicit tiebreak (matching ListAPITokens
// and every other listing in this file that learned this lesson first) so
// two invites created in the same transaction don't reshuffle between
// calls.
func (q *Queries) ListOutstandingInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listOutstandingInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Email,
			&i.ProjectID,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.RedeemedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteRedeemed = `-- name: MarkInviteRedeemed :execrows
UPDATE invites SET redeemed_at = now(), redeemed_by = $1::uuid
WHERE id = $2::uuid
  AND redeemed_at IS NULL
  AND expires_at > now()
`

type MarkInviteRedeemedParams struct {
	RedeemedBy uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) MarkInviteRedeemed(ctx context.Context, arg MarkInviteRedeemedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInviteRedeemed, arg.RedeemedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1::uuid AND project_id = $2::uuid
  AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

// Scoped to project_id as well as id: revoking an id that exists but
// belongs to a different project, like revoking an unknown or
// already-revoked id, is a no-op rather than an error — the caller's goal
// (no live token under this id in this project) is already satisfied, the
// same convention RevokeSession and RevokeInvite already establish. This
// also means the project scope of the caller is enforced by the query
// itself, not by a separate ownership check the caller could forget.
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.ProjectID)
	return err
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites SET expires_at = now()
WHERE id = $1::uuid AND redeemed_at IS NULL
`

// Setting expires_at to now(), rather than deleting the row, keeps the
// audit trail (who created it, when, for what) intact instead of erasing
// it — the same reasoning DeleteExpiredInvites documents for why it only
// ever removes unredeemed rows. Restricted to redeemed_at IS NULL so
// revoking an already-redeemed or already-expired invite is a no-op that
// cannot rewrite a real redemption's or an earlier revocation's expires_at.
func (q *Queries) RevokeInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvite, id)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now()
WHERE id = $1::uuid
  AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

// Throttled: this runs on every authenticated agent request, so an
// unconditional UPDATE would take a row lock on the hot path for no
// observable benefit. Only write when the existing timestamp is missing or
// more than five minutes stale. An UPDATE whose WHERE clause matches no
// row takes no row lock at all, so the common case (touched within the
// last five minutes) costs a statement round trip but no lock contention.
// The five-minute interval here must match identity.touchThrottle in
// tokens.go, which pre-checks the same condition in Go before ever
// issuing this statement (so the common case skips the round trip
// entirely, not just the lock) — this WHERE clause stays authoritative
// regardless, since it is what actually makes the write safe under two
// concurrent resolves of the same token, which the Go pre-check alone
// cannot guarantee. Change one, change both.
func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $1::text
WHERE id = $2::uuid
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO memberships (user_id, project_id, role)
VALUES ($1::uuid, $2::uuid, $3::text)
ON CONFLICT (user_id, project_id) DO UPDATE SET role = excluded.role
`

type UpsertMembershipParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership, arg.UserID, arg.ProjectID, arg.Role)
	return err
}
