// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metamodel.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const countEntitiesOfType = `-- name: CountEntitiesOfType :one
SELECT count(*) FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
`

type CountEntitiesOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

func (q *Queries) CountEntitiesOfType(ctx context.Context, arg CountEntitiesOfTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesOfType, arg.ProjectID, arg.EntityTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntitiesOfType = `-- name: DeleteEntitiesOfType :exec
DELETE FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
`

type DeleteEntitiesOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

func (q *Queries) DeleteEntitiesOfType(ctx context.Context, arg DeleteEntitiesOfTypeParams) error {
	_, err := q.db.Exec(ctx, deleteEntitiesOfType, arg.ProjectID, arg.EntityTypeID)
	return err
}

const deleteEntityType = `-- name: DeleteEntityType :execrows
DELETE FROM entity_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteEntityTypeParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteEntityType(ctx context.Context, arg DeleteEntityTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntityType, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntityTypeByID = `-- name: GetEntityTypeByID :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetEntityTypeByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetEntityTypeByID(ctx context.Context, arg GetEntityTypeByIDParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByID, arg.ProjectID, arg.ID)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByKey = `-- name: GetEntityTypeByKey :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
`

type GetEntityTypeByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetEntityTypeByKey(ctx context.Context, arg GetEntityTypeByKeyParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByKey, arg.ProjectID, arg.Key)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByKeyForUpdate = `-- name: GetEntityTypeByKeyForUpdate :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
FOR UPDATE
`

type GetEntityTypeByKeyForUpdateParams struct {
	ProjectID uuid.UUID
	Key       string
}

// The upsert's own read, taken inside its transaction with the row lock
// held, so the spelling and version a caller is told about are the ones
// their write will actually meet. Without the lock, two writers racing on
// one key both read the same version and the second's report of "current
// version is N" is stale by the time it is returned.
func (q *Queries) GetEntityTypeByKeyForUpdate(ctx context.Context, arg GetEntityTypeByKeyForUpdateParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByKeyForUpdate, arg.ProjectID, arg.Key)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const listEntityFieldsOfType = `-- name: ListEntityFieldsOfType :many
SELECT id, fields FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
ORDER BY id
`

type ListEntityFieldsOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

type ListEntityFieldsOfTypeRow struct {
	ID     uuid.UUID
	Fields []byte
}

// The re-validation sweep reads nothing but the stored values and the id
// to flag, so it does not pay to load whole rows — a type can hold
// hundreds of entities and every schema edit sweeps all of them.
func (q *Queries) ListEntityFieldsOfType(ctx context.Context, arg ListEntityFieldsOfTypeParams) ([]ListEntityFieldsOfTypeRow, error) {
	rows, err := q.db.Query(ctx, listEntityFieldsOfType, arg.ProjectID, arg.EntityTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityFieldsOfTypeRow
	for rows.Next() {
		var i ListEntityFieldsOfTypeRow
		if err := rows.Scan(&i.ID, &i.Fields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityTypes = `-- name: ListEntityTypes :many
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid
ORDER BY label, id
`

// Ordered by label then id: labels are not unique, and a label-only order
// reshuffles ties between calls in whatever order Postgres returns them.
func (q *Queries) ListEntityTypes(ctx context.Context, projectID uuid.UUID) ([]EntityType, error) {
	rows, err := q.db.Query(ctx, listEntityTypes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityType
	for rows.Next() {
		var i EntityType
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.LabelPlural,
			&i.Description,
			&i.Color,
			&i.Icon,
			&i.FieldSchema,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEntitiesOfTypeInvalid = `-- name: MarkEntitiesOfTypeInvalid :exec
UPDATE entities SET invalid = $1::boolean
WHERE project_id = $2::uuid
  AND entity_type_id = $3::uuid
  AND id = ANY($4::uuid[])
  AND invalid <> $1::boolean
`

type MarkEntitiesOfTypeInvalidParams struct {
	Invalid      bool
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Ids          []uuid.UUID
}

// The invalid <> flag guard keeps the sweep from rewriting rows whose
// verdict has not changed. Without it, every schema edit would touch each
// of the type's entities and the set_updated_at trigger would move their
// updated_at, so a validation pass would read as an edit of content
// nobody edited.
func (q *Queries) MarkEntitiesOfTypeInvalid(ctx context.Context, arg MarkEntitiesOfTypeInvalidParams) error {
	_, err := q.db.Exec(ctx, markEntitiesOfTypeInvalid,
		arg.Invalid,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Ids,
	)
	return err
}

const upsertEntityType = `-- name: UpsertEntityType :one
INSERT INTO entity_types (project_id, key, label, label_plural, description, color, icon,
                          field_schema, updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::text,
        $6::text, $7::text, $8::jsonb,
        $9::uuid, $10::uuid)
ON CONFLICT (project_id, lower(key)) DO UPDATE
SET label               = excluded.label,
    label_plural        = excluded.label_plural,
    description         = excluded.description,
    color               = excluded.color,
    icon                = excluded.icon,
    field_schema        = excluded.field_schema,
    version             = entity_types.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE entity_types.version = $11::integer
RETURNING id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertEntityTypeParams struct {
	ProjectID        uuid.UUID
	Key              string
	Label            string
	LabelPlural      string
	Description      string
	Color            string
	Icon             string
	FieldSchema      []byte
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// Every statement in this file filters on the resolved project id,
// including the ones addressing a row by its primary key: isolation
// between games is enforced in SQL, not in Go, so a query trusting an id
// alone would hand a caller another game's row the moment an id leaked.
//
// That is the whole mechanism only for the statements addressing
// entity_types itself (GetEntityTypeByID, DeleteEntityType): drop the
// filter there and a leaked id reads, or deletes, another game's type,
// which TestTypesAreScopedToTheirProject pins. It is *not* the mechanism
// for the three statements reaching entities through an entity_type_id
// (ListEntityFieldsOfType, MarkEntitiesOfTypeInvalid,
// DeleteEntitiesOfType). 0004_metamodel.sql gives entities a composite
// FOREIGN KEY (entity_type_id, project_id) REFERENCES
// entity_types (id, project_id), so an entity's project is already
// determined by its type's: no row can match a type id under one project
// id and not another, and dropping the filter from those three changes no
// result and can be caught by no test. They keep it as defence in depth,
// against a future schema that relaxes that composite key, and so that a
// reader adding the next entities query copies the safe shape rather than
// having to work out which statements happen to be covered by a
// constraint. Written down here because a comment claiming these filters
// are what isolates games would be relied on as if it were true.
//
// No write here sets updated_at. 0004_metamodel.sql puts a set_updated_at
// trigger on all four tables, so the column has one mechanism behind it
// rather than a trigger plus a clause every future query must remember.
//
// The DO UPDATE is guarded by the caller's expected version, so the whole
// compare-and-set happens in one statement and two concurrent writers
// cannot both read version 1 and both succeed. A creating caller has no
// version to expect and passes noVersion, which no stored version can
// equal, so the guard is a no-op on the insert path and a guaranteed
// mismatch when a row it did not know about turns out to exist. A guard
// that fails returns no row rather than an error; UpsertEntityType turns
// that into the typed conflict.
//
// Idempotent by (project, key), matched case-insensitively through the
// entity_types_key_key index. The key column itself is deliberately not in
// the SET list: the first spelling stored stays, so a re-seed cannot
// rewrite the handle other rows and documents refer to. That omission is
// also what lets UpsertEntityType in Go refuse a respelling *after* this
// statement runs: the row returned still carries the stored key, so
// comparing it to the submitted one catches a writer whose own locked read
// could not have seen this row at all — a creation racing a creator, where
// there was nothing yet to lock. So this clause is what makes an identical
// spelling a no-op; it is not what resolves a conflict.
func (q *Queries) UpsertEntityType(ctx context.Context, arg UpsertEntityTypeParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, upsertEntityType,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.LabelPlural,
		arg.Description,
		arg.Color,
		arg.Icon,
		arg.FieldSchema,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}
