// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metamodel.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const countEntitiesOfType = `-- name: CountEntitiesOfType :one
SELECT count(*) FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
`

type CountEntitiesOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

func (q *Queries) CountEntitiesOfType(ctx context.Context, arg CountEntitiesOfTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesOfType, arg.ProjectID, arg.EntityTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntitiesOfType = `-- name: DeleteEntitiesOfType :exec
DELETE FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
`

type DeleteEntitiesOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

func (q *Queries) DeleteEntitiesOfType(ctx context.Context, arg DeleteEntitiesOfTypeParams) error {
	_, err := q.db.Exec(ctx, deleteEntitiesOfType, arg.ProjectID, arg.EntityTypeID)
	return err
}

const deleteEntity = `-- name: DeleteEntity :execrows
DELETE FROM entities
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteEntityParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteEntity(ctx context.Context, arg DeleteEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntity, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEntityType = `-- name: DeleteEntityType :execrows
DELETE FROM entity_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteEntityTypeParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteEntityType(ctx context.Context, arg DeleteEntityTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntityType, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetEntityByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetEntityByID(ctx context.Context, arg GetEntityByIDParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByID, arg.ProjectID, arg.ID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityByKey = `-- name: GetEntityByKey :one
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
  AND lower(key) = lower($3::text)
`

type GetEntityByKeyParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Key          string
}

func (q *Queries) GetEntityByKey(ctx context.Context, arg GetEntityByKeyParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByKey, arg.ProjectID, arg.EntityTypeID, arg.Key)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityByKeyForUpdate = `-- name: GetEntityByKeyForUpdate :one
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
  AND lower(key) = lower($3::text)
FOR UPDATE
`

type GetEntityByKeyForUpdateParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Key          string
}

// FOR UPDATE, for the reason GetEntityTypeByKeyForUpdate records: without
// the lock the read runs against the transaction's snapshot, so a caller
// racing an in-flight edit is told to merge onto a version that is
// already stale by the time it retries, and retries into the same refusal
// forever. What the lock buys is not the refusal -- the guarded DO UPDATE
// refuses on its own -- but the *number* the caller is told to merge
// onto. TestTheReportedCurrentEntityVersionIsTheOneTheWriteWouldHaveMet
// pins exactly that, because nothing else here does: both entity race
// tests block on the unique index inside the INSERT, not on this lock.
func (q *Queries) GetEntityByKeyForUpdate(ctx context.Context, arg GetEntityByKeyForUpdateParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByKeyForUpdate, arg.ProjectID, arg.EntityTypeID, arg.Key)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByID = `-- name: GetEntityTypeByID :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetEntityTypeByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetEntityTypeByID(ctx context.Context, arg GetEntityTypeByIDParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByID, arg.ProjectID, arg.ID)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByKey = `-- name: GetEntityTypeByKey :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
`

type GetEntityTypeByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetEntityTypeByKey(ctx context.Context, arg GetEntityTypeByKeyParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByKey, arg.ProjectID, arg.Key)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByKeyForUpdate = `-- name: GetEntityTypeByKeyForUpdate :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
FOR UPDATE
`

type GetEntityTypeByKeyForUpdateParams struct {
	ProjectID uuid.UUID
	Key       string
}

// The upsert's own read, taken inside its transaction with the row lock
// held, so the spelling and version a caller is told about are the ones
// their write will actually meet. Without the lock, two writers racing on
// one key both read the same version and the second's report of "current
// version is N" is stale by the time it is returned.
func (q *Queries) GetEntityTypeByKeyForUpdate(ctx context.Context, arg GetEntityTypeByKeyForUpdateParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByKeyForUpdate, arg.ProjectID, arg.Key)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const listEntityFieldsOfType = `-- name: ListEntityFieldsOfType :many
SELECT id, fields FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
ORDER BY id
`

type ListEntityFieldsOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

type ListEntityFieldsOfTypeRow struct {
	ID     uuid.UUID
	Fields []byte
}

// The re-validation sweep reads nothing but the stored values and the id
// to flag, so it does not pay to load whole rows — a type can hold
// hundreds of entities and every schema edit sweeps all of them.
func (q *Queries) ListEntityFieldsOfType(ctx context.Context, arg ListEntityFieldsOfTypeParams) ([]ListEntityFieldsOfTypeRow, error) {
	rows, err := q.db.Query(ctx, listEntityFieldsOfType, arg.ProjectID, arg.EntityTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityFieldsOfTypeRow
	for rows.Next() {
		var i ListEntityFieldsOfTypeRow
		if err := rows.Scan(&i.ID, &i.Fields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityTypes = `-- name: ListEntityTypes :many
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid
ORDER BY label, id
`

// Ordered by label then id: labels are not unique, and a label-only order
// reshuffles ties between calls in whatever order Postgres returns them.
func (q *Queries) ListEntityTypes(ctx context.Context, projectID uuid.UUID) ([]EntityType, error) {
	rows, err := q.db.Query(ctx, listEntityTypes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityType
	for rows.Next() {
		var i EntityType
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.LabelPlural,
			&i.Description,
			&i.Color,
			&i.Icon,
			&i.FieldSchema,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEntitiesOfTypeInvalid = `-- name: MarkEntitiesOfTypeInvalid :exec
UPDATE entities SET invalid = $1::boolean
WHERE project_id = $2::uuid
  AND entity_type_id = $3::uuid
  AND id = ANY($4::uuid[])
  AND invalid <> $1::boolean
`

type MarkEntitiesOfTypeInvalidParams struct {
	Invalid      bool
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Ids          []uuid.UUID
}

// The invalid <> flag guard keeps the sweep from rewriting rows whose
// verdict has not changed. Without it, every schema edit would touch each
// of the type's entities and the set_updated_at trigger would move their
// updated_at, so a validation pass would read as an edit of content
// nobody edited.
func (q *Queries) MarkEntitiesOfTypeInvalid(ctx context.Context, arg MarkEntitiesOfTypeInvalidParams) error {
	_, err := q.db.Exec(ctx, markEntitiesOfTypeInvalid,
		arg.Invalid,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Ids,
	)
	return err
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (project_id, entity_type_id, key, name, fields, search,
                      updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::uuid,
        $3::text, $4::text, $5::jsonb,
        to_tsvector('simple', $4::text || ' ' || $6::text),
        $7::uuid, $8::uuid)
ON CONFLICT (project_id, entity_type_id, lower(key)) DO UPDATE
SET name                = excluded.name,
    fields              = excluded.fields,
    search              = excluded.search,
    invalid             = false,
    version             = entities.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE entities.version = $9::integer
RETURNING id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertEntityParams struct {
	ProjectID        uuid.UUID
	EntityTypeID     uuid.UUID
	Key              string
	Name             string
	Fields           []byte
	SearchText       string
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// The same shape as UpsertEntityType, for the same reasons, and that
// statement's comment carries the full argument. In short:
//
//   - The DO UPDATE is guarded by the caller's expected version, so the
//     whole compare-and-set is one statement and two writers cannot both
//     read version 1 and both succeed. A creating caller passes
//     noVersion, which no stored version can equal.
//   - The key column is deliberately not in the SET list. The first
//     spelling stored stands, and the returned row therefore still
//     carries it -- which is what lets Go refuse a respelling *after* the
//     write, closing the creation-race hole.
//   - No write sets updated_at: 0004_metamodel.sql puts a set_updated_at
//     trigger on all four tables, and a clause here would be a second
//     mechanism behind one column.
//   - The audit columns are carried, so the composite
//     FOREIGN KEY (updated_by_token_id, project_id) catches a token
//     scoped to another game.
//
// search is written by this statement and by nothing else, on both arms
// of the upsert. It cannot be a generated column: it is derived from
// user-declared jsonb whose *text* fields are the only ones worth
// indexing, and which of a row's fields those are is known only to the
// Go validator that has just read the type's schema. So every write path
// that changes name or fields must come through here, or the row stays
// indexed under its previous words and a search stops finding it with
// nothing to signal why.
//
// invalid is reset to false because the caller has just validated these
// values against the type's current schema; a row that is being written
// is a row that has been judged.
func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Key,
		arg.Name,
		arg.Fields,
		arg.SearchText,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertEntityType = `-- name: UpsertEntityType :one
INSERT INTO entity_types (project_id, key, label, label_plural, description, color, icon,
                          field_schema, updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::text,
        $6::text, $7::text, $8::jsonb,
        $9::uuid, $10::uuid)
ON CONFLICT (project_id, lower(key)) DO UPDATE
SET label               = excluded.label,
    label_plural        = excluded.label_plural,
    description         = excluded.description,
    color               = excluded.color,
    icon                = excluded.icon,
    field_schema        = excluded.field_schema,
    version             = entity_types.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE entity_types.version = $11::integer
RETURNING id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertEntityTypeParams struct {
	ProjectID        uuid.UUID
	Key              string
	Label            string
	LabelPlural      string
	Description      string
	Color            string
	Icon             string
	FieldSchema      []byte
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// Every statement in this file carries the resolved project id -- the
// reads and deletes as a filter, including the ones addressing a row by
// its primary key, and the upserts as the column they write. Isolation
// between games is enforced in SQL, not in Go, so a query trusting an id
// alone would hand a caller another game's row the moment an id leaked.
//
// That is the whole mechanism only for the statements addressing a row
// by its own primary key: GetEntityTypeByID and DeleteEntityType, which
// TestTypesAreScopedToTheirProject pins, and GetEntityByID and
// DeleteEntity, which
// TestTheEntityQueriesThatAddressARowByIDAreScopedToTheProject pins.
// Drop the filter from any of the four and a leaked id reads, or
// deletes, another game's row. The entity pair needed a test of its own
// against the queries: their only caller is RemoveEntity, which reads
// the row, then its type, then deletes, so each of its three filters
// masks the others and only mutating all three at once is observable
// through the service.
//
// It is *not* the mechanism for the statements reaching entities through
// an entity_type_id (ListEntityFieldsOfType, MarkEntitiesOfTypeInvalid,
// DeleteEntitiesOfType, GetEntityByKey, GetEntityByKeyForUpdate).
// 0004_metamodel.sql gives entities a composite
// FOREIGN KEY (entity_type_id, project_id) REFERENCES
// entity_types (id, project_id), so an entity's project is already
// determined by its type's: no row can match a type id under one project
// id and not another, and dropping the filter from any of those five
// changes no result and can be caught by no test. They keep it as
// defence in depth, against a future schema that relaxes that composite
// key, and so that a
// reader adding the next entities query copies the safe shape rather than
// having to work out which statements happen to be covered by a
// constraint. Written down here because a comment claiming these filters
// are what isolates games would be relied on as if it were true.
//
// UpsertEntity is deliberately not in that list, and is not unobservable
// either: it has no project filter at all. Its project_id is a NOT NULL
// column value it writes and part of its ON CONFLICT
// (project_id, entity_type_id, lower(key)) target, so removing it is a
// syntax or constraint error rather than a silently widened query --
// nothing about it can be dropped and still compile.
//
// No write here sets updated_at. 0004_metamodel.sql puts a set_updated_at
// trigger on all four tables, so the column has one mechanism behind it
// rather than a trigger plus a clause every future query must remember.
//
// The DO UPDATE is guarded by the caller's expected version, so the whole
// compare-and-set happens in one statement and two concurrent writers
// cannot both read version 1 and both succeed. A creating caller has no
// version to expect and passes noVersion, which no stored version can
// equal, so the guard is a no-op on the insert path and a guaranteed
// mismatch when a row it did not know about turns out to exist. A guard
// that fails returns no row rather than an error; UpsertEntityType turns
// that into the typed conflict.
//
// Idempotent by (project, key), matched case-insensitively through the
// entity_types_key_key index. The key column itself is deliberately not in
// the SET list: the first spelling stored stays, so a re-seed cannot
// rewrite the handle other rows and documents refer to. That omission is
// also what lets UpsertEntityType in Go refuse a respelling *after* this
// statement runs: the row returned still carries the stored key, so
// comparing it to the submitted one catches a writer whose own locked read
// could not have seen this row at all — a creation racing a creator, where
// there was nothing yet to lock. So this clause is what makes an identical
// spelling a no-op; it is not what resolves a conflict.
func (q *Queries) UpsertEntityType(ctx context.Context, arg UpsertEntityTypeParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, upsertEntityType,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.LabelPlural,
		arg.Description,
		arg.Color,
		arg.Icon,
		arg.FieldSchema,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}
