// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metamodel.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEntitiesOfType = `-- name: CountEntitiesOfType :one
SELECT count(*) FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
`

type CountEntitiesOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

func (q *Queries) CountEntitiesOfType(ctx context.Context, arg CountEntitiesOfTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesOfType, arg.ProjectID, arg.EntityTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelationsOfType = `-- name: CountRelationsOfType :one
SELECT count(*) FROM relations
WHERE project_id = $1::uuid
  AND relation_type_id = $2::uuid
`

type CountRelationsOfTypeParams struct {
	ProjectID      uuid.UUID
	RelationTypeID uuid.UUID
}

func (q *Queries) CountRelationsOfType(ctx context.Context, arg CountRelationsOfTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRelationsOfType, arg.ProjectID, arg.RelationTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntitiesOfType = `-- name: DeleteEntitiesOfType :exec
DELETE FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
`

type DeleteEntitiesOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

func (q *Queries) DeleteEntitiesOfType(ctx context.Context, arg DeleteEntitiesOfTypeParams) error {
	_, err := q.db.Exec(ctx, deleteEntitiesOfType, arg.ProjectID, arg.EntityTypeID)
	return err
}

const deleteEntity = `-- name: DeleteEntity :execrows
DELETE FROM entities
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteEntityParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteEntity(ctx context.Context, arg DeleteEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntity, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEntityType = `-- name: DeleteEntityType :execrows
DELETE FROM entity_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteEntityTypeParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteEntityType(ctx context.Context, arg DeleteEntityTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntityType, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRelation = `-- name: DeleteRelation :execrows
DELETE FROM relations
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteRelationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteRelation(ctx context.Context, arg DeleteRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelation, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRelationType = `-- name: DeleteRelationType :execrows
DELETE FROM relation_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteRelationTypeParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteRelationType(ctx context.Context, arg DeleteRelationTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelationType, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRelationsOfType = `-- name: DeleteRelationsOfType :exec
DELETE FROM relations
WHERE project_id = $1::uuid
  AND relation_type_id = $2::uuid
`

type DeleteRelationsOfTypeParams struct {
	ProjectID      uuid.UUID
	RelationTypeID uuid.UUID
}

func (q *Queries) DeleteRelationsOfType(ctx context.Context, arg DeleteRelationsOfTypeParams) error {
	_, err := q.db.Exec(ctx, deleteRelationsOfType, arg.ProjectID, arg.RelationTypeID)
	return err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetEntityByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetEntityByID(ctx context.Context, arg GetEntityByIDParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByID, arg.ProjectID, arg.ID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityByKey = `-- name: GetEntityByKey :one
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
  AND lower(key) = lower($3::text)
`

type GetEntityByKeyParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Key          string
}

func (q *Queries) GetEntityByKey(ctx context.Context, arg GetEntityByKeyParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByKey, arg.ProjectID, arg.EntityTypeID, arg.Key)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityByKeyForUpdate = `-- name: GetEntityByKeyForUpdate :one
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
  AND lower(key) = lower($3::text)
FOR UPDATE
`

type GetEntityByKeyForUpdateParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Key          string
}

// FOR UPDATE, for the reason GetEntityTypeByKeyForUpdate records: without
// the lock the read runs against the transaction's snapshot, so a caller
// racing an in-flight edit is told to merge onto a version that is
// already stale by the time it retries, and retries into the same refusal
// forever. What the lock buys is not the refusal -- the guarded DO UPDATE
// refuses on its own -- but the *number* the caller is told to merge
// onto. TestTheReportedCurrentEntityVersionIsTheOneTheWriteWouldHaveMet
// pins exactly that, because nothing else here does: both entity race
// tests block on the unique index inside the INSERT, not on this lock.
func (q *Queries) GetEntityByKeyForUpdate(ctx context.Context, arg GetEntityByKeyForUpdateParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByKeyForUpdate, arg.ProjectID, arg.EntityTypeID, arg.Key)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByID = `-- name: GetEntityTypeByID :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetEntityTypeByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetEntityTypeByID(ctx context.Context, arg GetEntityTypeByIDParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByID, arg.ProjectID, arg.ID)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByKey = `-- name: GetEntityTypeByKey :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
`

type GetEntityTypeByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetEntityTypeByKey(ctx context.Context, arg GetEntityTypeByKeyParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByKey, arg.ProjectID, arg.Key)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getEntityTypeByKeyForUpdate = `-- name: GetEntityTypeByKeyForUpdate :one
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
FOR UPDATE
`

type GetEntityTypeByKeyForUpdateParams struct {
	ProjectID uuid.UUID
	Key       string
}

// The upsert's own read, taken inside its transaction with the row lock
// held, so the spelling and version a caller is told about are the ones
// their write will actually meet. Without the lock, two writers racing on
// one key both read the same version and the second's report of "current
// version is N" is stale by the time it is returned.
func (q *Queries) GetEntityTypeByKeyForUpdate(ctx context.Context, arg GetEntityTypeByKeyForUpdateParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, getEntityTypeByKeyForUpdate, arg.ProjectID, arg.Key)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getRelationByID = `-- name: GetRelationByID :one
SELECT id, project_id, relation_type_id, source_id, target_id, fields, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM relations
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetRelationByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetRelationByID(ctx context.Context, arg GetRelationByIDParams) (Relation, error) {
	row := q.db.QueryRow(ctx, getRelationByID, arg.ProjectID, arg.ID)
	var i Relation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RelationTypeID,
		&i.SourceID,
		&i.TargetID,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getRelationTypeByID = `-- name: GetRelationTypeByID :one
SELECT id, project_id, key, label, description, source_type_ids, target_type_ids, semantic_role, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM relation_types
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetRelationTypeByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetRelationTypeByID(ctx context.Context, arg GetRelationTypeByIDParams) (RelationType, error) {
	row := q.db.QueryRow(ctx, getRelationTypeByID, arg.ProjectID, arg.ID)
	var i RelationType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.SourceTypeIds,
		&i.TargetTypeIds,
		&i.SemanticRole,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getRelationTypeByKey = `-- name: GetRelationTypeByKey :one
SELECT id, project_id, key, label, description, source_type_ids, target_type_ids, semantic_role, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM relation_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
`

type GetRelationTypeByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetRelationTypeByKey(ctx context.Context, arg GetRelationTypeByKeyParams) (RelationType, error) {
	row := q.db.QueryRow(ctx, getRelationTypeByKey, arg.ProjectID, arg.Key)
	var i RelationType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.SourceTypeIds,
		&i.TargetTypeIds,
		&i.SemanticRole,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getRelationTypeByKeyForUpdate = `-- name: GetRelationTypeByKeyForUpdate :one
SELECT id, project_id, key, label, description, source_type_ids, target_type_ids, semantic_role, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM relation_types
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
FOR UPDATE
`

type GetRelationTypeByKeyForUpdateParams struct {
	ProjectID uuid.UUID
	Key       string
}

// FOR UPDATE, for the reason GetEntityTypeByKeyForUpdate records: the
// lock is what makes the reported current version the one this caller's
// own write would have met, so "re-read and retry with 2" is advice that
// works.
func (q *Queries) GetRelationTypeByKeyForUpdate(ctx context.Context, arg GetRelationTypeByKeyForUpdateParams) (RelationType, error) {
	row := q.db.QueryRow(ctx, getRelationTypeByKeyForUpdate, arg.ProjectID, arg.Key)
	var i RelationType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.SourceTypeIds,
		&i.TargetTypeIds,
		&i.SemanticRole,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const listEntitiesPage = `-- name: ListEntitiesPage :many
SELECT id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entities
WHERE project_id = $1::uuid
  AND ($2::uuid IS NULL OR entity_type_id = $2::uuid)
  AND ($3::boolean IS NULL OR invalid = $3::boolean)
  AND ($4::uuid IS NULL
       OR (name, id) > ($5::text, $4::uuid))
ORDER BY name, id
LIMIT $6::int
`

type ListEntitiesPageParams struct {
	ProjectID    uuid.UUID
	EntityTypeID *uuid.UUID
	Invalid      *bool
	AfterID      *uuid.UUID
	AfterName    *string
	Limit        int32
}

// One page of a game's entities, keyed on (name, id).
//
// entities_listing_idx, added in 0005, is (project_id, name, id): this
// statement's filter and its whole sort key, so the position a cursor
// carries is sought to rather than arrived at by sorting the game. The
// migration carries the measurement and what the index costs a write.
//
// **The project filter is load-bearing**, as it is on ListRelations and
// for the same reason: the after_name/after_id position is
// caller-supplied and names no parent whose composite key could scope
// this statement. Drop it and a caller pages another game's rows.
// entity_type_id is resolved from a key inside the project before it
// gets here, so that filter narrows the answer rather than isolating it.
//
// The keyset compares uuid to uuid rather than casting id to text. A
// keyset whose comparison disagrees with its own ORDER BY skips or
// repeats rows at a page boundary and says nothing, so the comparison
// must use the same operator the sort does -- and here it demonstrably
// does, rather than being trusted to agree.
//
// **`id` in the ORDER BY is half of that agreement and it is pinned by a
// test**, which it was not at first: dropping it left the whole suite
// green, because every test then in the suite seeded distinct names.
// With ten rows sharing one name and a page of three, the unpinned
// version returned five distinct rows of ten and three of them twice --
// Postgres orders tied rows however each statement happens to, so the
// comparison lands nowhere near where the previous page stopped.
// Duplicate names are ordinary in game content, so
// TestPagingIsStableWhenEveryRowSharesOneName now holds both listings to
// it. The collation half below was defended from the start; this half
// was not, and a convention defended only by a comment is what the next
// listing will copy.
//
// The text form was measured
// on this project's own Postgres before the choice was made: over
// 300,000 random pairs under its en_US.utf8 collation, (a < b) and
// (a::text < b::text) never disagreed, so the cast is not a live bug
// today. What it is is a correctness that depends on the collation the
// deployment happens to have chosen, for nothing gained; comparing
// uuids removes the dependency instead of documenting it.
//
// after_id alone guards the clause, and after_name is read only when it
// is set: the two are always written together by the cursor decoder, and
// a row comparison against a NULL half yields NULL, which reads as false
// and would return an empty page rather than a refusal.
func (q *Queries) ListEntitiesPage(ctx context.Context, arg ListEntitiesPageParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesPage,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Invalid,
		arg.AfterID,
		arg.AfterName,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityTypeID,
			&i.Key,
			&i.Name,
			&i.Fields,
			&i.Invalid,
			&i.Version,
			&i.Search,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesRelatedTo = `-- name: ListEntitiesRelatedTo :many
SELECT e.id, e.project_id, e.entity_type_id, e.key, e.name, e.fields, e.invalid, e.version, e.search, e.created_at, e.updated_at, e.updated_by_user_id, e.updated_by_token_id FROM entities e
JOIN relations r
  ON ($1::text = 'outgoing'
      AND r.source_id = $2::uuid AND r.target_id = e.id)
  OR ($1::text = 'incoming'
      AND r.target_id = $2::uuid AND r.source_id = e.id)
WHERE e.project_id = $3::uuid
  AND r.project_id = $3::uuid
  AND r.relation_type_id = $4::uuid
  AND ($5::uuid IS NULL OR e.entity_type_id = $5::uuid)
  AND ($6::boolean IS NULL OR e.invalid = $6::boolean)
  AND ($7::uuid IS NULL
       OR (e.name, e.id) > ($8::text, $7::uuid))
ORDER BY e.name, e.id
LIMIT $9::int
`

type ListEntitiesRelatedToParams struct {
	Direction      string
	AnchorID       uuid.UUID
	ProjectID      uuid.UUID
	RelationTypeID uuid.UUID
	EntityTypeID   *uuid.UUID
	Invalid        *bool
	AfterID        *uuid.UUID
	AfterName      *string
	Limit          int32
}

// One page of the entities one hop from an anchor, along one relation
// type, in one direction.
//
// The join condition, not a WHERE clause, is what selects the far end of
// each edge, and it is written so that exactly one of the two arms can
// hold for a given (entity, edge) pair. That is what makes a self-loop
// appear once: the pair (anchor, loop) satisfies its direction's arm and
// produces one join row, not two.
//
// **Neither project filter here is what isolates games**, unlike
// ListEntitiesPage's. anchor_id and relation_type_id are both resolved
// from keys inside the project by the Go caller before this runs, and
// 0004_metamodel.sql's composite foreign keys put an edge, its type and
// both its endpoints in one project by construction, so no row can match
// an anchor of one game under another game's project id. Removing either
// filter changes no result and can be caught by no test; they are here as
// defence in depth and so that the next reader adding a traversal query
// copies the safe shape. The Go caller's key resolution is the mechanism.
//
// The same keyset as ListEntitiesPage, for the same reasons, so a
// traversal pages like every other listing instead of being silently
// truncated at its limit.
func (q *Queries) ListEntitiesRelatedTo(ctx context.Context, arg ListEntitiesRelatedToParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesRelatedTo,
		arg.Direction,
		arg.AnchorID,
		arg.ProjectID,
		arg.RelationTypeID,
		arg.EntityTypeID,
		arg.Invalid,
		arg.AfterID,
		arg.AfterName,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityTypeID,
			&i.Key,
			&i.Name,
			&i.Fields,
			&i.Invalid,
			&i.Version,
			&i.Search,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityFieldsOfType = `-- name: ListEntityFieldsOfType :many
SELECT id, fields FROM entities
WHERE project_id = $1::uuid
  AND entity_type_id = $2::uuid
ORDER BY id
`

type ListEntityFieldsOfTypeParams struct {
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
}

type ListEntityFieldsOfTypeRow struct {
	ID     uuid.UUID
	Fields []byte
}

// The re-validation sweep reads nothing but the stored values and the id
// to flag, so it does not pay to load whole rows — a type can hold
// hundreds of entities and every schema edit sweeps all of them.
func (q *Queries) ListEntityFieldsOfType(ctx context.Context, arg ListEntityFieldsOfTypeParams) ([]ListEntityFieldsOfTypeRow, error) {
	rows, err := q.db.Query(ctx, listEntityFieldsOfType, arg.ProjectID, arg.EntityTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityFieldsOfTypeRow
	for rows.Next() {
		var i ListEntityFieldsOfTypeRow
		if err := rows.Scan(&i.ID, &i.Fields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityTypes = `-- name: ListEntityTypes :many
SELECT id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM entity_types
WHERE project_id = $1::uuid
ORDER BY label, id
`

// Ordered by label then id: labels are not unique, and a label-only order
// reshuffles ties between calls in whatever order Postgres returns them.
func (q *Queries) ListEntityTypes(ctx context.Context, projectID uuid.UUID) ([]EntityType, error) {
	rows, err := q.db.Query(ctx, listEntityTypes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityType
	for rows.Next() {
		var i EntityType
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.LabelPlural,
			&i.Description,
			&i.Color,
			&i.Icon,
			&i.FieldSchema,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationTypes = `-- name: ListRelationTypes :many
SELECT id, project_id, key, label, description, source_type_ids, target_type_ids, semantic_role, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM relation_types
WHERE project_id = $1::uuid ORDER BY label, id
`

// Ordered by label then id: labels are not unique, and a label-only
// order reshuffles ties between calls.
func (q *Queries) ListRelationTypes(ctx context.Context, projectID uuid.UUID) ([]RelationType, error) {
	rows, err := q.db.Query(ctx, listRelationTypes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationType
	for rows.Next() {
		var i RelationType
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.Description,
			&i.SourceTypeIds,
			&i.TargetTypeIds,
			&i.SemanticRole,
			&i.FieldSchema,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelations = `-- name: ListRelations :many
SELECT r.id, r.project_id, r.relation_type_id, r.source_id, r.target_id, r.fields, r.created_at, r.updated_at, r.updated_by_user_id, r.updated_by_token_id FROM relations r
WHERE r.project_id = $1::uuid
  AND ($2::uuid IS NULL OR r.relation_type_id = $2::uuid)
  AND ($3::uuid IS NULL OR r.source_id = $3::uuid)
  AND ($4::uuid IS NULL OR r.target_id = $4::uuid)
  AND ($5::uuid IS NULL
       OR (r.created_at, r.id) > ($6::timestamptz, $5::uuid))
ORDER BY r.created_at, r.id
LIMIT $7::int
`

type ListRelationsParams struct {
	ProjectID      uuid.UUID
	RelationTypeID *uuid.UUID
	SourceID       *uuid.UUID
	TargetID       *uuid.UUID
	AfterID        *uuid.UUID
	AfterCreatedAt pgtype.Timestamptz
	Limit          int32
}

// Every filter but the project is optional, and the project one is what
// keeps a leaked entity id from listing another game's edges: source_id
// and target_id are caller-supplied here, unlike the entity statements
// whose composite key already determines their project.
//
// The keyset is on (created_at, id), which is this listing's own sort
// order, and not on the (name, id) the entity listings use: relations
// have no name, and created_at is a value nothing edits, so a page
// boundary here cannot move under a rewrite the way a renamed entity's
// can. relations_project_idx is (project_id, created_at), so the
// position seeks rather than scans. Before it, the LIMIT alone made
// every edge past the cap unreachable with nothing in the answer saying
// so.
func (q *Queries) ListRelations(ctx context.Context, arg ListRelationsParams) ([]Relation, error) {
	rows, err := q.db.Query(ctx, listRelations,
		arg.ProjectID,
		arg.RelationTypeID,
		arg.SourceID,
		arg.TargetID,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relation
	for rows.Next() {
		var i Relation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RelationTypeID,
			&i.SourceID,
			&i.TargetID,
			&i.Fields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEndpointEntityTypes = `-- name: LockEndpointEntityTypes :many
SELECT id FROM entity_types
WHERE project_id = $1::uuid
  AND id = ANY ($2::uuid[])
FOR SHARE
`

type LockEndpointEntityTypesParams struct {
	ProjectID uuid.UUID
	Ids       []uuid.UUID
}

// Reads the entity types an endpoint rule names, and holds a share lock
// on each until the reading transaction ends.
//
// The read is what UpsertRelationType checks its endpoint lists against;
// the lock is what stops RemoveEntityType from deleting one of them
// underneath a relation type that is being created. Without it the
// creation path had no row for PruneEntityTypeFromEndpointLists to find
// and took no lock of its own, so a relation type created between the
// prune's statement and the removal's commit kept a dangling id. FOR
// SHARE and not FOR UPDATE: two writers may name the same entity type at
// once, and only a DELETE of it has to wait.
//
// **Lock order is load-bearing.** UpsertRelationType takes this lock
// before the FOR UPDATE on its own relation_types row, and
// RemoveEntityType deletes the entity type before pruning the relation
// types; both therefore take entity_types first, and neither can hold
// what the other is waiting for. Moving this call after the relation
// type's row lock reintroduces a deadlock between the two.
//
// **Two costs, measured and judged acceptable, recorded so a future
// reader does not have to re-measure them:**
//
//   - A long transaction holding this share lock blocks
//     RemoveEntityType against the same entity type indefinitely — there
//     is no default statement or lock timeout, so the deletion simply
//     parks until the holder commits, rolls back, or is killed. Removals
//     are rare and the alternative (letting the delete proceed and
//     leaving a dangling id) is worse, but the wait is unbounded; a
//     deployment that cares should set lock_timeout, and the caller then
//     meets the retryable failure this file's Go comments describe
//     rather than hanging.
//   - FOR SHARE here conflicts with the FOR UPDATE UpsertEntityType
//     takes on its own row (GetEntityTypeByKeyForUpdate below), so
//     declaring a relation type's endpoint rule over an entity type now
//     serialises against editing that same entity type's own row for as
//     long as the declaring transaction holds the lock. Measured at 200
//     relation-type declarations sharing six endpoint types: 251ms on a
//     single worker, 140ms spread across eight — no measured throughput
//     problem, and share locks do not conflict with each other, so
//     concurrent *declarations* over the same type are unaffected. Only
//     a concurrent *edit* of the entity type itself waits, and no
//     deadlock was found: entity_types is always locked before
//     relation_types on both paths (see above).
func (q *Queries) LockEndpointEntityTypes(ctx context.Context, arg LockEndpointEntityTypesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockEndpointEntityTypes, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEntitiesOfTypeInvalid = `-- name: MarkEntitiesOfTypeInvalid :exec
UPDATE entities SET invalid = $1::boolean
WHERE project_id = $2::uuid
  AND entity_type_id = $3::uuid
  AND id = ANY($4::uuid[])
  AND invalid <> $1::boolean
`

type MarkEntitiesOfTypeInvalidParams struct {
	Invalid      bool
	ProjectID    uuid.UUID
	EntityTypeID uuid.UUID
	Ids          []uuid.UUID
}

// The invalid <> flag guard keeps the sweep from rewriting rows whose
// verdict has not changed. Without it, every schema edit would touch each
// of the type's entities and the set_updated_at trigger would move their
// updated_at, so a validation pass would read as an edit of content
// nobody edited.
func (q *Queries) MarkEntitiesOfTypeInvalid(ctx context.Context, arg MarkEntitiesOfTypeInvalidParams) error {
	_, err := q.db.Exec(ctx, markEntitiesOfTypeInvalid,
		arg.Invalid,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Ids,
	)
	return err
}

const pruneEntityTypeFromEndpointLists = `-- name: PruneEntityTypeFromEndpointLists :many
UPDATE relation_types
SET source_type_ids = array_remove(source_type_ids, $1::uuid),
    target_type_ids = array_remove(target_type_ids, $1::uuid)
WHERE project_id = $2::uuid
  AND $1::uuid = ANY (source_type_ids || target_type_ids)
RETURNING id, key
`

type PruneEntityTypeFromEndpointListsParams struct {
	EntityTypeID uuid.UUID
	ProjectID    uuid.UUID
}

type PruneEntityTypeFromEndpointListsRow struct {
	ID  uuid.UUID
	Key string
}

// Removes a deleted entity type's id from every relation type's endpoint
// lists. source_type_ids and target_type_ids are plain uuid[]: Postgres
// has no foreign key from an array element, so nothing but this
// statement keeps them from outliving the type they name. It runs in the
// same transaction as the type's own delete.
//
// It returns the identity of every row it changed, because the caller
// announces them: this is a write to relation types nobody named, and a
// subscriber has no other way to learn its copy of an endpoint rule is
// stale. An UPDATE cannot order its RETURNING, so the caller sorts what
// comes back before announcing it: an unordered burst is a burst that
// arrives differently twice.
func (q *Queries) PruneEntityTypeFromEndpointLists(ctx context.Context, arg PruneEntityTypeFromEndpointListsParams) ([]PruneEntityTypeFromEndpointListsRow, error) {
	rows, err := q.db.Query(ctx, pruneEntityTypeFromEndpointLists, arg.EntityTypeID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PruneEntityTypeFromEndpointListsRow
	for rows.Next() {
		var i PruneEntityTypeFromEndpointListsRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEntities = `-- name: SearchEntities :many
SELECT e.id, e.project_id, e.entity_type_id, e.key, e.name, e.fields, e.invalid, e.version, e.search, e.created_at, e.updated_at, e.updated_by_user_id, e.updated_by_token_id, ts_rank(e.search, plainto_tsquery('simple', $1::text)) AS rank
FROM entities e
WHERE e.project_id = $2::uuid
  AND ($3::uuid IS NULL OR e.entity_type_id = $3::uuid)
  AND e.search @@ plainto_tsquery('simple', $1::text)
ORDER BY rank DESC, e.name, e.id
LIMIT $4::int
`

type SearchEntitiesParams struct {
	Query        string
	ProjectID    uuid.UUID
	EntityTypeID *uuid.UUID
	Limit        int32
}

type SearchEntitiesRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityTypeID     uuid.UUID
	Key              string
	Name             string
	Fields           []byte
	Invalid          bool
	Version          int32
	Search           pgtype.TSVector
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	Rank             float32
}

// Full-text search over a game's entities, ranked.
//
// The project filter is load-bearing: the query text is the caller's and
// names no parent, so nothing but this clause keeps a search inside one
// game.
//
// ORDER BY carries id after name for the reason ListEntityTypes records:
// neither rank nor name is unique, and an order that can tie reshuffles
// its ties between two identical calls.
//
// The tsquery is built twice, in the projection and in the predicate,
// because a WHERE cannot refer to an output column's alias. **The
// planner does not fold the two into one**, which this comment used to
// claim it did. Measured on this project's own Postgres, 200 evaluations
// of a non-constant plainto_tsquery: 0.63 ms each written once against
// 1.44 ms written twice at 4 KiB of query text, and 4.09 ms against
// 8.70 ms at 15 KiB. There is no common-subexpression elimination here;
// the second build costs what the first one did.
//
// It stays written twice anyway, now that MaxSearchQuery bounds the
// query at 4 KiB: the doubling is worth about 0.8 ms on the worst query
// this surface will accept, and it was only ever alarming while the
// query side was unbounded. The obvious way to build it once, a
// `WITH q AS MATERIALIZED (SELECT plainto_tsquery(...) AS ts)` joined
// in, was measured too. It keeps the Bitmap Index Scan on
// entities_search_idx, so it is not wrong, but the tsquery stops being a
// constant the planner can see, and its row estimate for the match went
// from 5 (exact) to 100 (a default guess) on the same data. Trading a
// correct selectivity estimate on every search for 0.8 ms on the largest
// accepted query is the wrong way round; whoever raises MaxSearchQuery
// should measure both again.
func (q *Queries) SearchEntities(ctx context.Context, arg SearchEntitiesParams) ([]SearchEntitiesRow, error) {
	rows, err := q.db.Query(ctx, searchEntities,
		arg.Query,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchEntitiesRow
	for rows.Next() {
		var i SearchEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityTypeID,
			&i.Key,
			&i.Name,
			&i.Fields,
			&i.Invalid,
			&i.Version,
			&i.Search,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (project_id, entity_type_id, key, name, fields, search,
                      updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::uuid,
        $3::text, $4::text, $5::jsonb,
        setweight(to_tsvector('simple', $4::text), 'A')
          || setweight(to_tsvector('simple', $4::text || ' ' || $6::text), 'B'),
        $7::uuid, $8::uuid)
ON CONFLICT (project_id, entity_type_id, lower(key)) DO UPDATE
SET name                = excluded.name,
    fields              = excluded.fields,
    search              = excluded.search,
    invalid             = false,
    version             = entities.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE entities.version = $9::integer
RETURNING id, project_id, entity_type_id, key, name, fields, invalid, version, search, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertEntityParams struct {
	ProjectID        uuid.UUID
	EntityTypeID     uuid.UUID
	Key              string
	Name             string
	Fields           []byte
	SearchText       string
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// The same shape as UpsertEntityType, for the same reasons, and that
// statement's comment carries the full argument. In short:
//
//   - The DO UPDATE is guarded by the caller's expected version, so the
//     whole compare-and-set is one statement and two writers cannot both
//     read version 1 and both succeed. A creating caller passes
//     noVersion, which no stored version can equal.
//   - The key column is deliberately not in the SET list. The first
//     spelling stored stands, and the returned row therefore still
//     carries it -- which is what lets Go refuse a respelling *after* the
//     write, closing the creation-race hole.
//   - No write sets updated_at: 0004_metamodel.sql puts a set_updated_at
//     trigger on all four tables, and a clause here would be a second
//     mechanism behind one column.
//   - The audit columns are carried, so the composite
//     FOREIGN KEY (updated_by_token_id, project_id) catches a token
//     scoped to another game.
//
// search is written by this statement and by nothing else, on both arms
// of the upsert. **It is weighted**: the name goes in twice, once alone
// under label A and once as the head of the whole text under label B, so
// that ts_rank puts a row the query names above a row that merely
// mentions the word. 0006_weighted_entity_search.sql records why the B
// half carries the name rather than the fields alone — it is what makes
// that migration's backfill an exact function of the vector this
// statement used to write, so a migrated row and a re-seeded row rank
// the same. It cannot be a generated column: it is derived from
// user-declared jsonb whose *text* fields are the only ones worth
// indexing, and which of a row's fields those are is known only to the
// Go validator that has just read the type's schema. So every write path
// that changes name or fields must come through here, or the row stays
// indexed under its previous words and a search stops finding it with
// nothing to signal why.
//
// invalid is reset to false because the caller has just validated these
// values against the type's current schema; a row that is being written
// is a row that has been judged.
func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.ProjectID,
		arg.EntityTypeID,
		arg.Key,
		arg.Name,
		arg.Fields,
		arg.SearchText,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityTypeID,
		&i.Key,
		&i.Name,
		&i.Fields,
		&i.Invalid,
		&i.Version,
		&i.Search,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertEntityType = `-- name: UpsertEntityType :one
INSERT INTO entity_types (project_id, key, label, label_plural, description, color, icon,
                          field_schema, updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::text,
        $6::text, $7::text, $8::jsonb,
        $9::uuid, $10::uuid)
ON CONFLICT (project_id, lower(key)) DO UPDATE
SET label               = excluded.label,
    label_plural        = excluded.label_plural,
    description         = excluded.description,
    color               = excluded.color,
    icon                = excluded.icon,
    field_schema        = excluded.field_schema,
    version             = entity_types.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE entity_types.version = $11::integer
RETURNING id, project_id, key, label, label_plural, description, color, icon, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertEntityTypeParams struct {
	ProjectID        uuid.UUID
	Key              string
	Label            string
	LabelPlural      string
	Description      string
	Color            string
	Icon             string
	FieldSchema      []byte
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// Every statement in this file carries the resolved project id -- the
// reads and deletes as a filter, including the ones addressing a row by
// its primary key, and the upserts as the column they write. Isolation
// between games is enforced in SQL, not in Go, so a query trusting an id
// alone would hand a caller another game's row the moment an id leaked.
//
// That is the whole mechanism only for the statements addressing a row
// by its own primary key: GetEntityTypeByID and DeleteEntityType, which
// TestTypesAreScopedToTheirProject pins, and GetEntityByID and
// DeleteEntity, which
// TestTheEntityQueriesThatAddressARowByIDAreScopedToTheProject pins.
// Drop the filter from any of the four and a leaked id reads, or
// deletes, another game's row. The entity pair needed a test of its own
// against the queries: their only caller is RemoveEntity, which reads
// the row, then its type, then deletes, so each of its three filters
// masks the others and only mutating all three at once is observable
// through the service.
//
// It is *not* the mechanism for the statements reaching entities through
// an entity_type_id (ListEntityFieldsOfType, MarkEntitiesOfTypeInvalid,
// DeleteEntitiesOfType, GetEntityByKey, GetEntityByKeyForUpdate).
// 0004_metamodel.sql gives entities a composite
// FOREIGN KEY (entity_type_id, project_id) REFERENCES
// entity_types (id, project_id), so an entity's project is already
// determined by its type's: no row can match a type id under one project
// id and not another, and dropping the filter from any of those five
// changes no result and can be caught by no test. They keep it as
// defence in depth, against a future schema that relaxes that composite
// key, and so that a
// reader adding the next entities query copies the safe shape rather than
// having to work out which statements happen to be covered by a
// constraint. Written down here because a comment claiming these filters
// are what isolates games would be relied on as if it were true.
//
// UpsertEntity is deliberately not in that list, and is not unobservable
// either: it has no project filter at all. Its project_id is a NOT NULL
// column value it writes and part of its ON CONFLICT
// (project_id, entity_type_id, lower(key)) target, so removing it is a
// syntax or constraint error rather than a silently widened query --
// nothing about it can be dropped and still compile.
//
// No write here sets updated_at. 0004_metamodel.sql puts a set_updated_at
// trigger on all four tables, so the column has one mechanism behind it
// rather than a trigger plus a clause every future query must remember.
//
// The DO UPDATE is guarded by the caller's expected version, so the whole
// compare-and-set happens in one statement and two concurrent writers
// cannot both read version 1 and both succeed. A creating caller has no
// version to expect and passes noVersion, which no stored version can
// equal, so the guard is a no-op on the insert path and a guaranteed
// mismatch when a row it did not know about turns out to exist. A guard
// that fails returns no row rather than an error; UpsertEntityType turns
// that into the typed conflict.
//
// Idempotent by (project, key), matched case-insensitively through the
// entity_types_key_key index. The key column itself is deliberately not in
// the SET list: the first spelling stored stays, so a re-seed cannot
// rewrite the handle other rows and documents refer to. That omission is
// also what lets UpsertEntityType in Go refuse a respelling *after* this
// statement runs: the row returned still carries the stored key, so
// comparing it to the submitted one catches a writer whose own locked read
// could not have seen this row at all — a creation racing a creator, where
// there was nothing yet to lock. So this clause is what makes an identical
// spelling a no-op; it is not what resolves a conflict.
func (q *Queries) UpsertEntityType(ctx context.Context, arg UpsertEntityTypeParams) (EntityType, error) {
	row := q.db.QueryRow(ctx, upsertEntityType,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.LabelPlural,
		arg.Description,
		arg.Color,
		arg.Icon,
		arg.FieldSchema,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.LabelPlural,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertRelation = `-- name: UpsertRelation :one
INSERT INTO relations (project_id, relation_type_id, source_id, target_id, fields,
                       updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::uuid,
        $3::uuid, $4::uuid, $5::jsonb,
        $6::uuid, $7::uuid)
ON CONFLICT (relation_type_id, source_id, target_id) DO UPDATE
SET fields              = excluded.fields,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
RETURNING id, project_id, relation_type_id, source_id, target_id, fields, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertRelationParams struct {
	ProjectID        uuid.UUID
	RelationTypeID   uuid.UUID
	SourceID         uuid.UUID
	TargetID         uuid.UUID
	Fields           []byte
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

// No version guard, because relations carry no version column: an edge
// is identified by (type, source, target) and re-writing its fields is
// the operation, not a lost update. Two writers editing one edge's
// fields therefore both succeed and the last one wins, which is this
// table's documented concurrency behaviour and not an oversight -- see
// RelationInput.
//
// The ON CONFLICT target is relations_edge_key, so a re-seed of the same
// edge updates it rather than laying a second copy beside it. That is
// also why a game cannot hold two edges of one type between one ordered
// pair; UpsertRelation's doc comment says what to do when it genuinely
// needs to.
//
// No updated_at either -- the set_updated_at trigger owns that column on
// all four tables. project_id is the column this statement writes rather
// than a filter it applies, exactly as in UpsertEntity, and the
// composite foreign keys on the type and both endpoints are what keep an
// edge inside one game.
func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) (Relation, error) {
	row := q.db.QueryRow(ctx, upsertRelation,
		arg.ProjectID,
		arg.RelationTypeID,
		arg.SourceID,
		arg.TargetID,
		arg.Fields,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
	)
	var i Relation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RelationTypeID,
		&i.SourceID,
		&i.TargetID,
		&i.Fields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const upsertRelationType = `-- name: UpsertRelationType :one
INSERT INTO relation_types (project_id, key, label, description,
                            source_type_ids, target_type_ids, semantic_role, field_schema,
                            updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::uuid[],
        $6::uuid[], $7::text,
        $8::jsonb,
        $9::uuid, $10::uuid)
ON CONFLICT (project_id, lower(key)) DO UPDATE
SET label               = excluded.label,
    description         = excluded.description,
    source_type_ids     = excluded.source_type_ids,
    target_type_ids     = excluded.target_type_ids,
    semantic_role       = excluded.semantic_role,
    field_schema        = excluded.field_schema,
    version             = relation_types.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE relation_types.version = $11::integer
RETURNING id, project_id, key, label, description, source_type_ids, target_type_ids, semantic_role, field_schema, version, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertRelationTypeParams struct {
	ProjectID        uuid.UUID
	Key              string
	Label            string
	Description      string
	SourceTypeIds    []uuid.UUID
	TargetTypeIds    []uuid.UUID
	SemanticRole     *string
	FieldSchema      []byte
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// Guarded, audited and trigger-owned exactly as UpsertEntityType is; see
// that statement's comment for the full argument. In short: the DO UPDATE
// carries the caller's expected version so the compare-and-set is one
// statement, no write sets updated_at because the set_updated_at trigger
// owns it, and key is not in the SET list, so the stored spelling stands
// and the returned row is what lets Go refuse a respelling after the
// write.
func (q *Queries) UpsertRelationType(ctx context.Context, arg UpsertRelationTypeParams) (RelationType, error) {
	row := q.db.QueryRow(ctx, upsertRelationType,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.Description,
		arg.SourceTypeIds,
		arg.TargetTypeIds,
		arg.SemanticRole,
		arg.FieldSchema,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i RelationType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.SourceTypeIds,
		&i.TargetTypeIds,
		&i.SemanticRole,
		&i.FieldSchema,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}
