// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID
	TokenHash  []byte
	ProjectID  uuid.UUID
	UserID     uuid.UUID
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	TokenHint  string
}

type Entity struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityTypeID     uuid.UUID
	Key              string
	Name             string
	Fields           []byte
	Invalid          bool
	Version          int32
	Search           pgtype.TSVector
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type EntityType struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Key              string
	Label            string
	LabelPlural      string
	Description      string
	Color            string
	Icon             string
	FieldSchema      []byte
	Version          int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type Invite struct {
	ID         uuid.UUID
	TokenHash  []byte
	Email      *string
	ProjectID  *uuid.UUID
	Role       *string
	CreatedBy  *uuid.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	RedeemedBy *uuid.UUID
}

type Membership struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Relation struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	RelationTypeID   uuid.UUID
	SourceID         uuid.UUID
	TargetID         uuid.UUID
	Fields           []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type RelationType struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Key              string
	Label            string
	Description      string
	SourceTypeIds    []uuid.UUID
	TargetTypeIds    []uuid.UUID
	SemanticRole     *string
	FieldSchema      []byte
	Version          int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
