// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID
	TokenHash  []byte
	ProjectID  uuid.UUID
	UserID     uuid.UUID
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Invite struct {
	ID         uuid.UUID
	TokenHash  []byte
	Email      *string
	ProjectID  *uuid.UUID
	Role       *string
	CreatedBy  *uuid.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	RedeemedBy *uuid.UUID
}

type Membership struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
