// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID
	TokenHash  []byte
	ProjectID  uuid.UUID
	UserID     uuid.UUID
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	TokenHint  string
}

type Document struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Path             string
	Kind             string
	Title            string
	Summary          string
	BodyMd           string
	Frontmatter      []byte
	CurrentVersion   int32
	DeletedAt        pgtype.Timestamptz
	Search           pgtype.TSVector
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type DocumentLink struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	DocumentID uuid.UUID
	EntityID   uuid.UUID
	Role       string
	CreatedAt  pgtype.Timestamptz
}

type DocumentVersion struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	DocumentID    uuid.UUID
	Version       int32
	Title         string
	Summary       string
	BodyMd        string
	Frontmatter   []byte
	Message       string
	Deleted       bool
	AuthorUserID  *uuid.UUID
	AuthorTokenID *uuid.UUID
	CreatedAt     pgtype.Timestamptz
	Path          string
}

type Entity struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	EntityTypeID     uuid.UUID
	Key              string
	Name             string
	Fields           []byte
	Invalid          bool
	Version          int32
	Search           pgtype.TSVector
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type EntityType struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Key              string
	Label            string
	LabelPlural      string
	Description      string
	Color            string
	Icon             string
	FieldSchema      []byte
	Version          int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
}

type Invite struct {
	ID         uuid.UUID
	TokenHash  []byte
	Email      *string
	ProjectID  *uuid.UUID
	Role       *string
	CreatedBy  *uuid.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	RedeemedBy *uuid.UUID
}

type Membership struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID            uuid.UUID
	Slug          string
	Name          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DesignVersion int64
}

type Relation struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	RelationTypeID   uuid.UUID
	SourceID         uuid.UUID
	TargetID         uuid.UUID
	Fields           []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	Invalid          bool
	Version          int32
}

type RelationType struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Key              string
	Label            string
	Description      string
	SourceTypeIds    []uuid.UUID
	TargetTypeIds    []uuid.UUID
	SemanticRole     *string
	FieldSchema      []byte
	Version          int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	AnalysisTraits   []string
}

type Route struct {
	ID                       uuid.UUID
	ProjectID                uuid.UUID
	Key                      string
	Name                     string
	Description              string
	Params                   []byte
	Version                  int32
	LastCheckedAt            pgtype.Timestamptz
	LastCheckedDesignVersion *int64
	LastCheck                []byte
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	UpdatedByUserID          *uuid.UUID
	UpdatedByTokenID         *uuid.UUID
}

type RouteStep struct {
	RouteID       uuid.UUID
	ProjectID     uuid.UUID
	Position      int32
	EntityID      *uuid.UUID
	EntityTypeKey string
	EntityKey     string
	Note          string
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type View struct {
	ID                uuid.UUID
	ProjectID         uuid.UUID
	Key               string
	Name              string
	Description       string
	Query             []byte
	Renderer          string
	RendererParams    []byte
	LayoutMode        string
	BackgroundAssetID *uuid.UUID
	BackgroundScale   float64
	BackgroundOffset  []byte
	Version           int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	UpdatedByUserID   *uuid.UUID
	UpdatedByTokenID  *uuid.UUID
}

type ViewAsset struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Filename         string
	Mime             string
	Width            int32
	Height           int32
	Bytes            []byte
	CreatedAt        pgtype.Timestamptz
	CreatedByUserID  *uuid.UUID
	CreatedByTokenID *uuid.UUID
}

type ViewPosition struct {
	ViewID    uuid.UUID
	EntityID  uuid.UUID
	ProjectID uuid.UUID
	X         float64
	Y         float64
	Pinned    bool
	UpdatedAt pgtype.Timestamptz
}

type ViewRef struct {
	ViewID         uuid.UUID
	ProjectID      uuid.UUID
	Kind           string
	RefKey         string
	EntityTypeID   *uuid.UUID
	RelationTypeID *uuid.UUID
	Pointer        string
}
