// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const countOwnersForUpdate = `-- name: CountOwnersForUpdate :one
SELECT count(*) FROM (
    SELECT 1 FROM memberships
    WHERE project_id = $1::uuid AND role = 'owner'
    FOR UPDATE
) owners
`

// Locks every owner row of the project before counting, so that SetRole
// and RemoveMember (both of which call this from inside a transaction
// before demoting or deleting an owner) serialize against any other
// concurrent call doing the same thing for the same project. FOR UPDATE
// cannot be combined directly with an aggregate, hence the subquery: the
// lock is taken in the inner SELECT, the count happens in the outer one.
// Under READ COMMITTED, a blocked transaction that unblocks re-checks the
// WHERE clause against the row's latest committed version, so a row
// demoted away from 'owner' by the transaction that held the lock is
// correctly excluded from the count the next transaction sees.
//
// This lock is deliberate defence in depth, not the only thing standing
// between two concurrent callers and a zero-owner project: migration
// 0002's constraint trigger enforces the identical invariant
// independently, re-checked at commit time regardless of whether this
// lock is taken at all, and a quality review confirmed it alone already
// serializes the two-goroutine race projects_test.go's
// TestConcurrentRemovalLeavesExactlyOneOwner drives — stripping this
// FOR UPDATE and running that test roughly eighty times produced no
// failures. What this lock earns on its own is SetRole/RemoveMember
// failing fast with a typed ErrLastOwner instead of the transaction
// aborting on a raw trigger exception; see that test's own comment for
// the fuller version of this note.
func (q *Queries) CountOwnersForUpdate(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersForUpdate, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name)
VALUES ($1::text, $2::text)
RETURNING id, slug, name, created_at, updated_at
`

type CreateProjectParams struct {
	Slug string
	Name string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Slug, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE user_id = $1::uuid AND project_id = $2::uuid
`

type DeleteMembershipParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.ProjectID)
	return err
}

const getMembershipRole = `-- name: GetMembershipRole :one
SELECT role FROM memberships
WHERE user_id = $1::uuid AND project_id = $2::uuid
`

type GetMembershipRoleParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembershipRole, arg.UserID, arg.ProjectID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, created_at, updated_at FROM projects WHERE id = $1::uuid
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, created_at, updated_at FROM projects WHERE lower(slug) = lower($1::text)
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.display_name, m.role
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1::uuid
ORDER BY u.display_name, u.id
`

type ListMembersRow struct {
	ID          uuid.UUID
	DisplayName string
	Role        string
}

// No u.email: ListMembers is authorization-free by design (see
// projects.ListMembers's own doc comment), so every caller holding a
// Member holds whatever this query returns, including a viewer with no
// business reading a teammate's email. display_name, id and role are what
// a member list renders; an owner-only contact-details view, if the
// product ever wants one, is a separate query added deliberately rather
// than this one growing a field most callers should not see.
// Ordered by display_name then id, for the same tiebreak reason as
// ListProjectsForUser above: display names are not unique.
func (q *Queries) ListMembers(ctx context.Context, projectID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.slug, p.name, p.created_at, p.updated_at FROM projects p
JOIN memberships m ON m.project_id = p.id
WHERE m.user_id = $1::uuid
ORDER BY p.name, p.id
`

// Ordered by name then id: name alone is not unique (two games can both
// be called "Untitled"), so a name-only order reshuffles ties between
// calls in whatever order Postgres happens to return them. id, being a
// primary key, is always unique, so appending it as a tiebreak makes the
// order stable across repeated calls with identical input.
func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
