// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const deleteView = `-- name: DeleteView :execrows
DELETE FROM views
WHERE project_id = $1::uuid AND id = $2::uuid
`

type DeleteViewParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// The positions and the refs go with it: both key into views with
// ON DELETE CASCADE (0008_views.sql), so this is one statement rather
// than three. execrows, not exec, because zero rows is the answer to
// "was it there" — a caller that resolved the view a moment earlier and
// deletes nothing raced another remover, and hears not_found instead of
// a success it can publish an event about.
func (q *Queries) DeleteView(ctx context.Context, arg DeleteViewParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteView, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteViewRefs = `-- name: DeleteViewRefs :exec
DELETE FROM view_refs
WHERE project_id = $1::uuid AND view_id = $2::uuid
`

type DeleteViewRefsParams struct {
	ProjectID uuid.UUID
	ViewID    uuid.UUID
}

// Half of the rewrite an upsert performs; InsertViewRef is the other.
// Both run inside the upsert's own transaction, because refs that are
// rewritten outside it drift from the query they index, which is the one
// thing they exist not to do.
func (q *Queries) DeleteViewRefs(ctx context.Context, arg DeleteViewRefsParams) error {
	_, err := q.db.Exec(ctx, deleteViewRefs, arg.ProjectID, arg.ViewID)
	return err
}

const getViewByID = `-- name: GetViewByID :one
SELECT id, project_id, key, name, description, query, renderer, renderer_params, layout_mode, layout_seed, background_asset_id, background_scale, background_offset, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM views
WHERE project_id = $1::uuid AND id = $2::uuid
`

type GetViewByIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// The project filter is the whole mechanism here: an id is a value a
// previous answer handed back and names no parent that could scope this
// statement. Drop it and a leaked id reads another game's view.
func (q *Queries) GetViewByID(ctx context.Context, arg GetViewByIDParams) (View, error) {
	row := q.db.QueryRow(ctx, getViewByID, arg.ProjectID, arg.ID)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Renderer,
		&i.RendererParams,
		&i.LayoutMode,
		&i.LayoutSeed,
		&i.BackgroundAssetID,
		&i.BackgroundScale,
		&i.BackgroundOffset,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getViewByKey = `-- name: GetViewByKey :one
SELECT id, project_id, key, name, description, query, renderer, renderer_params, layout_mode, layout_seed, background_asset_id, background_scale, background_offset, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM views
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
`

type GetViewByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

// Matched without regard to case, through views_key_key
// (project_id, lower(key)), so a caller that reads with one spelling and
// writes with another meets one row rather than two.
func (q *Queries) GetViewByKey(ctx context.Context, arg GetViewByKeyParams) (View, error) {
	row := q.db.QueryRow(ctx, getViewByKey, arg.ProjectID, arg.Key)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Renderer,
		&i.RendererParams,
		&i.LayoutMode,
		&i.LayoutSeed,
		&i.BackgroundAssetID,
		&i.BackgroundScale,
		&i.BackgroundOffset,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const getViewByKeyForUpdate = `-- name: GetViewByKeyForUpdate :one
SELECT id, project_id, key, name, description, query, renderer, renderer_params, layout_mode, layout_seed, background_asset_id, background_scale, background_offset, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM views
WHERE project_id = $1::uuid AND lower(key) = lower($2::text)
FOR UPDATE
`

type GetViewByKeyForUpdateParams struct {
	ProjectID uuid.UUID
	Key       string
}

// The upsert's own read, taken inside its transaction with the row lock
// held, so the spelling and the version a caller is told about are the
// ones its own write will actually meet. Without the lock the read runs
// against the transaction's snapshot, and a caller racing an in-flight
// edit is told to merge onto a version that is already stale by the time
// it retries. What the lock buys is not the refusal — the guarded DO
// UPDATE refuses on its own — but the *number* the caller is told to
// merge onto: TestTheReportedCurrentViewVersionIsTheOneTheWriteWouldHaveMet
// pins exactly that.
func (q *Queries) GetViewByKeyForUpdate(ctx context.Context, arg GetViewByKeyForUpdateParams) (View, error) {
	row := q.db.QueryRow(ctx, getViewByKeyForUpdate, arg.ProjectID, arg.Key)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Renderer,
		&i.RendererParams,
		&i.LayoutMode,
		&i.LayoutSeed,
		&i.BackgroundAssetID,
		&i.BackgroundScale,
		&i.BackgroundOffset,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}

const insertViewRef = `-- name: InsertViewRef :exec
INSERT INTO view_refs (view_id, project_id, kind, ref_key, entity_type_id,
                       relation_type_id, pointer)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::uuid,
        $6::uuid, $7::text)
`

type InsertViewRefParams struct {
	ViewID         uuid.UUID
	ProjectID      uuid.UUID
	Kind           string
	RefKey         string
	EntityTypeID   *uuid.UUID
	RelationTypeID *uuid.UUID
	Pointer        string
}

// One reference from a query to a declared type, at the JSON pointer
// that addresses it.
//
// **A plain INSERT, with no ON CONFLICT arm, deliberately.** A pointer
// addresses exactly one position in one document, so two rows for one
// pointer would be a rewrite that did not delete the first;
// view_refs_key is UNIQUE (view_id, pointer) and 0008_views.sql records
// that the index exists to make that a refusal rather than a silent
// duplicate. Swallowing it here would put the silence back.
//
// kind says which of the two id columns the row uses and the table's own
// CHECK refuses a row that claims one kind and carries the other's id,
// so Go passes a null for the column the kind does not name.
func (q *Queries) InsertViewRef(ctx context.Context, arg InsertViewRefParams) error {
	_, err := q.db.Exec(ctx, insertViewRef,
		arg.ViewID,
		arg.ProjectID,
		arg.Kind,
		arg.RefKey,
		arg.EntityTypeID,
		arg.RelationTypeID,
		arg.Pointer,
	)
	return err
}

const listViewRefs = `-- name: ListViewRefs :many
SELECT view_id, project_id, kind, ref_key, entity_type_id, relation_type_id, pointer FROM view_refs
WHERE project_id = $1::uuid AND view_id = $2::uuid
ORDER BY pointer
`

type ListViewRefsParams struct {
	ProjectID uuid.UUID
	ViewID    uuid.UUID
}

// One view's dependency list, in document order. The sort is the pointer
// rather than the insertion order because a table has no insertion
// order, and a staleness report that listed one query's broken
// references in an order Postgres chose would move about between calls.
func (q *Queries) ListViewRefs(ctx context.Context, arg ListViewRefsParams) ([]ViewRef, error) {
	rows, err := q.db.Query(ctx, listViewRefs, arg.ProjectID, arg.ViewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ViewRef
	for rows.Next() {
		var i ViewRef
		if err := rows.Scan(
			&i.ViewID,
			&i.ProjectID,
			&i.Kind,
			&i.RefKey,
			&i.EntityTypeID,
			&i.RelationTypeID,
			&i.Pointer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsBrokenByType = `-- name: ListViewsBrokenByType :many
SELECT v.id, v.key, v.name, r.kind, r.ref_key, r.pointer
FROM view_refs r
JOIN views v ON v.id = r.view_id AND v.project_id = r.project_id
WHERE r.project_id = $1::uuid
  AND v.project_id = $1::uuid
  AND (($2::uuid IS NOT NULL
        AND r.entity_type_id = $2::uuid)
    OR ($3::uuid IS NOT NULL
        AND r.relation_type_id = $3::uuid))
ORDER BY v.name, v.id, r.pointer
`

type ListViewsBrokenByTypeParams struct {
	ProjectID      uuid.UUID
	EntityTypeID   *uuid.UUID
	RelationTypeID *uuid.UUID
}

type ListViewsBrokenByTypeRow struct {
	ID      uuid.UUID
	Key     string
	Name    string
	Kind    string
	RefKey  string
	Pointer string
}

// "Which views does this type hold up, and where in each query" — the
// lookup ON DELETE SET NULL on view_refs exists to serve, and the reason
// that column is nullable rather than cascading.
//
// **It is asked with the type's id, so it must be asked before the type
// is deleted**, inside the deleting transaction: the SET NULL is what
// makes the row survive its type, and it also empties the column this
// statement matches on. Asking afterwards finds nothing and reports that
// nothing broke, which is the wrong answer rather than an error. Task 12
// is the caller that reports the list in a deletion's answer.
//
// One of the two arguments is set and the other is null: an entity type
// and a relation type are different vocabularies and a call naming both
// would be asking two questions. view_refs_entity_type_idx and
// view_refs_relation_type_idx are (project_id, entity_type_id) and
// (project_id, relation_type_id), so each arm is an index lookup rather
// than a scan over every stored query document, which is the whole point
// of the table.
func (q *Queries) ListViewsBrokenByType(ctx context.Context, arg ListViewsBrokenByTypeParams) ([]ListViewsBrokenByTypeRow, error) {
	rows, err := q.db.Query(ctx, listViewsBrokenByType, arg.ProjectID, arg.EntityTypeID, arg.RelationTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListViewsBrokenByTypeRow
	for rows.Next() {
		var i ListViewsBrokenByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Kind,
			&i.RefKey,
			&i.Pointer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsPage = `-- name: ListViewsPage :many
SELECT id, project_id, key, name, description, query, renderer, renderer_params, layout_mode, layout_seed, background_asset_id, background_scale, background_offset, version, created_at, updated_at, updated_by_user_id, updated_by_token_id FROM views
WHERE project_id = $1::uuid
  AND ($2::text IS NULL OR renderer = $2::text)
  AND ($3::uuid IS NULL
       OR (name, id) > ($4::text, $3::uuid))
ORDER BY name, id
LIMIT $5::int
`

type ListViewsPageParams struct {
	ProjectID uuid.UUID
	Renderer  *string
	AfterID   *uuid.UUID
	AfterName *string
	Limit     int32
}

// One page of a game's saved views, keyed on (name, id).
//
// views_project_idx, added in 0008, is (project_id, name, id): this
// statement's filter and its whole sort key, so the position a cursor
// carries is sought to rather than arrived at by sorting the game.
//
// **The project filter is load-bearing.** The after_name/after_id
// position is caller-supplied and names no parent whose composite key
// could scope this statement, and the renderer filter is free text off
// the same caller. Drop the project filter and a caller pages another
// game's rows.
//
// The keyset compares uuid to uuid rather than casting id to text, and
// `id` is in the ORDER BY as well as in the comparison, for the reasons
// ListEntitiesPage's own comment sets out at length: a keyset whose
// comparison disagrees with its own sort order skips or repeats rows at
// a page boundary and says nothing, and view names are as duplicable as
// entity names. after_id alone guards the clause, and after_name is read
// only when it is set, because a row comparison against a NULL half
// yields NULL, which reads as false and would answer with an empty page
// rather than a refusal.
func (q *Queries) ListViewsPage(ctx context.Context, arg ListViewsPageParams) ([]View, error) {
	rows, err := q.db.Query(ctx, listViewsPage,
		arg.ProjectID,
		arg.Renderer,
		arg.AfterID,
		arg.AfterName,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Renderer,
			&i.RendererParams,
			&i.LayoutMode,
			&i.LayoutSeed,
			&i.BackgroundAssetID,
			&i.BackgroundScale,
			&i.BackgroundOffset,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.UpdatedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertView = `-- name: UpsertView :one

INSERT INTO views (project_id, key, name, description, query, renderer, renderer_params,
                   layout_mode, layout_seed, updated_by_user_id, updated_by_token_id)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::jsonb,
        $6::text, $7::jsonb,
        $8::text, $9::integer,
        $10::uuid, $11::uuid)
ON CONFLICT (project_id, lower(key)) DO UPDATE
SET name                = excluded.name,
    description         = excluded.description,
    query               = excluded.query,
    renderer            = excluded.renderer,
    renderer_params     = excluded.renderer_params,
    layout_mode         = excluded.layout_mode,
    layout_seed         = excluded.layout_seed,
    version             = views.version + 1,
    updated_by_user_id  = excluded.updated_by_user_id,
    updated_by_token_id = excluded.updated_by_token_id
WHERE views.version = $12::integer
RETURNING id, project_id, key, name, description, query, renderer, renderer_params, layout_mode, layout_seed, background_asset_id, background_scale, background_offset, version, created_at, updated_at, updated_by_user_id, updated_by_token_id
`

type UpsertViewParams struct {
	ProjectID        uuid.UUID
	Key              string
	Name             string
	Description      string
	Query            []byte
	Renderer         string
	RendererParams   []byte
	LayoutMode       string
	LayoutSeed       int32
	UpdatedByUserID  *uuid.UUID
	UpdatedByTokenID *uuid.UUID
	ExpectedVersion  int32
}

// Every statement in this file carries the resolved project id: the
// reads and the delete as a filter, the writes as the column they set.
// Isolation between games is enforced in SQL, not in Go, so a query
// trusting a key or an id alone would hand a caller another game's view
// the moment one leaked.
//
// Which filters are load-bearing, stated rather than implied, because
// 0008_views.sql's composite foreign keys cover some of these tables and
// a comment claiming every filter here is what isolates games would be
// relied on as if it were true:
//
//   - On views, every one of them is. A key is caller-supplied and names
//     no parent, and a view id is a value a previous answer handed back,
//     so nothing but the project filter keeps either inside one game.
//     That includes GetViewByID: a view id in a caller's hand is not
//     authority to read it. TestReadingAnotherGamesViewIsNotFound pins
//     both, by key and by id, with a positive control in the same test.
//   - On view_refs, the filter is **not** the mechanism and is defence
//     in depth. 0008_views.sql gives the table a composite
//     FOREIGN KEY (view_id, project_id) REFERENCES views (id, project_id),
//     so a ref row's project is already determined by its view's and no
//     row can match a view id under one project id and not another.
//     Dropping the filter from DeleteViewRefs, InsertViewRef or
//     ListViewRefs changes no result and can be caught by no test — the
//     same position internal/db/queries/metamodel.sql records for the
//     statements that reach entities through an entity_type_id. It stays
//     against a future schema that relaxes that key, and so that whoever
//     adds the next view_refs query copies the safe shape rather than
//     working out which statements happen to be covered by a constraint.
//     InsertViewRef writes project_id as a column value, which is what
//     makes the composite key check anything at all.
//
// No write here sets updated_at. 0008_views.sql puts a set_updated_at
// trigger on views, so the column has one mechanism behind it rather
// than a trigger plus a clause every future query must remember.
// The compare-and-set, in one statement, exactly as UpsertEntityType and
// UpsertDocument do it; those statements' comments carry the full
// argument and it is not restated here. In short: the DO UPDATE is
// guarded by the caller's expected version, so two writers cannot both
// read version 1 and both succeed, and a guard that matches nothing
// returns no row rather than an error, which Go turns into the typed
// conflict. A creating caller passes noVersion (-1), which no stored
// version can equal.
//
// **key is deliberately not in the SET list**, for the reason
// UpsertEntityType gives: the first spelling stored stands, so a re-seed
// cannot rewrite the handle a designer bookmarks, and the row this
// statement returns still carries the stored spelling — which is what
// lets Go refuse a respelling *after* the write, closing the
// creation-races-a-creation hole its locked read cannot see.
//
// **The three background columns are not in the SET list either, and
// that is a decision rather than an omission.** A background is written
// by views.set_background (the views plan, Task 14) and belongs to the
// picture rather than to the query; listing them here would make every
// ordinary edit of a query or a renderer parameter silently detach the
// world map a designer put behind it, because a caller that says nothing
// about a background would be saying "none". The same distinction
// markdown's WriteInput.Links draws with a pointer, drawn here by the
// column simply not being writable from this path.
func (q *Queries) UpsertView(ctx context.Context, arg UpsertViewParams) (View, error) {
	row := q.db.QueryRow(ctx, upsertView,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.Renderer,
		arg.RendererParams,
		arg.LayoutMode,
		arg.LayoutSeed,
		arg.UpdatedByUserID,
		arg.UpdatedByTokenID,
		arg.ExpectedVersion,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Renderer,
		&i.RendererParams,
		&i.LayoutMode,
		&i.LayoutSeed,
		&i.BackgroundAssetID,
		&i.BackgroundScale,
		&i.BackgroundOffset,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.UpdatedByTokenID,
	)
	return i, err
}
