package web

import (
	"fmt"
	"sort"
	"strings"

	"github.com/neverbot/maestro/internal/analysis"
	"github.com/neverbot/maestro/internal/config"
	"github.com/neverbot/maestro/internal/identity"
	"github.com/neverbot/maestro/internal/markdown"
	"github.com/neverbot/maestro/internal/metamodel"
	"github.com/neverbot/maestro/internal/projects"
	"github.com/neverbot/maestro/internal/views"
)

// ToolReferenceHeader is the first line of the generated tool index. It
// is exported so the generator and the test that diffs its output can
// both name it, and so a reader who opens reference/tools.md is told in
// its first line that editing it by hand is pointless.
const ToolReferenceHeader = "<!-- generated by cmd/maestro-skilldoc; do not edit -->"

// ToolReferencePath is where the generated index lives in the bundle,
// relative to skill.Files(). The generator writes it and
// TestToolReferenceIsCurrent reads it back.
const ToolReferencePath = "reference/tools.md"

// ToolReference is the bundle's reference/tools.md, generated from the
// tools this server registers and from nothing else.
//
// **It carries first sentences, not descriptions.** The full text of
// every description is already on the wire in the tool list an agent
// receives at connect time; a second copy in a file would be the drift
// this whole sub-project is built to refuse, and it would cost an agent
// the same tokens twice. What the wire does not give is grouping and a
// one-line answer to "which of these tools do I want", which is what
// this file is.
//
// TestToolReferenceIsCurrent regenerates this in memory and diffs it
// against the committed file, so a tool added, renamed or removed
// without regenerating fails the build.
// TestTheToolReferenceNamesEveryRegisteredTool then compares the
// committed file against the *server* rather than against this
// function, which is the half that catches a generator that skipped a
// domain — a file generated from a broken generator matches it forever.
func (s *Server) ToolReference() string {
	return toolReference(s.mcpToolDescriptions)
}

// toolReference is ToolReference's body, taking the table as an
// argument so the tests can drive it with a hand-built one.
func toolReference(descriptions map[string]string) string {
	names := make([]string, 0, len(descriptions))
	for name := range descriptions {
		names = append(names, name)
	}
	sort.Strings(names)

	groups := map[string][]string{}
	order := []string{}
	for _, name := range names {
		group := toolGroup(name)
		if _, seen := groups[group]; !seen {
			order = append(order, group)
		}
		groups[group] = append(groups[group], name)
	}
	sort.Strings(order)

	var b strings.Builder
	b.WriteString(ToolReferenceHeader)
	b.WriteString("\n# The tool surface\n\n")
	// The count is written from len(), not by hand. A hand-typed number
	// is a sentence that goes false on the next tool with nothing to
	// catch it.
	fmt.Fprintf(&b, "%d tools. Each one's full contract — every argument, every admitted\n", len(names))
	b.WriteString("value, every default, every bound and every refusal — is in its own\n")
	b.WriteString("description, which your client already has in the tool list it\n")
	b.WriteString("received when it connected. Nothing is repeated here, deliberately:\n")
	b.WriteString("a second copy of a contract is a copy that goes false quietly.\n\n")
	b.WriteString("This page is the index. What exists, which domain it belongs to, and\n")
	b.WriteString("one line each so you can tell which of them you want before you read\n")
	b.WriteString("any of them.\n")

	for _, group := range order {
		fmt.Fprintf(&b, "\n## %s\n\n", group)
		for _, name := range groups[group] {
			fmt.Fprintf(&b, "- `%s` — %s\n", name, firstSentence(descriptions[name]))
		}
	}
	return b.String()
}

// toolGroup is the domain a tool name belongs to: the prefix before its
// first dot, and "session" for the handful of tools that have no prefix
// at all (whoami, search). A group named after nothing would be an
// unlabelled heading, and an agent scanning for "the one about who I
// am" would have nowhere to look.
func toolGroup(name string) string {
	if before, _, found := strings.Cut(name, "."); found {
		return before
	}
	return "session"
}

// firstSentence is the tool's description up to and including its first
// full stop, flattened onto one line.
//
// It stops at a full stop followed by whitespace or end of text, which
// is why a description opening with `entities.upsert` or with a version
// number does not get cut in half at the dot inside it. Abbreviations
// that end in a dot and are followed by a space (`e.g.`, `i.e.`) are
// skipped explicitly: they are the one form the whitespace rule gets
// wrong, and both appear in descriptions this repository already ships.
func firstSentence(text string) string {
	flat := strings.Join(strings.Fields(text), " ")
	for i := 0; i < len(flat); i++ {
		if flat[i] != '.' {
			continue
		}
		if i+1 < len(flat) && flat[i+1] != ' ' {
			continue
		}
		if isAbbreviationEnd(flat[:i+1]) {
			continue
		}
		return flat[:i+1]
	}
	if flat == "" {
		return "(this tool was registered with no description)"
	}
	return flat
}

// isAbbreviationEnd reports whether a full stop closes an abbreviation
// rather than a sentence. The list is closed on purpose: a heuristic
// that guessed would cut a real sentence short somewhere and nobody
// would notice, and every entry here is a form that actually occurs in
// a registered description.
func isAbbreviationEnd(prefix string) bool {
	for _, abbreviation := range []string{"e.g.", "i.e.", "cf.", "vs.", "etc."} {
		if strings.HasSuffix(prefix, abbreviation) {
			return true
		}
	}
	return false
}

// NewToolReferenceServer builds a Server registered with every optional
// domain service present, purely so its tool table can be read. It
// executes no query and needs no database: the services are constructed
// over a nil connection pool, and registering a tool reads only the
// tool's own definition.
//
// It exists as one function, in this package, because
// cmd/maestro-skilldoc and TestToolReferenceIsCurrent must build the
// *same* server — a generator and a test that each assembled their own
// would agree with each other while both differing from the binary. The
// service list mirrors cmd/maestro's own NewServer call, and the tools
// of a domain are registered only when that domain's service is present
// (TestTheViewsToolsAreAbsentWithoutAViewsService), so a nil here is a
// whole domain missing from the bundle's index with nothing in this
// file to notice.
//
// It is what TestTheToolReferenceNamesEveryRegisteredTool is deliberately
// *not* built from: that test assembles its own server and compares the
// committed file against it, which is what catches this constructor
// dropping a service.
func NewToolReferenceServer() *Server {
	return NewServer(Options{
		Version:   "skilldoc",
		Identity:  identity.New(nil, config.Config{}),
		Projects:  projects.New(nil),
		Metamodel: metamodel.New(nil, nil),
		Markdown:  markdown.New(nil, nil),
		Views:     views.New(nil, nil),
		Analysis:  analysis.New(nil, nil),
	})
}
