package web

import (
	"fmt"
	"sort"
	"strings"

	"github.com/neverbot/maestro/internal/analysis"
	"github.com/neverbot/maestro/internal/config"
	"github.com/neverbot/maestro/internal/identity"
	"github.com/neverbot/maestro/internal/markdown"
	"github.com/neverbot/maestro/internal/metamodel"
	"github.com/neverbot/maestro/internal/projects"
	"github.com/neverbot/maestro/internal/views"
)

// ToolReferenceHeader is the first line of the generated tool index. It
// is exported so the generator and the test that diffs its output can
// both name it, and so a reader who opens reference/tools.md is told in
// its first line that editing it by hand is pointless.
const ToolReferenceHeader = "<!-- generated by cmd/maestro-skilldoc; do not edit -->"

// ToolReferencePath is where the generated index lives in the bundle,
// relative to skill.Files(). The generator writes it and
// TestToolReferenceIsCurrent reads it back.
const ToolReferencePath = "reference/tools.md"

// RouteReferencePath is where the generated route table lives in the
// bundle, relative to the bundle root.
const RouteReferencePath = "reference/rest.md"

// ToolReference is the bundle's reference/tools.md, generated from the
// tools this server registers and from nothing else.
func (s *Server) ToolReference() string {
	return toolReference(s.mcpToolDescriptions)
}

// toolReference is ToolReference's body, taking the table as an
// argument so the tests can drive it with a hand-built one.
func toolReference(descriptions map[string]string) string {
	names := make([]string, 0, len(descriptions))
	for name := range descriptions {
		names = append(names, name)
	}
	sort.Strings(names)

	groups := map[string][]string{}
	order := []string{}
	for _, name := range names {
		group := toolGroup(name)
		if _, seen := groups[group]; !seen {
			order = append(order, group)
		}
		groups[group] = append(groups[group], name)
	}
	sort.Strings(order)

	var b strings.Builder
	b.WriteString(ToolReferenceHeader)
	b.WriteString("\n# The tool surface\n\n")
	// The count is written from len(), not by hand. A hand-typed number
	// is a sentence that goes false on the next tool with nothing to
	// catch it.
	fmt.Fprintf(&b, "%d tools. Each one's full contract — every argument, every admitted\n", len(names))
	b.WriteString("value, every default, every bound and every refusal — is in its own\n")
	b.WriteString("description, which your client already has in the tool list it\n")
	b.WriteString("received when it connected. Nothing is repeated here, deliberately:\n")
	b.WriteString("a second copy of a contract is a copy that goes false quietly.\n\n")
	b.WriteString("This page is the index. What exists, which domain it belongs to, and\n")
	b.WriteString("one line each so you can tell which of them you want before you read\n")
	b.WriteString("any of them.\n")

	for _, group := range order {
		fmt.Fprintf(&b, "\n## %s\n\n", group)
		for _, name := range groups[group] {
			fmt.Fprintf(&b, "- `%s` — %s\n", name, firstSentence(descriptions[name]))
		}
	}
	return b.String()
}

// toolGroup is the domain a tool name belongs to: the prefix before its
// first dot, and "session" for the handful of tools that have no prefix
// at all (whoami, search). A group named after nothing would be an
// unlabelled heading, and an agent scanning for "the one about who I
// am" would have nowhere to look.
func toolGroup(name string) string {
	if before, _, found := strings.Cut(name, "."); found {
		return before
	}
	return "session"
}

// firstSentence is the tool's description up to and including its first
// full stop, flattened onto one line.
func firstSentence(text string) string {
	flat := strings.Join(strings.Fields(text), " ")
	for i := 0; i < len(flat); i++ {
		if flat[i] != '.' {
			continue
		}
		if i+1 < len(flat) && flat[i+1] != ' ' {
			continue
		}
		if isAbbreviationEnd(flat[:i+1]) {
			continue
		}
		return flat[:i+1]
	}
	if flat == "" {
		return "(this tool was registered with no description)"
	}
	return flat
}

// isAbbreviationEnd reports whether a full stop closes an abbreviation
// rather than a sentence. The list is closed on purpose: a heuristic
// that guessed would cut a real sentence short somewhere and nobody
// would notice, and every entry here is a form that actually occurs in
// a registered description.
func isAbbreviationEnd(prefix string) bool {
	for _, abbreviation := range []string{"e.g.", "i.e.", "cf.", "vs.", "etc."} {
		if strings.HasSuffix(prefix, abbreviation) {
			return true
		}
	}
	return false
}

// NewToolReferenceServer builds a Server registered with every optional
// domain service present, purely so its tool table can be read. It
// executes no query and needs no database: the services are constructed
// over a nil connection pool, and registering a tool reads only the
// tool's own definition.
func (s *Server) RouteReference() string {
	return routeReference(s.registeredPatterns)
}

// routeReference is RouteReference's body, taking the patterns as an
// argument so a test can drive it with a hand-built list.
func routeReference(patterns []string) string {
	// The chrome is not the API: a browser shell, the static files and
	// the MCP transport itself are not routes an agent calls.
	skip := func(path string) bool {
		return !strings.HasPrefix(path, "/api/")
	}
	type route struct{ method, path string }
	groups := map[string][]route{}
	order := []string{}
	for _, pattern := range patterns {
		method, path, found := strings.Cut(pattern, " ")
		if !found || skip(path) {
			continue
		}
		group := routeGroup(path)
		if _, seen := groups[group]; !seen {
			order = append(order, group)
		}
		groups[group] = append(groups[group], route{method: method, path: path})
	}
	sort.Strings(order)

	var out strings.Builder
	out.WriteString("<!-- generated by cmd/maestro-skilldoc; do not edit -->\n")
	out.WriteString("# The REST surface\n\n")
	out.WriteString("Every tool is mirrored by a route, and this is where they are. The\n")
	out.WriteString("contract is still the tool's own description — what each argument\n")
	out.WriteString("admits, what it defaults to, what it refuses — and this page carries\n")
	out.WriteString("none of it: see `reference/surface.md` for reading a description over\n")
	out.WriteString("either surface.\n\n")
	out.WriteString("`{game}` is a game's **slug**, from `whoami`. A body is JSON and\n")
	out.WriteString("`Content-Type: application/json` is required. Authenticate with\n")
	out.WriteString("`Authorization: Bearer <token>`, the same token the MCP transport\n")
	out.WriteString("takes.\n")
	for _, group := range order {
		out.WriteString("\n## " + group + "\n\n")
		rows := groups[group]
		sort.Slice(rows, func(i, j int) bool {
			if rows[i].path != rows[j].path {
				return rows[i].path < rows[j].path
			}
			return rows[i].method < rows[j].method
		})
		for _, row := range rows {
			out.WriteString("- `" + row.method + " " + row.path + "`\n")
		}
	}
	return out.String()
}

// routeGroup is the section a route is listed under: the segment after
// `/api/games/{game}/` where there is one, and the first segment
// otherwise, so the table reads in the same domains the tool index does.
func routeGroup(path string) string {
	rest := strings.TrimPrefix(path, "/api/")
	if after, ok := strings.CutPrefix(rest, "games/{game}/"); ok {
		segment, _, _ := strings.Cut(after, "/")
		return segment
	}
	segment, _, _ := strings.Cut(rest, "/")
	if segment == "" {
		return "instance"
	}
	return segment
}

func NewToolReferenceServer() *Server {
	return NewServer(Options{
		Version:   "skilldoc",
		Identity:  identity.New(nil, config.Config{}),
		Projects:  projects.New(nil),
		Metamodel: metamodel.New(nil, nil),
		Markdown:  markdown.New(nil, nil),
		Views:     views.New(nil, nil),
		Analysis:  analysis.New(nil, nil),
	})
}
