// Package style holds guards over the shape of the repository itself.
package style

import (
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The two ceilings on prose. Comments are the one thing here under no
// deletion pressure — the sources were 43% comment, 2.8 MB of it, with
// nothing red — so the share is measured rather than judged.
//
// A small package may be mostly contract, which is why the per-package
// ceiling is loose and only catches a runaway; the repository-wide one
// is what actually holds.
const (
	repoCeiling = 0.33
	pkgCeiling  = 0.55
	pkgFloor    = 20 * 1024 // packages smaller than this are not judged
)

func TestCommentShareStaysUnderTheCeiling(t *testing.T) {
	root := repoRoot(t)
	out, err := exec.Command("git", "-C", root, "ls-files", "*.go").Output()
	if err != nil {
		t.Fatalf("git ls-files: %v", err)
	}
	type tally struct{ code, comment int }
	pkgs := map[string]*tally{}
	var all tally
	for _, rel := range strings.Fields(string(out)) {
		src, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		if strings.Contains(string(src[:min(len(src), 400)]), "// Code generated by") {
			continue
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, rel, src, parser.ParseComments)
		if err != nil {
			t.Fatalf("parse %s: %v", rel, err)
		}
		comment := 0
		for _, cg := range file.Comments {
			comment += fset.Position(cg.End()).Offset - fset.Position(cg.Pos()).Offset
		}
		dir := filepath.Dir(rel)
		if pkgs[dir] == nil {
			pkgs[dir] = &tally{}
		}
		pkgs[dir].comment += comment
		pkgs[dir].code += len(src) - comment
		all.comment += comment
		all.code += len(src) - comment
	}

	if share := float64(all.comment) / float64(all.code+all.comment); share > repoCeiling {
		t.Errorf("the Go sources are %.0f%% comment, over the %.0f%% ceiling (%d KB of prose)",
			100*share, 100*repoCeiling, all.comment/1024)
	}
	for dir, tl := range pkgs {
		total := tl.code + tl.comment
		if total < pkgFloor {
			continue
		}
		if share := float64(tl.comment) / float64(total); share > pkgCeiling {
			t.Errorf("%s is %.0f%% comment, over the %.0f%% ceiling (%d KB of prose)",
				dir, 100*share, 100*pkgCeiling, tl.comment/1024)
		}
	}
}

func repoRoot(t *testing.T) string {
	t.Helper()
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		t.Fatalf("git rev-parse: %v", err)
	}
	return strings.TrimSpace(string(out))
}
