package graph_test

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/uuid"

	"github.com/neverbot/maestro/internal/graph"
)

var updateGolden = flag.Bool("update", false, "rewrite the golden statement in testdata")

// goldenCases are the three emitter shapes the golden file holds: the
// plain out-walk, an Any walk carrying a caller's edge predicate and a
// row cap -- which is the shape internal/analysis compiles into -- and a
// capped In walk with a min depth. Between them they exercise every
// branch of WalkCTE that puts text on the page. Nothing here binds a
// uuid into the *statement*, so the text is deterministic: the project
// id, the relation types and the seed's own values are all arguments.
var goldenCases = []struct {
	name string
	walk graph.Walk
}{
	{"out_basic", graph.Walk{
		Name: "w", SeedSQL: "SELECT id FROM entities WHERE project_id = $1 AND id = $2",
		SeedArgs: []any{uuid.Nil, uuid.Nil}, Direction: graph.Out, MinDepth: 0, MaxDepth: 3,
	}},
	{"any_predicate_capped", graph.Walk{
		Name:     "s3",
		SeedSQL:  "SELECT id FROM entities WHERE project_id = $1 AND entity_type_id = $2",
		SeedArgs: []any{uuid.Nil, uuid.Nil},
		EdgePredicate: "((r.relation_type_id = ANY($1::uuid[]) AND r.source_id = w.id)" +
			" OR (r.relation_type_id = ANY($2::uuid[]) AND r.target_id = w.id))",
		EdgeArgs:  []any{[]uuid.UUID{}, []uuid.UUID{}},
		Direction: graph.Any, MinDepth: 1, MaxDepth: 25, MaxRows: 50_000,
	}},
	{"in_min_depth_capped", graph.Walk{
		Name: "t1", SeedSQL: "SELECT id FROM entities WHERE project_id = $1",
		SeedArgs:  []any{uuid.Nil},
		Direction: graph.In, MinDepth: 2, MaxDepth: 2, MaxRows: 10,
	}},
}

func goldenText() string {
	var b strings.Builder
	for _, c := range goldenCases {
		sql, _ := graph.WalkCTE(c.walk)
		b.WriteString("-- case: " + c.name + "\n")
		b.WriteString(sql)
		b.WriteString("\n\n")
	}
	return b.String()
}

// TestAWalkWithoutTheRelationPathEmitsTheSameStatementItAlwaysDid is the
// proof that CarryRelationPath is opt-in *as text*, and it is a golden
// file rather than a set of substring assertions because the claim is
// byte-identity and a substring assertion cannot make that claim.
//
// The checked-in file was generated by the emitter as it stood **before**
// CarryRelationPath existed -- HEAD's walk.go, compiled in a throwaway
// module -- so this test compares today's output against yesterday's
// bytes and not against its own.
//
// internal/views' three golden files are the second, wider half of the
// same claim: that package compiles traversal steps through this emitter
// and asserts the whole statement, so a column that leaked into an
// unasked-for walk moves them too.
func TestAWalkWithoutTheRelationPathEmitsTheSameStatementItAlwaysDid(t *testing.T) {
	t.Parallel()
	path := filepath.Join("testdata", "walk_without_relation_path.sql")
	got := goldenText()
	if *updateGolden {
		if err := os.WriteFile(path, []byte(got), 0o600); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		return
	}
	want, err := os.ReadFile(path) //nolint:gosec // a fixed testdata path
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if got != string(want) {
		t.Errorf("the emitted statement moved without CarryRelationPath being asked for.\n"+
			"got:\n%s\nwant:\n%s", got, want)
	}
}

// TestAWalkWithTheRelationPathAddsExactlyOneColumn is the other half: the
// opt-in has to change something, or the golden test above is green over
// a field that does nothing. It asserts the three fragments and that the
// rest of the statement is untouched.
func TestAWalkWithTheRelationPathAddsExactlyOneColumn(t *testing.T) {
	t.Parallel()
	w := goldenCases[0].walk
	plain, _ := graph.WalkCTE(w)
	w.CarryRelationPath = true
	carried, _ := graph.WalkCTE(w)

	if plain == carried {
		t.Fatalf("CarryRelationPath changed nothing in the emitted statement:\n%s", plain)
	}
	for _, frag := range []string{"(id, depth, path, rel_path, via_relation",
		"ARRAY[seed.id], ARRAY[]::uuid[]", "w.rel_path || r.id"} {
		if !strings.Contains(carried, frag) {
			t.Errorf("the carried statement does not contain %q:\n%s", frag, carried)
		}
	}
	// Removing the three fragments must give back the plain statement
	// exactly: anything else is a second change riding along with this
	// one, which is what a golden file exists to catch.
	back := carried
	for _, frag := range []string{", rel_path", ", ARRAY[]::uuid[]", ", w.rel_path || r.id"} {
		back = strings.Replace(back, frag, "", 1)
	}
	if back != plain {
		t.Errorf("the relation path changed more than its own three fragments.\ngot:\n%s\nwant:\n%s",
			back, plain)
	}
}
