package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// buildSite builds the whole site into a temporary directory and returns
// every page it wrote, keyed by its path.
//
// **Every guard here reads the built site rather than the generator.** A
// test that asserted this file's own strings would pass over a page that
// never reached the disk, which is the "correct in the module, dead at
// the call site" defect this repository keeps finding.
func buildSite(t *testing.T) map[string]string {
	t.Helper()
	out := t.TempDir()
	if err := build("../..", out); err != nil {
		t.Fatalf("build the site: %v", err)
	}
	pages := map[string]string{}
	err := filepath.WalkDir(out, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(p, ".html") {
			return err
		}
		body, err := os.ReadFile(p) // #nosec G304 -- a path this test just wrote
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(out, p)
		if err != nil {
			return err
		}
		pages[filepath.ToSlash(rel)] = string(body)
		return nil
	})
	if err != nil {
		t.Fatalf("walk the built site: %v", err)
	}
	if len(pages) < 20 {
		t.Fatalf("built %d page(s): the bundle alone is nineteen, so this guard is holding nothing", len(pages))
	}
	return pages
}

// TestEveryPageWearsTheSameFrame holds the one shape this site has.
//
// The design-system page used to be copied whole: it arrived with its
// own header, its own wordmark, twice every other page's width and no
// link back to anywhere — the only page on the site that was not part of
// it. It is generated by docs/design-system.mjs between two markers now,
// and wrapped here like every other page. This is what stops that from
// coming back, and it names the page explicitly because that page is the
// one the rule was broken for.
func TestEveryPageWearsTheSameFrame(t *testing.T) {
	pages := buildSite(t)
	if _, ok := pages["design-system.html"]; !ok {
		t.Fatal("the site has no design-system.html: this guard exists for that page")
	}
	for path, body := range pages {
		for _, part := range []struct{ what, needle string }{
			{"the skip link", `class="skip"`},
			{"the header bar", `<header><div class="bar">`},
			{"the content sheet", `<main id="content">`},
			{"the rail", `<nav class="rail"`},
			{"the site stylesheet", `style.css"`},
		} {
			if !strings.Contains(body, part.needle) {
				t.Errorf("%s carries no %s (%q)", path, part.what, part.needle)
			}
		}
		if strings.Count(body, "<main") != 1 {
			t.Errorf("%s has %d <main> elements: a page has exactly one", path, strings.Count(body, "<main"))
		}
	}
}

// TestTheFrameIsTheOneDesignDotMdStates is the "prose about code" guard
// pointed at the site's own layout.
//
// docs/design.md's page frame gives the numbers: 1440px maximum width,
// 24px gutters, a 280px rail, a 48px header. The first version of this
// stylesheet copied the header's height and the paper colour and then
// set `main { max-width: 46rem }`, which is the measure design.md says
// belongs to the prose role and never to the page — the exact defect the
// document records as already fixed once, re-committed on the site that
// publishes the document.
func TestTheFrameIsTheOneDesignDotMdStates(t *testing.T) {
	stated, err := os.ReadFile("../../docs/design.md")
	if err != nil {
		t.Fatalf("read docs/design.md: %v", err)
	}
	document := string(stated)
	frame := map[string]string{
		"--page":   "1440px",
		"--rail":   "280px",
		"--bar":    "48px",
		"--gutter": "24px",
	}
	for token, value := range frame {
		if !strings.Contains(siteCSS, token+": "+value) {
			t.Errorf("the site's stylesheet does not declare %s: %s", token, value)
		}
		if !strings.Contains(document, value) {
			t.Errorf("docs/design.md no longer states %s anywhere, and the stylesheet still sets %s to it",
				value, token)
		}
	}
	if strings.Contains(siteCSS, "max-width: 46rem") {
		t.Error("the page is set to a prose measure again: docs/design.md's frame caps the page at " +
			"1440px and gives 68ch to the prose role alone")
	}
}

// TestTheHeaderPromisesAPageAndNotAnAnchor holds the fix for the link
// the owner could not place.
//
// "For agents" pointed at `index.html#for-agents`: an h2 nine tenths of
// the way down the readme, so the reader landed with the navigation
// scrolled off the top, looking at nineteen bullets in repository order
// with the bundle's own entry point last. A label that promises a
// destination gets one.
func TestTheHeaderPromisesAPageAndNotAnAnchor(t *testing.T) {
	pages := buildSite(t)
	index, ok := pages[agentsIndexPath]
	if !ok {
		t.Fatalf("the site has no %s", agentsIndexPath)
	}
	for path, body := range pages {
		if strings.Contains(body, `href="index.html#for-agents">For agents`) {
			t.Errorf("%s still sends For agents at an anchor into the readme", path)
		}
		if !strings.Contains(body, `For agents</a>`) {
			t.Errorf("%s has no For agents link at all", path)
		}
	}
	// Every bundle page is on it, under a group heading.
	bundle, err := bundlePages()
	if err != nil {
		t.Fatalf("render the bundle: %v", err)
	}
	for _, p := range bundle {
		href := strings.TrimPrefix(p.Path, "agents/")
		if !strings.Contains(index, `href="`+href+`"`) {
			t.Errorf("%s does not link %s", agentsIndexPath, href)
		}
	}
	for _, label := range groupLabels {
		if !strings.Contains(index, ">"+label+"<") {
			t.Errorf("%s does not group anything under %q", agentsIndexPath, label)
		}
	}
	// And the entry point is first, which is what the path order got
	// wrong: `agents/genres/...` sorts before `agents/skill.md`.
	if first := strings.Index(index, `href="skill.html"`); first < 0 {
		t.Error("the bundle's own entry point is not linked from its index")
	} else if other := strings.Index(index, `href="genres/`); other >= 0 && other < first {
		t.Error("the index still leads with the worked examples: skill is where an agent starts")
	}
}

// TestNoPageFetchesAnotherOrigin holds the CSP argument on a site that
// has no CSP.
//
// The readme's two shields.io badges rendered as the only chromatic
// pixels above the fold — a saturated blue and an orange belonging to
// neither of this palette's two chromatic exemptions — and they are
// GitHub's chrome verbatim, which docs/product.md names as an
// anti-reference. They are also two requests to a third-party origin
// from a product whose own front end forbids exactly that.
func TestNoPageFetchesAnotherOrigin(t *testing.T) {
	for path, body := range buildSite(t) {
		for _, attr := range []string{`<img`, `<script`} {
			for _, fragment := range strings.Split(body, attr)[1:] {
				tag, _, _ := strings.Cut(fragment, ">")
				if strings.Contains(tag, `src="http`) {
					t.Errorf("%s fetches %s from another origin: %s", path, attr, strings.TrimSpace(tag))
				}
			}
		}
	}
}

// TestTheSiteAnswersAMistypedAddress is the third negative state on the
// one surface that can reach it: GitHub Pages serves /404.html for a
// path it does not have, and without one the reader leaves the design
// entirely at the moment they most need a way back.
func TestTheSiteAnswersAMistypedAddress(t *testing.T) {
	pages := buildSite(t)
	body, ok := pages["404.html"]
	if !ok {
		t.Fatal("the site has no 404.html")
	}
	if !strings.Contains(body, `href="index.html"`) {
		t.Error("the refusal page offers no way back")
	}
}

// TestEverySectionCanBeLinked: a page whose headings have no ids is a
// page whose rail cannot point at them and whose sections cannot be
// sent to anybody.
func TestEverySectionCanBeLinked(t *testing.T) {
	for path, body := range buildSite(t) {
		if strings.Contains(body, "<h2>") && !strings.Contains(body, `<nav class="rail"`) {
			t.Errorf("%s has an h2 with no id", path)
		}
		// The rail's own headings are the exception: they are furniture,
		// not sections of the page.
		content := body
		if from := strings.Index(body, `<nav class="rail"`); from >= 0 {
			content = body[:from]
		}
		if strings.Contains(content, "<h2>") {
			t.Errorf("%s carries an h2 with no id, so nothing can link to it", path)
		}
	}
}

// TestTheRailsGroupsAreTheBundleAndNothingElse.
//
// `groupOf` answered "" for a page in the bundle's root *and* for a page
// that is not in the bundle at all, so the rail beside `skill.html`
// offered "Start here: License, Design system, Maestro skill, Nothing
// here" — the licence and the 404 page, filed under where to begin.
func TestTheRailsGroupsAreTheBundleAndNothingElse(t *testing.T) {
	pages, err := collect("../..")
	if err != nil {
		t.Fatalf("collect the pages: %v", err)
	}
	for _, group := range grouped(pages) {
		for _, p := range group {
			if !strings.HasPrefix(p.Path, "agents/") {
				t.Errorf("%s is not a page of the bundle and the rail groups it under %q",
					p.Path, groupLabels[groupOf(group[0])])
			}
		}
	}
}
